type: logs
title: GHAS Dependabot
streams:
  - input: httpjson
    vars:
      - name: access_token
        type: password
        title: Personal Access Token
        description: The GitHub Personal Access Token. \nSee [Authenticating with GraphQL](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql)
        multi: false
        required: true
        show_user: true
        secret: true
      - name: owner
        type: text
        title: Repository owner
        description: The owner of GitHub Repository
        multi: false
        required: true
        show_user: true
      - name: repo
        type: text
        title: Repository
        description: The GitHub Repository
        multi: false
        required: false
        show_user: true
      - name: http_client_timeout
        type: text
        title: HTTP Client Timeout
        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are ns, us, ms, s, m, h.
        multi: false
        required: false
        show_user: true
        default: 60s
      - name: interval
        type: text
        title: Interval
        multi: false
        required: true
        show_user: true
        description: Interval at which the alerts will be pulled. The value must be between 2m and 1h. Supported units for this parameter are h/m/s.
        default: 10m
      - name: api_url
        type: text
        title: API URL.
        description: The API URL without the path.
        multi: false
        required: true
        show_user: false
        default: https://api.github.com
      - name: ssl
        type: yaml
        title: SSL
        multi: false
        required: false
        show_user: false
      - name: proxy_url
        type: text
        title: Proxy URL
        multi: false
        required: false
        show_user: false
        description: URL to proxy connections in the form of http[s]://<user>:<password>@<server name/ip>:<port>
      - name: tags
        type: text
        title: Tags
        multi: true
        required: true
        show_user: true
        default:
          - forwarded
          - github-dependabot
      - name: preserve_original_event
        required: true
        show_user: true
        title: Preserve original event
        description: Preserves a raw copy of the original event, added to the field `event.original`
        type: bool
        multi: false
        default: false
      - name: processors
        type: yaml
        title: Processors
        multi: false
        required: false
        show_user: false
        description: >
          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata.  This executes in the agent before the logs are parsed.  See [Processors](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) for details.

    template_path: httpjson.yml.hbs
    title: GHAS Dependabot
    description: Collect GitHub Advanced Security Dependabot alerts via the API
