fields:
  - name: 'timestamp'
    period: -24h # one day
  - name: agent.id
    value: "ef5e274d-4b53-45e6-943a-a5bcf1a6f523"
  - name: service.address
    enum: ["elastic-package-service-nginx-1", "elastic-package-service-nginx-2", "elastic-package-service-nginx-3"]
  - name: event.duration
    range:
      min: 1
      max: 1000
  - name: accepts
    range:
      min: 1
      max: 100
  - name: active
    range:
      min: 1
      max: 100
  - name: current
    range:
      min: 1
      max: 100
  - name: dropped
    range:
      min: 1
      max: 100
  - name: handled
    range:
      min: 1
      max: 100
  - name: reading
    range:
      min: 1
      max: 100
  - name: requests
    range:
      min: 1
      max: 100
  - name: waiting
    range:
      min: 1
      max: 100
  - name: writing
    range:
      min: 1
      max: 100
