version: "2.3"
services:
  zscaler-zia-alerts-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9010 -p=tcp /sample_logs/alerts.log
  zscaler-zia-dns-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9011 -p=tcp /sample_logs/dns.log
  zscaler-zia-firewall-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9012 -p=tcp /sample_logs/firewall.log
  zscaler-zia-tunnel-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9013 -p=tcp /sample_logs/tunnel.log
  zscaler-zia-web-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9014 -p=tcp /sample_logs/web.log
  zscaler-zia-dns-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9556/
      - STREAM_WEBHOOK_HEADER=Content-Type=application/ndjson
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/dns-http_endpoint.log
  zscaler-zia-firewall-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9557/
      - STREAM_WEBHOOK_HEADER=Content-Type=application/ndjson
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/firewall-http_endpoint.log
  zscaler-zia-tunnel-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9558/
      - STREAM_WEBHOOK_HEADER=Content-Type=application/ndjson
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/tunnel-http_endpoint.log
  zscaler-zia-web-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9559/
      - STREAM_WEBHOOK_HEADER=Content-Type=application/ndjson
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/web-http_endpoint.log
