fields:
  - name: confidence
    cardinility: 100
  - name: created_by
    period: -24h
  - name: created_ts
    period: -24h
  - name: expiration_ts
    period: -24h
  - name: feed_id
    cardinility: 1000000
  - name: id
    cardinility: 1000000
  - name: itype
    enum:
      - mal_ip
      - mal_domain
      - mal_url
      - parked_ip
      - parked_email
      - parked_url
  - name: meta_detail2
    enum:
      - imported by user 142
      - imported by user 143
  - name: meta_severity
    enum:
      - low
      - medium
      - high
      - very-high
  - name: modified_ts
    period: -24h
  - name: org
    enum:
      - Domains by Proxy, LLC
      - Alicloud-hk
  - name: owner_organization_id
    cardinility: 1000000
  - name: resource_uri
    enum:
      - "/api/v2/intelligence/232020126/"
      - "/api/v2/intelligence/235548914/"
      - "/api/v2/intelligence/184982668/"
  - name: retina_confidence
    cardinility: 100
  - name: sort
    cardinility: 1000000
  - name: source
    enum:
      - Analyst
      - Default Organization
  - name: source_reported_confidence
    cardinility: 100
  - name: status
    enum:
      - active
      - inactive
  - name: tags_id
    cardinility: 1000000
  - name: tags_name
    enum:
      - Domains-contacted-by-samples-which-do-public-IP-checks.
      - public-ip-check-dns
      - md5-3d4bf45cc1648d76f9770c7c27afc4b8
  - name: threat_type
    enum:
      - bot
      - apt
      - c2
      - i2p
      - malware
  - name: threatscore
    cardinility: 100
  - name: timestamp
    period: -24h
  - name: tlp
    enum:
      - WHITE
      - AMBER
  - name: trusted_circle_ids
    cardinility: 1000000
  - name: type
    enum:
      - domain
      - ip
      - url
  - name: update_id
    cardinility: 1000000
  - name: uuid
    cardinility: 1000000
  - name: value
    enum:
      - "test_mail_remote@test.com"
      - "test_mail_remote2@test.com"
      - "test_mail_remote3@test.com"
      - "test_mail_remote4@test.com"
      - "test_mail_remote5@test.com"
