# newer versions go on top
- version: 2.10.0
  changes:
    - description: Bump format version, fix definition of 'docker.container.labels.*' fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9634
- version: 2.9.0
  changes:
    - description: Adapt fields for changes in file system info
      type: enhancement
      link: https://github.com/elastic/integrations/pull/8068
- version: "2.8.3"
  changes:
    - description: Migrate Docker Overview dashboard to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7942
- version: "2.8.2"
  changes:
    - description: Fix mapping for `message` to align with ECS.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/7964
- version: "2.8.1"
  changes:
    - description: Remove confusing documentation about Windows support.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7645
- version: "2.8.0"
  changes:
    - description: Enable time series data streams for the metrics datasets, except for event dataset. This improves storage usage and query performance. For more details, see https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6647
- version: "2.7.0"
  changes:
    - description: Add network.interface as dimension
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6646
- version: "2.6.0"
  changes:
    - description: Add permissions to reroute events to logs-*-* for container_logs datastream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6340
- version: "2.5.1"
  changes:
    - description: Set dimension fields to metrics data streams, except for event.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6390
- version: "2.5.0"
  changes:
    - description: Add metric type to diskio data stream.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6392
- version: "2.4.3"
  changes:
    - description: Added link to docs for condition filter
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5586
- version: "2.4.2"
  changes:
    - description: Added categories and/or subcategories.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5123
- version: "2.4.1"
  changes:
    - description: Add link to docker available keys
      type: enhancement
      link: http://github.com/elastic/integrations/pull/4952
- version: "2.4.0"
  changes:
    - description: Improve package description and titles
      type: enhancement
      link: http://github.com/elastic/integrations/pull/4919
- version: "2.3.0"
  changes:
    - description: Add container_logs
      type: enhancement
      link: http://github.com/elastic/integrations/pull/4716
- version: "2.2.0"
  changes:
    - description: Add skip_major flag
      type: bugfix
      link: http://github.com/elastic/integrations/pull/3254
- version: "2.1.1"
  changes:
    - description: Fix missing dedot options
      type: bugfix
      link: http://github.com/elastic/integrations/pull/2830
- version: "2.1.0"
  changes:
    - description: Add new ECS container fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3056
- version: "2.0.1"
  changes:
    - description: Add documentation for multi-fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2916
- version: "2.0.0"
  changes:
    - description: Remove deprecated fields
      type: breaking-change
      link: http://github.com/elastic/integrations/pull/2733
- version: "1.2.0"
  changes:
    - description: Release package for 8.0.0
      type: enhancement
      link: http://github.com/elastic/integrations/pull/2678
- version: "1.1.1"
  changes:
    - description: Uniform with guidelines
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2012
- version: "1.1.0"
  changes:
    - description: Update to ECS 1.12.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1691
- version: "1.0.0"
  changes:
    - description: Release Docker as GA
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1571
- version: "0.5.1"
  changes:
    - description: Escape special characters in docs
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1405
- version: "0.5.0"
  changes:
    - description: Update documentation to fit mdx spec
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1401
- version: "0.4.0"
  changes:
    - description: Update integration description
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1364
- version: "0.3.0"
  changes:
    - description: Set "event.module" and "event.dataset"
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1231
- version: "0.2.1"
  changes:
    - description: Fix data types of some fields in the `cpu` data stream
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1081
- version: "0.2.0"
  changes:
    - description: Render units and metric types in exported fields table
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1028
- version: "0.1.1"
  changes:
    - description: Fix compatibility with Kibana
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/740
- version: "0.1.0"
  changes:
    - description: initial release
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/632
