# newer versions go on top
- version: "2.0.0"
  changes:
    - description: Remove deprecated fields
      type: breaking-change
      link: http://github.com/elastic/integrations/pull/2733
- version: "1.2.0"
  changes:
    - description: Release package for 8.0.0
      type: enhancement
      link: http://github.com/elastic/integrations/pull/2678
- version: "1.1.1"
  changes:
    - description: Uniform with guidelines
      type: enhancement
      link: |
        https://github.com/elastic/integrations/pull/2012
- version: "1.1.0"
  changes:
    - description: Update to ECS 1.12.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1691
- version: "1.0.0"
  changes:
    - description: Release Docker as GA
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1571
- version: "0.5.1"
  changes:
    - description: Escape special characters in docs
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1405
- version: "0.5.0"
  changes:
    - description: Update documentation to fit mdx spec
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1401
- version: "0.4.0"
  changes:
    - description: Update integration description
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1364
- version: "0.3.0"
  changes:
    - description: Set "event.module" and "event.dataset"
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1231
- version: "0.2.1"
  changes:
    - description: Fix data types of some fields in the `cpu` data stream
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1081
- version: "0.2.0"
  changes:
    - description: Render units and metric types in exported fields table
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1028
- version: "0.1.1"
  changes:
    - description: Fix compatibility with Kibana
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/740
- version: "0.1.0"
  changes:
    - description: initial release
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/632
