name: docker
title: Docker
version: 2.10.0
description: Collect metrics and logs from Docker instances with Elastic Agent.
type: integration
icons:
  - src: /img/logo_docker.svg
    title: logo docker
    size: 32x32
    type: image/svg+xml
screenshots:
  - src: /img/docker-overview.png
    title: Docker Overview
    size: 5120x2562
    type: image/png
format_version: 2.13.0
categories:
  - observability
  - containers
conditions:
  kibana.version: ^8.8.0
policy_templates:
  - name: docker
    title: Docker logs and metrics
    description: Collect logs and metrics from Docker instances
    inputs:
      - type: docker/metrics
        title: Collect Docker metrics
        description: Collecting container, cpu, diskio, event, healthcheck, image, info, memory and network metrics from Docker instances
      - type: filestream
        title: Collect Docker container logs
        description: Collecting docker container logs
owner:
  github: elastic/obs-cloudnative-monitoring
