name: docker
title: Docker
version: 0.5.1
release: beta
description: This Elastic integration fetches metrics from Docker instances
type: integration
icons:
  - src: /img/logo_docker.svg
    title: logo docker
    size: 32x32
    type: image/svg+xml
screenshots:
  - src: /img/docker-overview.png
    title: Docker Overview
    size: 5120x2562
    type: image/png
format_version: 1.0.0
license: basic
categories:
  - containers
  - os_system
conditions:
  kibana.version: ^7.14.0
policy_templates:
  - name: docker
    title: Docker metrics
    description: Collect metrics from Docker instances
    inputs:
      - type: docker/metrics
        title: Collect Docker metrics
        description: Collecting container, cpu, diskio, event, healthcheck, image, info, memory and network metrics from Docker instances
owner:
  github: elastic/integrations
