- name: cloud
  type: group
  fields:
    - name: account.id
      type: keyword
      dimension: true
      description: Cloud account ID.
    - name: availability_zone
      type: keyword
      dimension: true
      description: Cloud availability zone.
    - name: instance.id
      type: keyword
      dimension: true
      description: Cloud instance ID.
    - name: provider
      type: keyword
      dimension: true
      description: Cloud provider name.
    - name: region
      type: keyword
      dimension: true
      description: Cloud region.
    - name: image.id
      type: keyword
      description: Image ID for the cloud instance.
- name: container
  type: group
  fields:
    - name: id
      type: keyword
      dimension: true
      description: Container ID.
- name: host
  type: group
  fields:
    - name: name
      type: keyword
      dimension: true
      description: Host name.
    - name: containerized
      type: boolean
      description: Whether the host is a container.
    - name: os.build
      type: keyword
      description: OS build information.
    - name: os.codename
      type: keyword
      description: OS codename, if any.
