- external: ecs
  name: ecs.version
- external: ecs
  name: error.message
- external: ecs
  name: event.kind
- external: ecs
  name: service.address
  dimension: true
- external: ecs
  name: service.name
  dimension: true
