- name: prometheus
  type: group
  fields:
    - name: labels.*
      type: object
      description: |
        Prometheus metric labels
    - name: metrics.*
      type: object
      description: |
        Prometheus metric