version: "2.3"
services:
  abusech:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config.yml
  abusech-threatfox:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8081
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8081
    command:
      - http-server
      - --addr=:8081
      - --config=/files/config-threatfox.yml
