title: Kubernetes Job metrics
release: experimental
type: metrics
streams:
  - input: kubernetes/metrics
    enabled: false
    vars:
      - name: add_metadata
        type: bool
        title: Add Metadata
        multi: false
        required: true
        show_user: true
        default: true
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - kube-state-metrics:8080
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
    title: Kubernetes Job metrics
    description: Collect Kubernetes Job metrics from kube_state_metrics
