version: '2.3'
services:
  m365-defender-log-http:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./log-http-mock-config.yml:/config.yml
    environment:
      PORT: 8080
    command:
      - http-server
      - --exit-on-unmatched-rule
      - --addr=:8080
      - --config=/config.yml
  m365-defender-incident-http:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./incident-http-mock-config.yml:/config.yml
    environment:
      PORT: 8080
    command:
      - http-server
      - --exit-on-unmatched-rule
      - --addr=:8080
      - --config=/config.yml
  m365-defender-alert-http:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./alert-http-mock-config.yml:/config.yml
    environment:
      PORT: 8080
    command:
      - http-server
      - --exit-on-unmatched-rule
      - --addr=:8080
      - --config=/config.yml
