# newer versions go on top
- version: "1.16.0"
  changes:
    - description: Remove labels fingerprint for TSDB purposes.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9785
- version: "1.15.3"
  changes:
    - description: Adding ssl verfication mode and removing default username for collector
      type: bugfix
      link: https://github.com/elastic/integrations/pull/10088
- version: "1.15.2"
  changes:
    - description: Fix typo - Replace "darastream" with "datastream"
      type: bugfix
      link: https://github.com/elastic/integrations/pull/7914
- version: "1.15.1"
  changes:
    - description: Add a "period" parameter to the counter cache.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/9424
- version: "1.15.0"
  changes:
    - description: Enable secrets for sensitive fields. For more details, refer https://www.elastic.co/guide/en/fleet/current/agent-policy.html#agent-policy-secret-values
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9321
- version: "1.14.2"
  changes:
    - description: Disable secrets for older stack versions due to errors.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/9279
- version: "1.14.1"
  changes:
    - description: Add Certificate Authorities for Remote Write
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9264
- version: "1.14.0"
  changes:
    - description: Enable 'secret' for the sensitive fields, supported from 8.12.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9009
- version: "1.13.1"
  changes:
    - description: Migrate Prometheus Server Overview dashboard to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/8016
- version: "1.13.0"
  changes:
    - description: Ensure event.kind is correctly set for pipeline errors.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7082
- version: "1.12.1"
  changes:
    - description: Fix remote_write ingest pipeline to include both metric path 'prometheus.*' and 'prometheus.metrics.*' to fingerprint calculation
      type: bugfix
      link: https://github.com/elastic/integrations/pull/7882
- version: "1.12.0"
  changes:
    - description: Use ecs definition of the 'event.dataset' field
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7667
- version: "1.11.0"
  changes:
    - description: Enable TSDB by default for remote_write datastreams. This improves storage usage and query performance. For more details, see https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7598
- version: "1.10.0"
  changes:
    - description: Align fingerprint field name across all datastreams, add handling of pipeline failures to the collector and query datastreams
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7594
- version: "1.9.0"
  changes:
    - description: Add dimension and metric_type fields to remote_write datastream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7565
- version: "1.8.0"
  changes:
    - description: Enable TSDB by default for collector and query metrics data streams. This improves storage usage and query performance. For more details, see https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html. Still TSDB is not supported for remote_write
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7261
- version: "1.7.0"
  changes:
    - description: Revert metrics field definition to the format used before introducing metric_type
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7324
- version: "1.6.0"
  changes:
    - description: Add metric_type fields to collector and query datastreams for TSDB support
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6981
- version: "1.5.0"
  changes:
    - description: Add dimension fields to collector and query datastreams for TSDB support
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5974
- version: "1.4.0"
  changes:
    - description: Add processor configuration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6536
- version: "1.3.2"
  changes:
    - description: Fix timeout and connect_timeout parameter parsing issue
      type: bugfix
      link: https://github.com/elastic/integrations/pull/6140
- version: "1.3.1"
  changes:
    - description: Added categories and/or subcategories.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5123
- version: "1.3.0"
  changes:
    - description: Support data_stream.dataset name
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5336
- version: "1.2.0"
  changes:
    - description: Enable setting condition on Prometheus Collector
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5317
- version: "1.1.0"
  changes:
    - description: Remove "integration" from the package name
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4983
- version: "1.0.1"
  changes:
    - description: Removing x-pack references and updating default values
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4545
- version: "1.0.0"
  changes:
    - description: Promote integration to GA
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4315
- version: "0.14.0"
  changes:
    - description: Update default dashboard
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4275
- version: "0.13.0"
  changes:
    - description: Revert index mapping changes for histogram type
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4060
- version: "0.12.0"
  changes:
    - description: Disable leader election by default, remove bearer token file default value
      type: bugfix
      link: https://github.com/elastic/integrations/pull/4034
- version: "0.11.0"
  changes:
    - description: Fix histogram type in collector data_stream
      type: bugfix
      link: https://github.com/elastic/integrations/pull/3891
- version: "0.10.0"
  changes:
    - description: Hide some configuration for remote_write data_stream; Add leader election for collector and query data_streams
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3662
- version: "0.9.2"
  changes:
    - description: reworded a link to related documentation in the Readme so it is clearer
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2916
- version: "0.9.1"
  changes:
    - description: Add documentation for multi-fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2916
- version: "0.9.0"
  changes:
    - description: Add standard HTTP options to the package
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2632
- version: "0.8.0"
  changes:
    - description: Improve default datastream enablement
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2619
- version: "0.7.0"
  changes:
    - description: Release prometheus package for v8.0.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2189
- version: "0.6.1"
  changes:
    - description: Uniform with guidelines
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2050
- version: "0.6.0"
  changes:
    - description: Update to ECS 1.12.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1705
- version: "0.5.1"
  changes:
    - description: Escape special characters in docs
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1405
- version: "0.5.0"
  changes:
    - description: Update integration description
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1364
- version: "0.4.1"
  changes:
    - description: Fix yml code blocks
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1323
- version: "0.4.0"
  changes:
    - description: Set `event.module` and `event.dataset`
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1249
- version: "0.3.5"
  changes:
    - description: Updating package owner
      type: enhancement
      link: https://github.com/elastic/integrations/pull/766
- version: "0.3.4"
  changes:
    - description: Correct sample event file.
      type: bugfix # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/754
- version: "0.3.3"
  changes:
    - description: Change kibana.version constraint to be more conservative.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/749
- version: "0.1.0"
  changes:
    - description: initial release
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/114
