format_version: 1.0.0
name: prometheus
title: Prometheus
version: 1.3.2
license: basic
description: Collect metrics from Prometheus servers with Elastic Agent.
type: integration
categories:
  - web
release: ga
conditions:
  kibana.version: "^8.4.0"
screenshots:
  - src: /img/prometheus-server-overview.png
    title: Metricbeat Prometheus Overview
    size: 5010x2676
    type: image/png
icons:
  - src: /img/logo_prometheus.svg
    title: logo prometheus
    size: 32x32
    type: image/svg+xml
policy_templates:
  - name: prometheus
    title: Prometheus metrics
    description: Collect metrics from Prometheus instances
    inputs:
      - type: prometheus/metrics
        title: Collect Prometheus metrics
        description: Collecting metrics from Prometheus exporters, Prometheus query API as well as able to receive metrics via remote write functionality.
owner:
  github: elastic/obs-cloudnative-monitoring
