# newer versions go on top
- version: "0.1.0"
  changes:
    - description: Initial release of the Prometheus OpenTelemetry Raw Input package
      type: enhancement
      link: https://github.com/elastic/integrations/pull/17117
