fields:
- name: CveBatchTitle
  cardinality: 100000
- name: CveBatchUrl
  cardinality: 100000
- name: CveId
  enum:
    - CVE10
    - CVE20
    - CVE30
    - CVE40
    - CVE50
- name: CvssScore
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: DeviceId
  cardinality: 100000
- name: DeviceName
  cardinality: 100000
- name: ExploitabilityLevel
  cardinality: 100000
- name: FirstSeenTimestamp
  period: -24h
- name: Id
  cardinality: 100000
- name: IsOnboarded
  cardinality: 100000
- name: LastSeenTimestamp
  period: -24h
- name: OSArchitecture
  cardinality: 100000
- name: OSPlatform
  cardinality: 100000
- name: OSVersion
  cardinality: 100000
- name: RbacGroupId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: RbacGroupName
  cardinality: 100000
- name: RecommendationReference
  cardinality: 100000
- name: RecommendedSecurityUpdate
  cardinality: 100000
- name: RecommendedSecurityUpdateId
  cardinality: 100000
- name: RecommendedSecurityUpdateUrl
  cardinality: 100000
- name: RegistryPaths
  cardinality: 100000
- name: SecurityUpdateAvailable
  cardinality: 100000
- name: SoftwareName
  cardinality: 100000
- name: SoftwareVendor
  cardinality: 100000
- name: SoftwareVersion
  cardinality: 100000
- name: VulnerabilitySeverityLevel
  enum:
    - low
    - high
    - medium
    - critical
    - informational
- name: DiskPaths
  cardinality: 100000
