version: '2.3'
services:
  qnap-nas-udp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9999 -p=udp /sample_logs/*.log
  qnap-nas-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9999 -p=tcp /sample_logs/*.log
  qnap-nas-tls:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9999 -p=tls --insecure /sample_logs/*.log
