rules:
  - path: /api/oauth/token
    query_params:
      grant_type: client_credentials
    methods: ['POST']
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |
          {"access_token":"xxxx","expires_in":3600,"token_type":"Bearer","refresh_token":"yyyy"}
  - path: /api/v1/computers-inventory
    methods: ["GET"]
    query_params:
      filter: "{filter:.*}"
    responses:
      - status_code: 200
        body: |
          {"totalCount":1,"results":[{"id":"3","udid":"5982CE36-4526-580B-B4B9-ECC6782535BA","general":{"name":"acme-C07DM3AZQ6NV","lastReportedIp":"10.122.26.87","lastIpAddress":"10.122.26.87","jamfBinaryVersion":"11.4.1-t1712591696","platform":"Mac","barcode1":"null","remoteManagement":{"managed":true},"supervised":false,"mdmCapable":{"capable":false,"capableUsers":[]},"reportDate":"2024-06-19T15:54:37.692Z","lastContactTime":"2024-04-18T14:26:51.514Z","lastEnrolledDate":"2023-02-22T10:46:17.199Z","initialEntryDate":"2024-06-19","site":{"id":"-1","name":"None"},"itunesStoreAccountActive":false,"enrolledViaAutomatedDeviceEnrollment":false,"userApprovedMdm":false,"declarativeDeviceManagementEnabled":false,"managementId":"1a59c510-b3a9-41cb-8afa-3d4187ac60d0","extensionAttributes":[]},"diskEncryption":null,"localUserAccounts":null,"purchasing":null,"printers":null,"storage":null,"applications":null,"userAndLocation":null,"configurationProfiles":null,"services":null,"plugins":null,"hardware":null,"certificates":null,"attachments":null,"packageReceipts":null,"fonts":null,"security":null,"operatingSystem":null,"licensedSoftware":null,"softwareUpdates":null,"groupMemberships":null,"extensionAttributes":null,"contentCaching":null,"ibeacons":null}]}
  - path: /api/v1/computers-inventory
    methods: ["GET"]
    responses:
      - status_code: 200
        body: |
          {"totalCount":2,"results":[{"id":"3","udid":"5982CE36-4526-580B-B4B9-ECC6782535BC","general":{"name":"acme-C07DM3AZQ6NV","lastReportedIp":"10.122.26.87","lastIpAddress":"10.122.26.87","jamfBinaryVersion":"11.4.1-t1712591696","platform":"Mac","barcode1":"null","remoteManagement":{"managed":true},"supervised":false,"mdmCapable":{"capable":false,"capableUsers":[]},"reportDate":"2024-06-19T15:54:37.692Z","lastContactTime":"2024-04-18T14:26:51.514Z","lastEnrolledDate":"2023-02-22T10:46:17.199Z","initialEntryDate":"2024-06-19","site":{"id":"-1","name":"None"},"itunesStoreAccountActive":false,"enrolledViaAutomatedDeviceEnrollment":false,"userApprovedMdm":false,"declarativeDeviceManagementEnabled":false,"managementId":"1a59c510-b3a9-41cb-8afa-3d4187ac60d0","extensionAttributes":[]},"diskEncryption":null,"localUserAccounts":null,"purchasing":null,"printers":null,"storage":null,"applications":null,"userAndLocation":null,"configurationProfiles":null,"services":null,"plugins":null,"hardware":null,"certificates":null,"attachments":null,"packageReceipts":null,"fonts":null,"security":null,"operatingSystem":null,"licensedSoftware":null,"softwareUpdates":null,"groupMemberships":null,"extensionAttributes":null,"contentCaching":null,"ibeacons":null}]}
