rules:
  - path: /request
    query_params:
      wait: 1
    methods: ['POST']
    request_body: '{"format":"json","prefix":"time-sync-status"}'
    responses:
      - status_code: 200
        body: |-
          { "failed":[],"finished":[{"command":"time-sync-status format=json","outb":"{\"timechecks\":{\"epoch\":7,\"round\":0,\"round_status\":\"finished\"}}","outs":""}],"has_failed":false,"id":"140055401700304","is_finished":true,"is_waiting":false,"running":[],"state":"success","waiting":[]}
  - path: /request
    query_params:
      wait: 1
    methods: ['POST']
    request_body: '{"format":"json","prefix":"osd perf"}'
    responses:
      - status_code: 200
        body: |-
          {"failed":[],"finished":[{"command":"osd perf format=json","outb":"{\"pg_ready\":true,\"osdstats\":{\"osd_perf_infos\":[{\"id\":1,\"perf_stats\":{\"commit_latency_ms\":5.621,\"apply_latency_ms\":3.495,\"commit_latency_ns\":5621000,\"apply_latency_ns\":3495000}},{\"id\":0,\"perf_stats\":{\"commit_latency_ms\":0,\"apply_latency_ms\":0,\"commit_latency_ns\":0,\"apply_latency_ns\":0}}]}\n}","outs":""}],"has_failed":false,"id":"140008221633504","is_finished":true,"is_waiting":false,"running":[],"state":"success","waiting":[]}
  - path: /request
    query_params:
      wait: 1
    methods: ['POST']
    request_body: '{"format":"json","prefix":"osd pool stats"}'
    responses:
      - status_code: 200
        body: |-
          {"failed":[],"finished":[{"command":"osd pool stats format=json","outb":"[{\"pool_name\":\"device_health_metrics\",\"pool_id\":1,\"recovery\":{},\"recovery_rate\":{},\"client_io_rate\":{\"read_bytes_sec\":6622518,\"write_bytes_sec\":6622518,\"read_op_per_sec\":11,\"write_op_per_sec\":11}},{\"pool_name\":\"elastic\",\"pool_id\":9,\"recovery\":{},\"recovery_rate\":{},\"client_io_rate\":{}}]","outs":""}],"has_failed":false,"id":"140222622573952","is_finished":true,"is_waiting":false,"running":[],"state":"success","waiting":[]}
  - path: /request
    query_params:
      wait: 1
    methods: ['POST']
    request_body: '{"format":"json","prefix":"df"}'
    responses:
      - status_code: 200
        body: |-
          {"failed":[],"finished":[{"command":"df format=json","outb":"{\"stats\":{\"total_bytes\":85882568704,\"total_avail_bytes\":81199562752,\"total_used_bytes\":388038656,\"total_used_raw_bytes\":4683005952,\"total_used_raw_ratio\":0.054528012871742249,\"num_osds\":4,\"num_per_pool_osds\":4,\"num_per_pool_omap_osds\":4},\"stats_by_class\":{\"hdd\":{\"total_bytes\":85882568704,\"total_avail_bytes\":81199562752,\"total_used_bytes\":388038656,\"total_used_raw_bytes\":4683005952,\"total_used_raw_ratio\":0.054528012871742249}},\"pools\":[{\"name\":\"device_health_metrics\",\"id\":1,\"stats\":{\"stored\":2142673,\"objects\":4,\"kb_used\":6336,\"bytes_used\":6488064,\"percent_used\":8.4362458437681198e-05,\"max_avail\":25633505280}},{\"name\":\"elk\",\"id\":4,\"stats\":{\"stored\":1176572,\"objects\":3,\"kb_used\":3648,\"bytes_used\":3735552,\"percent_used\":4.8574063839623705e-05,\"max_avail\":25633505280}},{\"name\":\"elastic\",\"id\":9,\"stats\":{\"stored\":1349210,\"objects\":5,\"kb_used\":4224,\"bytes_used\":4325376,\"percent_used\":5.6243221479235217e-05,\"max_avail\":25633505280}}]}\n","outs":""}],"has_failed":false,"id":"140222991325696","is_finished":true,"is_waiting":false,"running":[],"state":"success","waiting":[]}
  - path: /request
    query_params:
      wait: 1
    methods: ['POST']
    request_body: '{"format":"json","prefix":"osd tree"}'
    responses:
      - status_code: 200
        body: |-
          {"failed":[],"finished":[{"command":"osd tree format=json","outb":"{\"nodes\":[{\"id\":0,\"device_class\":\"hdd\",\"name\":\"osd.0\",\"type\":\"osd\",\"type_id\":0,\"crush_weight\":0.0194854736328125,\"depth\":2,\"pool_weights\":{},\"exists\":1,\"status\":\"up\",\"reweight\":1,\"primary_affinity\":1},{\"id\":-7,\"name\":\"node02\",\"type\":\"host\",\"type_id\":1,\"pool_weights\":{},\"children\":[2]},{\"id\":2,\"device_class\":\"hdd\",\"name\":\"osd.2\",\"type\":\"osd\",\"type_id\":0,\"crush_weight\":0.0194854736328125,\"depth\":2,\"pool_weights\":{},\"exists\":1,\"status\":\"up\",\"reweight\":1,\"primary_affinity\":1},{\"id\":-9,\"name\":\"node03\",\"type\":\"host\",\"type_id\":1,\"pool_weights\":{},\"children\":[3]},{\"id\":3,\"device_class\":\"hdd\",\"name\":\"osd.3\",\"type\":\"osd\",\"type_id\":0,\"crush_weight\":0.0194854736328125,\"depth\":2,\"pool_weights\":{},\"exists\":1,\"status\":\"up\",\"reweight\":1,\"primary_affinity\":1},{\"id\":-5,\"name\":\"node04\",\"type\":\"host\",\"type_id\":1,\"pool_weights\":{},\"children\":[1]},{\"id\":1,\"device_class\":\"hdd\",\"name\":\"osd.1\",\"type\":\"osd\",\"type_id\":0,\"crush_weight\":0.0194854736328125,\"depth\":2,\"pool_weights\":{},\"exists\":1,\"status\":\"up\",\"reweight\":1,\"primary_affinity\":1}],\"stray\":[{\"id\":4,\"name\":\"osd.4\",\"type\":\"osd\",\"type_id\":0,\"crush_weight\":0,\"depth\":0,\"exists\":1,\"status\":\"destroyed\",\"reweight\":0,\"primary_affinity\":1},{\"id\":5,\"name\":\"osd.5\",\"type\":\"osd\",\"type_id\":0,\"crush_weight\":0,\"depth\":0,\"exists\":1,\"status\":\"destroyed\",\"reweight\":0,\"primary_affinity\":1}]}\n","outs":""}],"has_failed":false,"id":"140222986406304","is_finished":true,"is_waiting":false,"running":[],"state":"success","waiting":[]}
