version: '3.8'
services:
  microsoft_defender_cloud:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: microsoft_defender_cloud
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
