rules:
  - path: "/v1/feeds/taxii2/api1/collections/3dce855a-c044-5d49-9334-533c24678c5a/objects/"
    methods: ["GET"]
    request_headers:
      Authorization: [ "testing" ]
    responses:
      - status_code: 200
        headers:
          Content-Type: [ "application/taxii+json; charset=utf-8; version=2.1" ]
          X-Taxii-Date-Added-First: [ "2022-02-23T07:34:19.000Z" ]
          X-Taxii-Date-Added-Last: [ "2024-02-23T12:59:14.320Z" ]
          X-Taxii-Date-Modified-First: [ "2024-02-23T13:15:32.276Z" ]
          X-Taxii-Date-Modified-Last: [ "2025-05-17T19:42:44.000Z" ]
        body: |-
          {"type":"bundle","id":"bundle--f29b20bc-bd56-5b25-b409-c5aa76e0be56","spec_version":"2.1","objects":[{"id":"indicator--953b51f0-5707-55c5-bd5a-d7dbddce6f01","created":"2022-02-23T07:34:19.000Z","created_by_ref":"identity--96a9cd9c-2f73-5ad3-a2ab-c14b3eba65c7","labels":["gcleaner","loader","feodo","malware"],"modified":"2025-05-17T19:42:44.000Z","pattern":"[url:value = 'http://appwebstat.biz/stats/1.php']","pattern_type":"stix","revoked":false,"spec_version":"2.1","type":"indicator","valid_from":"2022-02-23T07:34:19.000Z","confidence":100},{"id":"indicator--8b2de5a5-29a2-56a3-9089-94bef2464a7c","created":"2024-02-23T12:59:14.320Z","created_by_ref":"identity--96a9cd9c-2f73-5ad3-a2ab-c14b3eba65c7","external_references":[],"labels":["trickbot"],"modified":"2024-02-23T13:15:32.276Z","pattern":"[ipv4-addr:value = '67.43.156.93']","pattern_type":"stix","revoked":false,"spec_version":"2.1","type":"indicator","valid_from":"2024-02-23T12:59:14.320Z","confidence":90}],"more":false}