version: "2.3"
services:
  maltiverse:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    environment:
      PORT: "8080"
    volumes:
      - ./config.yml:/config.yml
    command:
      - http-server
      - --addr=:8080
      - --config=/config.yml
