version: '3.0'
services:
  elastic_security-cel:
    image: docker.elastic.co/observability/stream:v0.17.1
    hostname: abcsecurity
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
