title: Prometheus collector metrics
release: experimental
type: metrics
streams:
  - input: prometheus/metrics
    vars:
      - name: bearer_token_file
        type: text
        title: Bearer Token File
        multi: false
        required: false
        show_user: true
        default: /var/run/secrets/kubernetes.io/serviceaccount/token
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - localhost:9090
      - name: metrics_filters.exclude
        type: text
        title: Metrics Filters Exclude
        multi: true
        required: false
        show_user: true
        default: []
      - name: metrics_filters.include
        type: text
        title: Metrics Filters Include
        multi: true
        required: false
        show_user: true
        default: []
      - name: metrics_path
        type: text
        title: Metrics Path
        multi: false
        required: false
        show_user: true
        default: /metrics
      - name: password
        type: password
        title: Password
        multi: false
        required: false
        show_user: true
        default: secret
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
      - name: rate_counters
        type: bool
        title: Rate Counters
        multi: false
        required: true
        show_user: true
        default: true
      - name: ssl.certificate_authorities
        type: text
        title: SSL Certificate Authorities
        multi: true
        required: false
        show_user: true
        default:
          - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      - name: use_types
        type: bool
        title: Use Types
        multi: false
        required: true
        show_user: true
        default: true
      - name: username
        type: text
        title: Username
        multi: false
        required: false
        show_user: true
        default: user
    title: Prometheus collector metrics
    description: Collect Prometheus collector metrics
