version: '2.3'
services:
  cloudflare-logpush-gateway-http-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.20.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_WEBHOOK_PROBE=false
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/gateway_http
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/gateway_http.log
  azure-blob-storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000/tcp"
  uploader:
    image: mcr.microsoft.com/azure-cli
    depends_on:
      - azure-blob-storage-emulator
    volumes:
      - ./sample_logs:/sample_logs
    entrypoint: >
      sh -c "
        sleep 5 &&
        export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-blob-storage-emulator:10000/devstoreaccount1;' &&
        az storage container create --name test-container &&
        az storage blob upload --container-name test-container --file /sample_logs/gateway_http.log --name gateway_http.log
      "
  gcs-mock-service:
    image: golang:1.24.7-alpine
    working_dir: /app
    volumes:
      - ./gcs-mock-service:/app
      - ./files/manifest.yml:/files/manifest.yml:ro
      - ./sample_logs/:/data
    ports:
      - "4443/tcp"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:4443/health || exit 1"
      interval: 10s
      timeout: 5s
    command: go run main.go -manifest /files/manifest.yml
