version: '2.3'
services:
  ping-one-audit-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9577/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/audit.log
  ping_one:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: ping_one
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8080'
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config.yml
