version: '2.3'
services:
  trellix_epo_cloud:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: trellix_epo_cloud
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
