version: '2.3'
services:
  cloudflare:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config.yml
  logpull-mock-service:
    image: golang:1.20-alpine
    working_dir: /app
    volumes:
      - ./logpull-mock-service:/app
    ports:
      - "3000:3000"
    command: ["go", "run", "main.go"]
