# newer versions go on top
- version: "0.4.1"
  changes:
    - description: Add missing fields
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/745
- version: "0.1.0"
  changes:
    - description: initial release
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/70
