# newer versions go on top
- version: "1.25.0"
  changes:
    - description: Add `condition` configuration option to container logs data stream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4324
- version: "1.24.0"
  changes:
    - description: Add fields to audit logs data stream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4203
- version: "1.23.1"
  changes:
    - description: Add missing dimension fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4144
- version: "1.23.0"
  changes:
    - description: Add fields to audit logs data stream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4081
- version: "1.22.1"
  changes:
    - description: Fix overlapping fields in state_job data stream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4095
- version: "1.22.0"
  changes:
    - description: Update apiserver and controllermanaged deprecated fields and dashboards
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3825
- version: "1.21.2"
  changes:
    - description: add container ID and pod name as part of Kubernetes Cotainer Logs filestream input
      type: bugfix
      link: https://github.com/elastic/integrations/pull/3672
- version: "1.21.1"
  changes:
    - description: improved the wording of the link to Kubernetes documentation
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3139
- version: "1.21.0"
  changes:
    - description: Add new dashboards
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3115
- version: "1.20.0"
  changes:
    - description: Change fields type for audit_logs data_stream to use `requestObject` and `responseObject` fields of audit events. Disable dynamic mapping for audit_logs data_stream. Drop `kubernetes.audit.responseObject.metadata` and `kubernetes.audit.requestObject.metadata`
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3414
- version: "1.19.1"
  changes:
    - description: Add documentation for volume field
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3029
- version: "1.19.0"
  changes:
    - description: Add missed ecs fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3054
- version: "1.18.1"
  changes:
    - description: Add documentation for multi-fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2916
- version: "1.18.0"
  changes:
    - description: Fix k8s overview dashboard
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2876
- version: "1.17.3"
  changes:
    - description: Remove incorrectly tagged boolean dimension
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2827
- version: "1.17.2"
  changes:
    - description: Add missing metadata fields
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2702
- version: "1.17.1"
  changes:
    - description: Improve default ndjson parser configuration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2694
- version: "1.17.0"
  changes:
    - description: Disable audit logs collection by default
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2675
- version: "1.16.0"
  changes:
    - description: Documentation improvements
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2657
- version: "1.15.0"
  changes:
    - description: Add ssl.certificate_authorities configuration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2613
- version: "1.14.3"
  changes:
    - description: Add missing job.name and cronjob.name fields to state_container datastream
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2625
- version: "1.14.2"
  changes:
    - description: Add missing job.name and cronjob.name fields to container related datastreams
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2612
- version: "1.14.1"
  changes:
    - description: Add missing job.name and cronjob.name fields added by metadata generators
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2608
- version: "1.14.0"
  changes:
    - description: Tune state_metrics settings
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2567
- version: "1.13.0"
  changes:
    - description: Update to ECS 8.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2491
- version: "1.12.0"
  changes:
    - description: Expose add_recourse_metadata configuration option
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2370
- version: "1.11.0"
  changes:
    - description: Add memory.working_set.limit.pct for pod and container data streams
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2469
- version: "1.10.0"
  changes:
    - description: Add leader election in state_job data stream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2377
- version: "1.9.0"
  changes:
    - description: Add missing fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2361
- version: "1.8.1"
  changes:
    - description: Set kubernetes.volume.fs.used.pct to scaled_float
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2288
- version: "1.8.0"
  changes:
    - description: Support json logs parsing
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2345
- version: "1.7.0"
  changes:
    - description: Add new audit logs data stream in kubernetes integration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2317
- version: "1.6.0"
  changes:
    - description: Add skip_older option for event datastream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2342
- version: "1.5.0"
  changes:
    - description: Revert Kubernetes namespace field breaking change
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2209
- version: "1.4.2"
  changes:
    - description: Add dimension fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2076
- version: "1.4.1"
  changes:
    - description: Remove overriding of index pattern on the Kubernetes overview dashboard
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2151
- version: "1.4.0"
  changes:
    - description: Use filestream input for container_logs data stream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2139
- version: "1.3.3"
  changes:
    - description: Fix conditions of data_streams that are based on k8s labels & add condition in pipelines
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2041
- version: "1.3.2"
  changes:
    - description: Set default host for proxy to localhost
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2057
- version: "1.3.1"
  changes:
    - description: Uniform with guidelines
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2057
- version: "1.3.0"
  changes:
    - description: Add container_logs ecs fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2033
- version: "1.2.1"
  changes:
    - description: Update Kubernetes cluster_ip field type
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2031
- version: "1.2.0"
  changes:
    - description: Update Kubernetes namespace field
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1792
- version: "1.1.1"
  changes:
    - description: Update Kubernetes integration Readme
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1890
- version: "1.1.0"
  changes:
    - description: Update to ECS 1.12.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1696
- version: "1.0.0"
  changes:
    - description: Release Kubernetes as GA
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1610
- version: "0.14.1"
  changes:
    - description: Update default host in kubernetes proxy data stream in kubernetes integration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1565
- version: "0.14.0"
  changes:
    - description: Add new container logs data stream in kubernetes integration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1324
- version: "0.13.0"
  changes:
    - description: Leverage dynamic kubernetes provider for controller and scheduler datastream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1324
- version: "0.12.2"
  changes:
    - description: Add missing field "kubernetes.daemonset.name" field for pod and container data streams
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1459
- version: "0.12.1"
  changes:
    - description: Add missing cluster filter for "orchestrator.cluster.name" field in [Metrics Kubernetes] Overview dashboard and Dashboard section in the integration overview page
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1413
- version: "0.12.0"
  changes:
    - description: Update kubernetes package ecs fields with orchestrator.cluster.url and orchestrator.cluster.name
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1407
- version: "0.11.1"
  changes:
    - description: Escape special characters in docs
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1405
- version: "0.11.0"
  changes:
    - description: Update documentation to fit mdx spec
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1401
- version: "0.10.0"
  changes:
    - description: Update integration description
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1364
- version: "0.9.1"
  changes:
    - description: Add missing field "kubernetes.daemonset.name" field for state_pod and state_container
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1335
- version: "0.9.0"
  changes:
    - description: Enhance kubernetes package with state_job data stream
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1018
- version: "0.8.0"
  changes:
    - description: Leverage leader election in kubernetes integration
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1321
- version: "0.7.0"
  changes:
    - description: Add _meta information to Kubernetes fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1289
- version: "0.6.0"
  changes:
    - description: Introduce kubernetes package granularity using input_groups
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1018
- version: "0.5.3"
  changes:
    - description: Add missing field "kubernetes.statefulset.replicas.ready"
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1160
- version: "0.5.2"
  changes:
    - description: Fix stack compatability
      type: bugfix
      link: https://github.com/elastic/integrations/pull/998
- version: "0.5.1"
  changes:
    - description: Fix references to env variables
      type: bugfix
      link: https://github.com/elastic/integrations/pull/970
- version: "0.5.0"
  changes:
    - description: Add missing field "kubernetes.selectors.*" and extra https settings for controllermanager and scheduler datastreams
      type: enhancement
      link: https://github.com/elastic/integrations/pull/886
- version: "0.4.5"
  changes:
    - description: Add missing field "kubernetes.pod.ip"
      type: enhancement
      link: https://github.com/elastic/integrations/pull/919
- version: "0.4.4"
  changes:
    - description: Updating package owner
      type: enhancement
      link: https://github.com/elastic/integrations/pull/766
- version: "0.4.3"
  changes:
    - description: Correct sample event file.
      type: bugfix # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/754
- version: "0.4.2"
  changes:
    - description: Change kibana.version constraint to be more conservative.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/749
- version: "0.4.1"
  changes:
    - description: Add missing fields
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/745
- version: "0.1.0"
  changes:
    - description: initial release
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/70
