- name: prometheus
  type: group
  fields:
    - name: labels.*
      type: object
      object_type: keyword
      description: |
        Prometheus metric labels
    - name: query.*
      type: object
      object_type: double
      object_type_mapping_type: "*"
      description: |
        Prometheus value resulted from PromQL
