- name: kubernetes.cronjob
  type: group
  fields:
    - name: name
      dimension: true
      type: keyword
      description: Cronjob name
    - name: schedule
      dimension: true
      type: keyword
      description: Cronjob schedule
    - name: concurrency
      dimension: true
      type: keyword
      description: Concurrency policy
    - name: active.count
      type: long
      metric_type: gauge
      description: Number of active pods for the cronjob
    - name: is_suspended
      type: boolean
      description: Whether the cronjob is suspended
    - name: created.sec
      type: double
      unit: s
      metric_type: gauge
      description: Epoch seconds since the cronjob was created
    - name: last_schedule.sec
      type: double
      unit: s
      metric_type: gauge
      description: Epoch seconds for last cronjob run
    - name: next_schedule.sec
      type: double
      unit: s
      metric_type: gauge
      description: Epoch seconds for next cronjob run
    - name: deadline.sec
      type: long
      unit: s
      metric_type: gauge
      description: Deadline seconds after schedule for considering failed
