- name: '@odata.type'
  cardinality: 100000
- name: id
  cardinality: 100000
- name: incidentWebUrl
  cardinality: 100000
- name: redirectIncidentId
  cardinality: 100000
- name: tenantId
  cardinality: 100000
- name: displayName
  cardinality: 100000
- name: createdDateTime
  period: -24h
- name: lastUpdateDateTime
  period: -24h
- name: assignedTo
  cardinality: 100000
- name: classification
  cardinality: 100000
- name: determination
  cardinality: 100000
- name: status
  enum:
    - active
    - new
    - resolved
- name: severity
  enum:
    - low
    - high
    - medium
    - critical
    - informational
- name: tags
  cardinality: 100000
- name: comments
  cardinality: 100000
- name: alerts.@odata.type
  cardinality: 100000
- name: alerts.id
  cardinality: 100000
- name: alerts.providerAlertId
  cardinality: 100000
- name: alerts.incidentId
  cardinality: 100000
- name: alerts.status
  enum:
    - active
    - new
    - resolved
- name: alerts.severity
  enum:
    - low
    - high
    - medium
    - critical
    - informational
- name: alerts.classification
  cardinality: 100000
- name: alerts.determination
  cardinality: 100000
- name: alerts.serviceSource
  cardinality: 100000
- name: alerts.detectionSource
  cardinality: 100000
- name: alerts.detectorId
  cardinality: 100000
- name: alerts.tenantId
  cardinality: 100000
- name: alerts.title
  cardinality: 100000
- name: alerts.description
  cardinality: 100000
- name: alerts.recommendedActions
  cardinality: 100000
- name: alerts.category
  cardinality: 100000
- name: alerts.assignedTo
  cardinality: 100000
- name: alerts.alertWebUrl
  cardinality: 100000
- name: alerts.incidentWebUrl
  cardinality: 100000
- name: alerts.actorDisplayName
  cardinality: 100000
- name: alerts.threatDisplayName
  cardinality: 100000
- name: alerts.threatFamilyName
  cardinality: 100000
- name: alerts.mitreTechniques
  cardinality: 100000
- name: alerts.createdDateTime
  period: -24h
- name: alerts.lastUpdateDateTime
  period: -24h
- name: alerts.resolvedDateTime
  period: -24h
- name: alerts.firstActivityDateTime
  period: -24h
- name: alerts.lastActivityDateTime
  period: -24h
- name: alerts.comments
  cardinality: 100000
- name: alerts.evidence.@odata.type
  cardinality: 100000
- name: alerts.evidence.appId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: alerts.evidence.createdDateTime
  period: -24h
- name: alerts.evidence.displayName
  cardinality: 100000
- name: alerts.evidence.instanceId
  cardinality: 100000
- name: alerts.evidence.instanceName
  cardinality: 100000
- name: alerts.evidence.remediationStatus
  cardinality: 100000
- name: alerts.evidence.remediationStatusDetails
  cardinality: 100000
- name: alerts.evidence.roles
  cardinality: 100000
- name: alerts.evidence.saasAppId
  cardinality: 100000
- name: alerts.evidence.tags
  cardinality: 100000
- name: alerts.evidence.verdict
  cardinality: 100000
- name: customTags
  cardinality: 100000
