version: '2.3'
services:
  citrix_adc:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: citrix_adc
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config.yml
  citrix-adc-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  citrix-adc-tls:
    image: docker.elastic.co/observability/stream:v0.8.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9561 -p=tls --insecure /sample_logs/citrix-adc.log
  citrix-adc-tcp:
    image: docker.elastic.co/observability/stream:v0.8.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9560 -p=tcp /sample_logs/citrix-adc.log
  citrix-adc-udp:
    image: docker.elastic.co/observability/stream:v0.8.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9560 -p=udp /sample_logs/citrix-adc.log
