- version: "2.2.0"
  changes:
    - description: Add processor support for Traefik health.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/10411
- version: "2.1.0"
  changes:
    - description: Add global filter on data_stream.dataset to improve performance.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9995
- version: "2.0.0"
  changes:
    - description: Support traefik v2.x access-logs.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9131
- version: "1.11.1"
  changes:
    - description: Inline "by reference" visualizations.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/8423
- version: 1.11.0
  changes:
    - description: Update the package format_version to 3.0.0.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/8203
- version: "1.10.0"
  changes:
    - description: Enable time series data streams for the metrics datasets. This dramatically reduces storage for metrics and is expected to progressively improve query performance. For more details, see https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7781
- version: "1.9.1"
  changes:
    - description: Add metric_type mapping for `health` datastream.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7768
- version: "1.9.0"
  changes:
    - description: Add dimension mapping for `health` datastream.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/7767
- version: "1.8.1"
  changes:
    - description: Add null check and ignore_missing check to the rename processor.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/7845
- version: "1.8.0"
  changes:
    - description: Rename ownership from obs-service-integrations to obs-infraobs-integrations.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6298
- version: "1.7.0"
  changes:
    - description: Migrate visualizations to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5693
- version: "1.6.1"
  changes:
    - description: Added categories and/or subcategories.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5123
- version: "1.6.0"
  changes:
    - description: Update ECS version to 8.5.1.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4485
- version: "1.5.0"
  changes:
    - description: Added infrastructure category.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/4485
- version: "1.4.2"
  changes:
    - description: Fix the if condition on the community_id processor in the ingest pipeline.
      type: bugfix
      link: https://github.com/elastic/integrations/issues/4074
- version: "1.4.1"
  changes:
    - description: Remove unused visualizations.
      type: enhancement
      link: https://github.com/elastic/integrations/issues/3975
- version: "1.4.0"
  changes:
    - description: Migrate tile map to map in logs dashboard.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/3450
- version: "1.3.1"
  changes:
    - description: Add documentation for multi-fields.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2916
- version: "1.3.0"
  changes:
    - description: Update to ECS 8.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2513
- version: "1.2.2"
  changes:
    - description: Regenerate test files using the new GeoIP database.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2339
- version: "1.2.1"
  changes:
    - description: Change test public IPs to the supported subset.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/2327
- version: "1.2.0"
  changes:
    - description: Release traefik package for v8.0.0.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2186
- version: "1.1.2"
  changes:
    - description: Uniform with guidelines.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/2047
- version: "1.1.1"
  changes:
    - description: Fix logic that checks for the 'forwarded' tag.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1857
- version: "1.1.0"
  changes:
    - description: Update to ECS 1.12.0.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1710
- version: "1.0.0"
  changes:
    - description: Release Traefik as GA.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1621
- version: "0.4.3"
  changes:
    - description: Convert to generated ECS fields.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1510
- version: '0.4.2'
  changes:
    - description: update to ECS 1.11.0.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1423
- version: "0.4.1"
  changes:
    - description: Escape special characters in docs.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1405
- version: "0.4.0"
  changes:
    - description: Update integration description.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1364
- version: "0.3.0"
  changes:
    - description: Set "event.module" and "event.dataset".
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1247
- version: "0.2.0"
  changes:
    - description: update to ECS 1.10.0 and adding event.original options.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1107
- version: "0.1.2"
  changes:
    - description: setting minimum Kibana version required to 7.13.0.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1003
- version: "0.1.1"
  changes:
    - description: parse either commonlog- or json-formatted logs.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/770
    - description: update to ECS 1.9.0.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/876
- version: "0.1.0"
  changes:
    - description: initial release.
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/763
