# newer versions go on top
- version: "0.4.3"
  changes:
    - description: Convert to generated ECS fields
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1510
- version: '0.4.2'
  changes:
    - description: update to ECS 1.11.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1423
- version: "0.4.1"
  changes:
    - description: Escape special characters in docs
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1405
- version: "0.4.0"
  changes:
    - description: Update integration description
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1364
- version: "0.3.0"
  changes:
    - description: Set "event.module" and "event.dataset"
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1247
- version: "0.2.0"
  changes:
    - description: update to ECS 1.10.0 and adding event.original options
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1107
- version: "0.1.2"
  changes:
    - description: setting minimum Kibana version required to 7.13.0
      type: bugfix
      link: https://github.com/elastic/integrations/pull/1003
- version: "0.1.1"
  changes:
    - description: parse either commonlog- or json-formatted logs
      type: enhancement
      link: https://github.com/elastic/integrations/pull/770
    - description: update to ECS 1.9.0
      type: enhancement
      link: https://github.com/elastic/integrations/pull/876
- version: "0.1.0"
  changes:
    - description: initial release
      type: enhancement # can be one of: enhancement, bugfix, breaking-change
      link: https://github.com/elastic/integrations/pull/763
