name: traefik
title: Traefik
version: "2.2.0"
description: Collect logs from Traefik servers with Elastic Agent.
type: integration
icons:
  - src: /img/traefik.svg
    title: traefik
    size: 259x296
    type: image/svg+xml
format_version: "3.0.0"
categories:
  - observability
conditions:
  kibana:
    version: "^8.9.0"
  elastic:
    subscription: basic
screenshots:
  - src: /img/kibana-traefik.png
    title: kibana traefik
    size: 1409x1254
    type: image/png
policy_templates:
  - name: traefik
    title: Traefik logs
    description: Collect logs from Traefik instances
    inputs:
      - type: logfile
        title: "Collect Traefik access logs"
        description: "Collecting access logs from Traefik instances"
owner:
  github: elastic/obs-infraobs-integrations
  type: elastic
