rules:
  - path: /v1/feed/nod/
    methods: [GET]
    responses:
      - status_code: 200
        body: |-
          {"timestamp":"2025-01-11T08:42:46Z","domain":"test1.com"}
          {"timestamp":"2025-01-11T08:42:46Z","domain":"test2.com"}
