version: '3.0'
services:
  splunk:
    image: docker.elastic.co/observability/stream:v0.18.0
    hostname: splunk
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
