title: Kubernetes Proxy metrics
release: experimental
type: metrics
streams:
  - input: kubernetes/metrics
    vars:
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - ${env.NODE_NAME}:10249
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
    title: Kubernetes Proxy metrics
    description: Collect Kubernetes Proxy metrics
