rules:
  - path: /api/v1/itemusages
    methods: ["POST"]
    request_headers:
      Content-Type:
        - "application/json"
      Authorization:
        - "Bearer --token--"
    request_body: '{"limit":1000}'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json; charset=utf-8"
        body: |-
          {"cursor":"cursor_0","has_more":true,"items":[{"uuid":"MCQODBBWJD5HISKYNP3HJPV2DV","timestamp":"2021-08-30T18:57:42.484Z","used_version":1,"vault_uuid":"jaqxqf5qylslqiitnduawrndc5","item_uuid":"bvwmmwxisuca7wbehrbyqhag54","user":{"uuid":"OJQGU46KAPROEJLCK674RHSAY5","name":"Name","email":"email@1password.com"},"client":{"app_name":"1Password Browser Extension","app_version":"1109","platform_name":"Chrome","platform_version":"93.0.4577.62","os_name":"Android","os_version":"10","ip_address":"1.1.1.1"}}]}
  - path: /api/v1/itemusages
    methods: ["POST"]
    request_headers:
      Content-Type:
        - "application/json"
      Authorization:
        - "Bearer --token--"
    request_body: '{"cursor":"cursor_0"}'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json; charset=utf-8"
        body: |-
          {"cursor":"cursor_1","has_more":false,"items":[{"uuid":"5HBWJDWCQADISKY2DVBNP3HJPV","timestamp":"2021-08-30T19:10:00.123Z","used_version":1,"vault_uuid":"jaqxqf5qylslqiitnduawrndc5","item_uuid":"bvwmmwxisuca7wbehrbyqhag54","user":{"uuid":"OJQGU46KAPROEJLCK674RHSAY5","name":"Name","email":"email@1password.com"},"client":{"app_name":"1Password Browser Extension","app_version":"1109","platform_name":"Chrome","platform_version":"93.0.4577.62","os_name":"Android","os_version":"10","ip_address":"1.1.1.1"}}]}
  - path: /api/v1/itemusages
    methods: ["POST"]
    request_headers:
      Content-Type:
        - "application/json"
      Authorization:
        - "Bearer --token--"
    request_body: '{"cursor":"cursor_1"}'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json; charset=utf-8"
        body: |-
          {"cursor":"cursor_1","has_more":false,"items":[]}
  - path: /api/v1/signinattempts
    methods: ["POST"]
    request_headers:
      Content-Type:
        - "application/json"
      Authorization:
        - "Bearer --token--"
    request_body: '{"limit":1000}'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json; charset=utf-8"
        body: |-
          {"cursor":"cursor_0","has_more":true,"items":[{"uuid":"HGIF4OEWXDTVWKEQDIWTKV26HU","session_uuid":"UED4KFZ5BH37IQWTJ7LG4VPWK7","timestamp":"2021-08-11T14:28:03Z","country":"AR","category":"success","type":"credentials_ok","details":null,"target_user":{"uuid":"OJQGU46KAPROEJLCK674RHSAY5","name":"Name","email":"email@1password.com"},"client":{"app_name":"1Password Browser Extension","app_version":"1109","platform_name":"Chrome","platform_version":"93.0.4577.62","os_name":"Android","os_version":"10","ip_address":"1.1.1.1"}}]}
  - path: /api/v1/signinattempts
    methods: ["POST"]
    request_headers:
      Content-Type:
        - "application/json"
      Authorization:
        - "Bearer --token--"
    request_body: '{"cursor":"cursor_0"}'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json; charset=utf-8"
        body: |-
          {"cursor":"cursor_1","has_more":true,"items":[{"uuid":"QVWKEOEWXU2DIDHWTK6HGIF4TV","session_uuid":"UED4KFZ5BH37IQWTJ7LG4VPWK7","timestamp":"2021-08-11T15:04:22Z","country":"AR","category":"success","type":"credentials_ok","details":null,"target_user":{"uuid":"OJQGU46KAPROEJLCK674RHSAY5","name":"Name","email":"email@1password.com"},"client":{"app_name":"1Password Browser Extension","app_version":"1109","platform_name":"Chrome","platform_version":"93.0.4577.62","os_name":"Android","os_version":"10","ip_address":"1.1.1.1"}}]}
  - path: /api/v1/signinattempts
    methods: ["POST"]
    request_headers:
      Content-Type:
        - "application/json"
      Authorization:
        - "Bearer --token--"
    request_body: '{"cursor":"cursor_1"}'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json; charset=utf-8"
        body: |-
          {"cursor":"cursor_1","has_more":false,"items":[]}
