- name: data_stream.type
  external: ecs
- name: data_stream.dataset
  external: ecs
- name: data_stream.namespace
  external: ecs
- name: '@timestamp'
  external: ecs
- name: kubernetes
  type: group
  fields:
    - name: pod.name
      dimension: true
      type: keyword
      description: >
        Kubernetes pod name

    - name: pod.uid
      type: keyword
      description: >
        Kubernetes pod UID

    - name: pod.ip
      type: ip
      description: >
        Kubernetes pod IP

    - name: namespace
      dimension: true
      type: keyword
      description: >
        Kubernetes namespace

    - name: node.name
      type: keyword
      description: >
        Kubernetes node name

    - name: node.hostname
      type: keyword
      description: >
        Kubernetes hostname as reported by the nodeâ€™s kernel

    - name: labels.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes labels map

    - name: annotations.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes annotations map

    - name: selectors.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes Service selectors map

    - name: replicaset.name
      type: keyword
      description: >
        Kubernetes replicaset name

    - name: deployment.name
      type: keyword
      description: >
        Kubernetes deployment name

    - name: statefulset.name
      type: keyword
      description: >
        Kubernetes statefulset name

    - name: container.name
      type: keyword
      description: >
        Kubernetes container name

    - name: container.image
      type: keyword
      description: >-
        Kubernetes container image
