- name: kubernetes.volume
  type: group
  fields:
    - name: name
      dimension: true
      type: keyword
      description: |
        Volume name
    - name: fs
      type: group
      fields:
        - name: capacity
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Filesystem total capacity in bytes
        - name: available
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Filesystem total available in bytes
        - name: used
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Filesystem total used in bytes
            - name: pct
              type: scaled_float
              format: percent
              unit: percent
              metric_type: gauge
              description: |
                Percentage of filesystem total used
        - name: inodes
          type: group
          fields:
            - name: used
              type: long
              metric_type: gauge
              description: |
                Used inodes
            - name: pct
              type: scaled_float
              format: percent
              unit: percent
              metric_type: gauge
              description: |
                Percentage of used inodes
            - name: free
              type: long
              metric_type: gauge
              description: |
                Free inodes
            - name: count
              type: long
              metric_type: gauge
              description: |
                Total inodes
