rules:
  - path: /connect/token
    methods: ['POST']
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |
          {"access_token":"xxxx","expires_in":3600,"token_type":"Bearer"}
  - path: /public/collections
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    responses:
      - status_code: 200
        body: >
          {"object":"list","data":[{"externalId":"external_id_123456","object":"collection","id":"539a36c5-e0d2-4cf9-979e-51ecf5cf6593","groups":null}]}

  - path: /public/events
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    responses:
      - status_code: 200
        body: >
          {"object":"list","data":[{"object":"event","type":1000,"itemId":"3767a302-8208-4dc6-b842-030428a1cfad","collectionId":"bce212a4-25f3-4888-8a0a-4c5736d851e0","groupId":"f29a2515-91d2-4452-b49b-5e8040e6b0f4","policyId":"f29a2515-91d2-4452-b49b-5e8040e6b0f4","memberId":"e68b8629-85eb-4929-92c0-b84464976ba4","actingUserId":"a2549f79-a71f-4eb9-9234-eb7247333f94","date":"2023-02-22T09:00:21.728Z","device":0,"ipAddress":"172.16.254.1"}]}

  - path: /public/groups
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    responses:
      - status_code: 200
        body: >
          {"object":"list","data":[{"name":"Development Team","accessAll":true,"externalId":"external_id_123456","object":"group","id":"539a36c5-e0d2-4cf9-979e-51ecf5cf6593","collections":[{"id":"bfbc8338-e329-4dc0-b0c9-317c2ebf1a09","readOnly":true}]}]}

  - path: /public/policies
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    responses:
      - status_code: 200
        body: >
          {"object":"list","data":[{"enabled":true,"data":{"defaultType":"password","minLength":5,"useUpper":true,"useLower":true,"useNumbers":true,"useSpecial":true,"minNumbers":1,"minSpecial":1,"minNumberWords":3,"capitalize":true,"includeNumber":true},"object":"policy","id":"539a36c5-e0d2-4cf9-979e-51ecf5cf6593","type":0}]}

  - path: /public/members
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    responses:
      - status_code: 200
        body: >
          {"object":"list","data":[{"type":0,"accessAll":true,"externalId":"external_id_123456","resetPasswordEnrolled":true,"object":"member","id":"1234","userId":"48b47ee1-493e-4c67-aef7-014996c40eca","name":"John Smith","email":"jsmith@example.com","twoFactorEnabled":true,"status":0,"collections":null}]}

  - path: /public/members/1234
    methods: ['GET']
    request_headers:
    responses:
      - status_code: 200
        body: >
          {"type":0,"accessAll":true,"externalId":"external_id_123456","resetPasswordEnrolled":true,"object":"member","id":"539a36c5-e0d2-4cf9-979e-51ecf5cf6593","userId":"48b47ee1-493e-4c67-aef7-014996c40eca","name":"John Smith","email":"jsmith@example.com","twoFactorEnabled":true,"status":0,"collections":[{"id":"bfbc8338-e329-4dc0-b0c9-317c2ebf1a09","readOnly":true}]}

