version: '2.3'
services:
  nextron_thor:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: nextron_thor
    ports:
      - 443
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '443'
    command:
      - http-server
      - --addr=:443
      - --config=/files/config.yml
