rules:
  - path: /alert-management/v1/notifications
    methods: ['GET']
    query_params:
      size: "2"
      created_after: "{created_after:.*}"
      cursor: "1766048799.045972"
    request_headers:
      Authorization: "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {
            "items": [
              {
                "id": "392014d7-88ed-4f76-8410-305d38d3a1bc",
                "resource": {
                  "id": "VDUKzAG2WOWkGefHoe4TFA",
                  "basetypes": [
                    "article",
                    "news",
                    "newscatcher"
                  ],
                  "author": "up18news",
                  "authors": [
                    "up18news"
                  ],
                  "country": "IN",
                  "description": "Up18 News Wittypen Launches Zerply.ai and Wins Silver at MarTechAI Awards Business News",
                  "created_at": {
                    "date-time": "2025-12-17T06:46:29+00:00",
                    "raw": "2025-12-17 06:46:29",
                    "timestamp": 1765953989
                  },
                  "link": "https://example.com",
                  "site": {
                    "title": "example.com"
                  },
                  "sort_date": "2025-12-17T06:46:33Z",
                  "title": "Wittypen Launches Zerply.ai and Wins Silver at MarTechAI Awards"
                },
                "reason": {
                  "id": "0f325ca9-a28f-421b-8d0c-db3329366e5f",
                  "name": "credit",
                  "text": "credit",
                  "origin": "searches",
                  "details": {
                    "sources": [
                      "communities",
                      "media",
                      "marketplaces",
                      "news"
                    ],
                    "params": {
                      "exclude": {},
                      "include": {
                        "date": {
                          "end": "now",
                          "label": "Last 30 Days",
                          "start": "now-30d"
                        }
                      }
                    }
                  },
                  "entity": null
                },
                "status": null,
                "generated_at": "2025-12-17T06:54:21.863351Z",
                "created_at": "2025-12-17T06:54:26.163659Z",
                "tags": {},
                "highlights": {
                  "body.text/plain": [
                    "No <mark>credit</mark> card"
                  ]
                },
                "highlight_text": "No <mark>credit</mark> card is require",
                "data_type": "news",
                "parent_data_type": null,
                "source": "news",
                "is_read": false
              },
              {
                "id": "fab83d8c-3fc3-4267-ad71-1df7be82b7bf",
                "resource": {
                  "id": "TIaevTSpXQGxKlMDuh9RHw",
                  "basetypes": [
                    "chat",
                    "conversation",
                    "message",
                    "telegram"
                  ],
                  "container": {
                    "name": "My Tricky Deals | Official",
                    "native_id": "1117587920",
                    "title": "My Tricky Deals | Official"
                  },
                  "created_at": {
                    "date-time": "2025-12-17T06:53:09+00:00",
                    "raw": "1765954389",
                    "timestamp": 1765954389
                  },
                  "site": {
                    "title": "Telegram"
                  },
                  "site_actor": {
                    "names": {
                      "handle": "My Tricky Deals | Official"
                    },
                    "native_id": "1117587920"
                  },
                  "sort_date": "2025-12-17T06:53:09Z",
                  "title": "My Tricky Deals | Official"
                },
                "reason": {
                  "id": "0f325ca9-a28f-421b-8d0c-db3329366e5f",
                  "name": "credit",
                  "text": "credit",
                  "origin": "searches",
                  "details": {
                    "sources": [
                      "communities",
                      "media",
                      "marketplaces",
                      "news"
                    ],
                    "params": {
                      "exclude": {},
                      "include": {
                        "date": {
                          "end": "now",
                          "label": "Last 30 Days",
                          "start": "now-30d"
                        }
                      }
                    }
                  },
                  "entity": null
                },
                "status": null,
                "generated_at": "2025-12-17T06:54:14.756666Z",
                "created_at": "2025-12-17T06:54:15.576748Z",
                "tags": {},
                "highlights": {
                  "body.text/plain": [
                    "Pureit Eco Water Save"
                  ]
                },
                "highlight_text": "Pureit Eco Water Saver R",
                "data_type": "chat",
                "parent_data_type": null,
                "source": "communities",
                "is_read": false
              }
            ],
            "pagination": {
              "next": null,
              "prev": null,
              "total": null
            }
          }
  - path: /alert-management/v1/notifications
    methods: ['GET']
    query_params:
      size: "2"
      created_after: "{created_after:.*}"
      cursor: "1766048799.045962"
    request_headers:
      Authorization: "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {
            "items": [
              {
                "id": "04d5f5ca-4c7f-40b2-b2f1-91a08acc2a0b",
                "resource": {
                  "id": "BQoWAAO5X0uRdZgRAFUJMg",
                  "basetypes": [
                    "article",
                    "comment",
                    "conversation",
                    "message",
                    "reddit",
                    "web"
                  ],
                  "container": {
                    "container": {
                      "name": "walmart_RX",
                      "native_id": "walmart_RX"
                    },
                    "native_id": "1pklksl",
                    "title": "Why do patients get so upset when they have to go to the counseling window???"
                  },
                  "created_at": {
                    "date-time": "2025-12-17T04:08:07+00:00",
                    "raw": "2025-12-17 04:08:07+00:00",
                    "timestamp": 1765944487
                  },
                  "site": {
                    "title": "Reddit"
                  },
                  "site_actor": {
                    "names": {
                      "handle": "Jitae_Slay"
                    },
                    "native_id": "Jitae_Slay"
                  },
                  "section": "walmart_RX",
                  "sort_date": "2025-12-17T04:08:07Z",
                  "title": "Why do patients get so upset when they have to go to the counseling window???"
                },
                "reason": {
                  "id": "0f325ca9-a28f-421b-8d0c-db3329366e5f",
                  "name": "credit",
                  "text": "credit",
                  "origin": "searches",
                  "details": {
                    "sources": [
                      "communities",
                      "media",
                      "marketplaces",
                      "news"
                    ],
                    "params": {
                      "exclude": {},
                      "include": {
                        "date": {
                          "end": "now",
                          "label": "Last 30 Days",
                          "start": "now-30d"
                        }
                      }
                    }
                  },
                  "entity": null
                },
                "status": null,
                "generated_at": "2025-12-17T06:54:12.513737Z",
                "created_at": "2025-12-17T06:54:13.809007Z",
                "tags": {},
                "highlights": {
                  "body.text/plain": [
                    "You developed by pharmacists."
                  ]
                },
                "highlight_text": "You developed by pharmacists.",
                "data_type": "reddit",
                "parent_data_type": null,
                "source": "communities",
                "is_read": false
              },
              {
                "id": "d361ebdf-29e9-4063-8168-ede87124704b",
                "resource": {
                  "id": "m-xxur1VXm6W7hN0IU0rHA",
                  "basetypes": [
                    "chat",
                    "conversation",
                    "message",
                    "telegram"
                  ],
                  "container": {
                    "name": "BinX Chat",
                    "native_id": "2783168214",
                    "title": "BinX Chat"
                  },
                  "created_at": {
                    "date-time": "2025-12-17T06:53:40+00:00",
                    "raw": "1765954420",
                    "timestamp": 1765954420
                  },
                  "site": {
                    "title": "Telegram"
                  },
                  "site_actor": {
                    "names": {
                      "handle": "BinX Bot"
                    },
                    "native_id": "7329244255"
                  },
                  "sort_date": "2025-12-17T06:53:40Z",
                  "title": "BinX Chat"
                },
                "reason": {
                  "id": "0f325ca9-a28f-421b-8d0c-db3329366e5f",
                  "name": "credit",
                  "text": "credit",
                  "origin": "searches",
                  "details": {
                    "sources": [
                      "communities",
                      "media",
                      "marketplaces",
                      "news"
                    ],
                    "params": {
                      "exclude": {},
                      "include": {
                        "date": {
                          "end": "now",
                          "label": "Last 30 Days",
                          "start": "now-30d"
                        }
                      }
                    }
                  },
                  "entity": null
                },
                "status": null,
                "generated_at": "2025-12-17T06:54:05.410755Z",
                "created_at": "2025-12-17T06:54:08.483601Z",
                "tags": {},
                "highlights": {
                  "body.text/plain": [
                    "BinX Bin Lookup "
                  ]
                },
                "highlight_text": "BinX Bin Lookup",
                "data_type": "chat",
                "parent_data_type": null,
                "source": "communities",
                "is_read": false
              }
            ],
            "pagination": {
              "next": "http://{{ hostname }}:{{ env "PORT" }}/alert-management/v1/notifications?created_after=2025-12-02T00%3A00%3A00Z&cursor=1766048799.045972&size=2",
              "prev": null,
              "total": null
            }
          }
  - path: /alert-management/v1/notifications
    methods: ['GET']
    query_params:
      size: "2"
      created_after: "{created_after:.*}"
    request_headers:
      Authorization: "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {
            "items": [
              {
                "id": "e2af074a-970e-48a1-b34d-e63b573b8c2c",
                "resource": {
                  "id": "zjtsfLGBWhGEWmNDICmOUQ",
                  "basetypes": [
                    "chat",
                    "conversation",
                    "message",
                    "telegram"
                  ],
                  "container": {
                    "name": "Warnisx Scrapper",
                    "native_id": "3092489782",
                    "title": "Warnisx Scrapper"
                  },
                  "created_at": {
                    "date-time": "2025-12-17T06:53:13+00:00",
                    "raw": "1765954393",
                    "timestamp": 1765954393
                  },
                  "site": {
                    "title": "Telegram"
                  },
                  "site_actor": {
                    "names": {
                      "handle": "Warnisx Scrapper"
                    },
                    "native_id": "3092489782"
                  },
                  "sort_date": "2025-12-17T06:53:13Z",
                  "title": "Warnisx Scrapper"
                },
                "reason": {
                  "id": "0f325ca9-a28f-421b-8d0c-db3329366e5f",
                  "name": "credit",
                  "text": "credit",
                  "origin": "searches",
                  "details": {
                    "sources": [
                      "communities",
                      "media",
                      "marketplaces",
                      "news"
                    ],
                    "params": {
                      "exclude": {},
                      "include": {
                        "date": {
                          "end": "now",
                          "label": "Last 30 Days",
                          "start": "now-30d"
                        }
                      }
                    }
                  },
                  "entity": null
                },
                "status": null,
                "generated_at": "2025-12-17T06:54:02.025006Z",
                "created_at": "2025-12-17T06:54:06.495138Z",
                "tags": {},
                "highlights": {
                  "body.text/plain": [
                    "temp"
                  ]
                },
                "highlight_text": "temp",
                "data_type": "chat",
                "parent_data_type": null,
                "source": "communities",
                "is_read": false
              },
              {
                "id": "1fc0fc04-5a85-41ff-970d-acda1c0dd390",
                "resource": {
                  "id": "c4FF4mbNV7m2vBWPIaV0uw",
                  "basetypes": [
                    "article",
                    "news",
                    "newscatcher"
                  ],
                  "author": "Alias Doe",
                  "authors": [
                    "Alias Doe"
                  ],
                  "country": "IN",
                  "description": "Rajinikanth, who has ruled both South and Bollywood cinema, turns 75 today. Born on December 12, 1950, the superstar continues to deliver box-office blockbusters and is now gearing up for several exciting upcoming films.",
                  "created_at": {
                    "date-time": "2025-12-12T09:06:06+00:00",
                    "raw": "2025-12-12 09:06:06",
                    "timestamp": 1765530366
                  },
                  "link": "https://example.com",
                  "site": {
                    "title": "example.com"
                  },
                  "media_v2": [
                    {
                      "sha1": "ddc7b1f8b32056803bdce609c1262e59836bec87",
                      "phash": "9a996984a473e3c7",
                      "phash256": "9abe917a69c984a6a4d47368e34cc526ed85658cc913cdb3986b9b4cd31c3673",
                      "mime_type": "image/jpeg",
                      "storage_uri": "gs://kraken-datalake-media/artifacts/71/71a2a7e557b989f25b89a7cbd9ec3a65183a4717bc2a05ede89971064f177b58"
                    }
                  ],
                  "container": {
                    "name": "newbies-2",
                    "native_id": "966491148640211034"
                  },
                  "sort_date": "2025-12-12T09:06:06Z",
                  "title": "Jailer 2 to Coolie 2: Rajinikanth at 75 Ready to Thrill Fans with Upcoming Hits"
                },
                "reason": {
                  "id": "0f325ca9-a28f-421b-8d0c-db3329366e5f",
                  "name": "credit",
                  "text": "credit",
                  "origin": "searches",
                  "details": {
                    "sources": [
                      "communities",
                      "media",
                      "marketplaces",
                      "news"
                    ],
                    "params": {
                      "exclude": {},
                      "include": {
                        "date": {
                          "end": "now",
                          "label": "Last 30 Days",
                          "start": "now-30d"
                        }
                      }
                    }
                  },
                  "entity": null
                },
                "status": null,
                "generated_at": "2025-12-12T11:41:35.896396Z",
                "created_at": "2025-12-12T11:41:37.775301Z",
                "tags": {},
                "highlights": {
                  "body.text/plain": [
                    "16\nImage <mark>Credit</mark>."
                  ]
                },
                "highlight_text": "16\nImage <mark>Credit</mark> :",
                "data_type": "news",
                "parent_data_type": null,
                "source": "news",
                "is_read": false
              }
            ],
            "pagination": {
              "next": "http://{{ hostname }}:{{ env "PORT" }}/alert-management/v1/notifications?created_after=2025-12-02T00%3A00%3A00Z&cursor=1766048799.045962&size=2",
              "prev": null,
              "total": null
            }
          }
