rules:
  - path: /technical-intelligence/v2/indicators
    methods: ['GET']
    query_params:
      size: "2"
      modified_after: "{modified_after:.*}"
      from: "2"
    request_headers:
      Authorization: "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {
            "items": [
              {
                "id": "5YFE1T4tW--r8H4ARmgDfQ",
                "type": "domain",
                "value": "ns8.softline.top",
                "href": "https://api.flashpoint.io/technical-intelligence/v2/indicators/5YFE1T4tW--r8H4ARmgDfQ",
                "entity_type": "indicator",
                "score": {
                  "value": "malicious",
                  "last_scored_at": "2025-07-30T07:26:25.981000Z"
                },
                "modified_at": "2025-12-23T11:18:12.238000Z",
                "created_at": "2024-01-01T00:00:00Z",
                "last_seen_at": "2025-12-23T11:12:06.372000Z",
                "sort_date": "2025-12-23T11:12:06.372000Z",
                "platform_urls": {
                  "ignite": "https://app.flashpoint.io/cti/malware/iocs/5YFE1T4tW--r8H4ARmgDfQ"
                },
                "sightings": [
                  {
                    "id": "BqIOrT8HWaib7Cc-hOcoAA",
                    "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                    "source": "flashpoint_extraction",
                    "sighted_at": "2025-12-23T10:41:44.231000Z",
                    "tags": [
                      "beacontype:hybrid http dns",
                      "extracted_config:true",
                      "httpposturi:/n4215/adj/amzn.us.sr.aps",
                      "malware:cobaltstrike",
                      "source:flashpoint_extraction",
                      "type:backdoor"
                    ],
                    "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                  }
                ],
                "latest_sighting": {
                  "id": "BqIOrT8HWaib7Cc-hOcoAA",
                  "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                  "source": "flashpoint_extraction",
                  "sighted_at": "2025-12-23T10:41:44.231000Z",
                  "tags": [
                    "beacontype:hybrid http dns",
                    "extracted_config:true",
                    "httpposturi:/n4215/adj/amzn.us.sr.aps",
                    "malware:cobaltstrike",
                    "source:flashpoint_extraction",
                    "type:backdoor"
                  ],
                  "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                },
                "total_sightings": 229903
              },
              {
                "id": "pa1nUaXoVtuzyGb3HWKaBQ",
                "type": "domain",
                "value": "ns9.softline.top",
                "href": "https://api.flashpoint.io/technical-intelligence/v2/indicators/pa1nUaXoVtuzyGb3HWKaBQ",
                "entity_type": "indicator",
                "score": {
                  "value": "malicious",
                  "last_scored_at": "2025-07-30T07:26:35.100000Z"
                },
                "modified_at": "2025-12-23T11:18:16.650000Z",
                "created_at": "2024-01-01T00:00:00Z",
                "last_seen_at": "2025-12-23T11:12:06.372000Z",
                "sort_date": "2025-12-23T11:12:06.372000Z",
                "platform_urls": {
                  "ignite": "https://app.flashpoint.io/cti/malware/iocs/pa1nUaXoVtuzyGb3HWKaBQ"
                },
                "sightings": [
                  {
                    "id": "BqIOrT8HWaib7Cc-hOcoAA",
                    "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                    "source": "flashpoint_extraction",
                    "sighted_at": "2025-12-23T10:41:44.231000Z",
                    "tags": [
                      "beacontype:hybrid http dns",
                      "extracted_config:true",
                      "httpposturi:/n4215/adj/amzn.us.sr.aps",
                      "malware:cobaltstrike",
                      "source:flashpoint_extraction",
                      "type:backdoor"
                    ],
                    "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                  }
                ],
                "latest_sighting": {
                  "id": "BqIOrT8HWaib7Cc-hOcoAA",
                  "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                  "source": "flashpoint_extraction",
                  "sighted_at": "2025-12-23T10:41:44.231000Z",
                  "tags": [
                    "beacontype:hybrid http dns",
                    "extracted_config:true",
                    "httpposturi:/n4215/adj/amzn.us.sr.aps",
                    "malware:cobaltstrike",
                    "source:flashpoint_extraction",
                    "type:backdoor"
                  ],
                  "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                },
                "total_sightings": 229927
              }
            ],
            "total": null,
            "pagination": {
              "next": "http://{{ hostname }}:{{ env "PORT" }}/technical-intelligence/v2/indicators?modified_after=2025-12-18T10:00:00&from=4&size=2",
              "prev": "http://{{ hostname }}:{{ env "PORT" }}/technical-intelligence/v2/indicators?modified_after=2025-12-18T10:00:00&from=0&size=2"
            }
          }
  - path: /technical-intelligence/v2/indicators
    methods: ['GET']
    query_params:
      size: "2"
      from: "4"
      modified_after: "{modified_after:.*}"
    request_headers:
      Authorization: "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {
            "items": [
              {
                "id": "EtniFes7WyWvawEXcL2fmQ",
                "type": "domain",
                "value": "featured.xyz",
                "href": "https://api.flashpoint.io/technical-intelligence/v2/indicators/EtniFes7WyWvawEXcL2fmQ",
                "entity_type": "indicator",
                "score": {
                  "value": "informational",
                  "last_scored_at": "2025-11-03T08:46:17.620389Z"
                },
                "modified_at": "2025-12-23T10:58:20.798000Z",
                "created_at": "2025-11-03T08:35:08.714000Z",
                "last_seen_at": "2025-12-23T10:47:29.731000Z",
                "sort_date": "2025-12-23T10:47:29.731000Z",
                "platform_urls": {
                  "ignite": "https://app.flashpoint.io/cti/malware/iocs/EtniFes7WyWvawEXcL2fmQ"
                },
                "sightings": [
                  {
                    "id": "-mQDA1JEVYiXKTSenQuSbg",
                    "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/-mQDA1JEVYiXKTSenQuSbg",
                    "source": "flashpoint_extraction",
                    "sighted_at": "2025-12-23T10:47:29.731000Z",
                    "tags": [
                      "aes_key:be7b7befe99d381fbe34ef443b3179be7b7befe99d381fbe34ef443b31790e00",
                      "extracted_config:true",
                      "group:feturednew",
                      "malware:xworm",
                      "mutex:hr5unzmp8fhkimje",
                      "source:flashpoint_extraction",
                      "type:trojan"
                    ],
                    "description": "Observation: xworm [2025-12-23T10:47:29.731Z]"
                  }
                ],
                "latest_sighting": {
                  "id": "-mQDA1JEVYiXKTSenQuSbg",
                  "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/-mQDA1JEVYiXKTSenQuSbg",
                  "source": "flashpoint_extraction",
                  "sighted_at": "2025-12-23T10:47:29.731000Z",
                  "tags": [
                    "aes_key:be7b7befe99d381fbe34ef443b3179be7b7befe99d381fbe34ef443b31790e00",
                    "extracted_config:true",
                    "group:feturednew",
                    "malware:xworm",
                    "mutex:hr5unzmp8fhkimje",
                    "source:flashpoint_extraction",
                    "type:trojan"
                  ],
                  "description": "Observation: xworm [2025-12-23T10:47:29.731Z]"
                },
                "total_sightings": 11
              },
              {
                "id": "dH2jOrbPXm226gzXBq1EUg",
                "type": "file",
                "value": "10136d02ddb5e041c22a1a7214208509cf4c6606a3fd8ea0a03da0215228c54d",
                "href": "https://api.flashpoint.io/technical-intelligence/v2/indicators/dH2jOrbPXm226gzXBq1EUg",
                "entity_type": "indicator",
                "score": {
                  "value": "malicious",
                  "last_scored_at": "2025-12-23T10:58:23.852917Z"
                },
                "modified_at": "2025-12-23T10:58:24.706000Z",
                "created_at": "2025-12-23T10:47:29.731000Z",
                "last_seen_at": "2025-12-23T10:47:29.731000Z",
                "sort_date": "2025-12-23T10:47:29.731000Z",
                "platform_urls": {
                  "ignite": "https://app.flashpoint.io/cti/malware/iocs/dH2jOrbPXm226gzXBq1EUg"
                },
                "hashes": {
                  "md5": null,
                  "sha1": "14a85091e4d91fe58a81475498a5d037328c2431",
                  "sha256": "10136d02ddb5e041c22a1a7214208509cf4c6606a3fd8ea0a03da0215228c54d"
                },
                "sightings": [
                  {
                    "id": "-mQDA1JEVYiXKTSenQuSbg",
                    "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/-mQDA1JEVYiXKTSenQuSbg",
                    "source": "flashpoint_extraction",
                    "sighted_at": "2025-12-23T10:47:29.731000Z",
                    "tags": [
                      "aes_key:be7b7befe99d381fbe34ef443b3179be7b7befe99d381fbe34ef443b31790e00",
                      "extracted_config:true",
                      "group:feturednew",
                      "malware:xworm",
                      "mutex:hr5unzmp8fhkimje",
                      "source:flashpoint_extraction",
                      "type:trojan"
                    ],
                    "description": "Observation: xworm [2025-12-23T10:47:29.731Z]"
                  }
                ],
                "latest_sighting": {
                  "id": "-mQDA1JEVYiXKTSenQuSbg",
                  "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/-mQDA1JEVYiXKTSenQuSbg",
                  "source": "flashpoint_extraction",
                  "sighted_at": "2025-12-23T10:47:29.731000Z",
                  "tags": [
                    "aes_key:be7b7befe99d381fbe34ef443b3179be7b7befe99d381fbe34ef443b31790e00",
                    "extracted_config:true",
                    "group:feturednew",
                    "malware:xworm",
                    "mutex:hr5unzmp8fhkimje",
                    "source:flashpoint_extraction",
                    "type:trojan"
                  ],
                  "description": "Observation: xworm [2025-12-23T10:47:29.731Z]"
                },
                "total_sightings": 1
              }
            ],
            "total": null,
            "pagination": {
              "next": null,
              "prev": "http://{{ hostname }}:{{ env "PORT" }}/technical-intelligence/v2/indicators?modified_after=2025-12-18T10:00:00&from=2&size=2"
            }
          }
  - path: /technical-intelligence/v2/indicators
    methods: ['GET']
    query_params:
      size: "2"
      modified_after: "{modified_after:.*}"
    request_headers:
      Authorization: "Bearer xxxx"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {
            "items": [
              {
                "id": "bO3Y4XA7WWqaHbHy-H11YA",
                "type": "domain",
                "value": "ns7.softline.top",
                "href": "https://api.flashpoint.io/technical-intelligence/v2/indicators/bO3Y4XA7WWqaHbHy-H11YA",
                "entity_type": "indicator",
                "score": {
                  "value": "malicious",
                  "last_scored_at": "2025-07-30T07:26:22.823000Z"
                },
                "modified_at": "2025-12-23T11:18:09.404000Z",
                "created_at": "2024-01-01T00:00:00Z",
                "last_seen_at": "2025-12-23T11:12:06.372000Z",
                "sort_date": "2025-12-23T11:12:06.372000Z",
                "platform_urls": {
                  "ignite": "https://app.flashpoint.io/cti/malware/iocs/bO3Y4XA7WWqaHbHy-H11YA"
                },
                "sightings": [
                  {
                    "id": "BqIOrT8HWaib7Cc-hOcoAA",
                    "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                    "source": "flashpoint_extraction",
                    "sighted_at": "2025-12-23T10:41:44.231000Z",
                    "tags": [
                      "beacontype:hybrid http dns",
                      "extracted_config:true",
                      "httpposturi:/n4215/adj/amzn.us.sr.aps",
                      "malware:cobaltstrike",
                      "source:flashpoint_extraction",
                      "type:backdoor"
                    ],
                    "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                  }
                ],
                "latest_sighting": {
                  "id": "BqIOrT8HWaib7Cc-hOcoAA",
                  "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                  "source": "flashpoint_extraction",
                  "sighted_at": "2025-12-23T10:41:44.231000Z",
                  "tags": [
                    "beacontype:hybrid http dns",
                    "extracted_config:true",
                    "httpposturi:/n4215/adj/amzn.us.sr.aps",
                    "malware:cobaltstrike",
                    "source:flashpoint_extraction",
                    "type:backdoor"
                  ],
                  "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                },
                "total_sightings": 230089
              },
              {
                "id": "jGJDObZBWEK6upz3HX4NDA",
                "type": "extracted_config",
                "value": "{\"BeaconType\": \"Hybrid HTTP DNS\", \"HttpPostUri\": \"/N4215/adj/amzn.us.sr.aps\", \"type\": \"backdoor\", \"C2Server\": \"ns7.softline.top,/s/ref=nb_sb_noss_1/167-3294888-0262949/field-keywords=books,ns8.softline.top,/s/ref=nb_sb_noss_1/167-3294888-0262949/field-keywords=books,ns9.softline.top,/s/ref=nb_sb_noss_1/167-3294888-0262949/field-keywords=books\"}",
                "href": "https://api.flashpoint.io/technical-intelligence/v2/indicators/jGJDObZBWEK6upz3HX4NDA",
                "entity_type": "indicator",
                "score": {
                  "value": "no_score",
                  "last_scored_at": null
                },
                "modified_at": "2025-12-23T11:18:08.970000Z",
                "created_at": "2025-08-14T14:56:41.421000Z",
                "last_seen_at": "2025-12-23T11:12:06.372000Z",
                "sort_date": "2025-12-23T11:12:06.372000Z",
                "platform_urls": {
                  "ignite": "https://app.flashpoint.io/cti/malware/iocs/jGJDObZBWEK6upz3HX4NDA"
                },
                "sightings": [
                  {
                    "id": "BqIOrT8HWaib7Cc-hOcoAA",
                    "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                    "source": "flashpoint_extraction",
                    "sighted_at": "2025-12-23T10:41:44.231000Z",
                    "tags": [
                      "beacontype:hybrid http dns",
                      "extracted_config:true",
                      "httpposturi:/n4215/adj/amzn.us.sr.aps",
                      "malware:cobaltstrike",
                      "source:flashpoint_extraction",
                      "type:backdoor"
                    ],
                    "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                  }
                ],
                "latest_sighting": {
                  "id": "BqIOrT8HWaib7Cc-hOcoAA",
                  "href": "https://api.flashpoint.io/technical-intelligence/v2/sightings/BqIOrT8HWaib7Cc-hOcoAA",
                  "source": "flashpoint_extraction",
                  "sighted_at": "2025-12-23T10:41:44.231000Z",
                  "tags": [
                    "beacontype:hybrid http dns",
                    "extracted_config:true",
                    "httpposturi:/n4215/adj/amzn.us.sr.aps",
                    "malware:cobaltstrike",
                    "source:flashpoint_extraction",
                    "type:backdoor"
                  ],
                  "description": "Observation: cobaltstrike [2025-12-23T10:41:44.231Z]"
                },
                "total_sightings": 165488
              }
            ],
            "total": null,
            "pagination": {
              "next": "http://{{ hostname }}:{{ env "PORT" }}/technical-intelligence/v2/indicators?modified_after=2025-12-18T10:00:00&from=2&size=2",
              "prev": null
            }
          }
