# newer versions go on top
- version: "0.0.1"
  changes:
    - description: Initial draft of the Prometheus Input Package
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5167
