# newer versions go on top
- version: "0.1.2"
  changes:
    - description: Fix the typos in package
      type: bugfix
      link: https://github.com/elastic/integrations/pull/6399
- version: "0.1.1"
  changes:
    - description: Update the url's in README
      type: bugfix
      link: https://github.com/elastic/integrations/pull/6331
- version: "0.1.0"
  changes:
    - description: Rename ownership from obs-service-integrations to obs-infraobs-integrations
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6298
- version: "0.0.2"
  changes:
    - description: Add base fields mappings
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6212
- version: "0.0.1"
  changes:
    - description: Initial draft of the Prometheus Input Package
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6170
