# newer versions go on top
- version: 0.6.0
  changes:
    - description: Add processor support for input data stream.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/10411
- version: "0.5.0"
  changes:
    - description: ECS version updated to 8.11.0. Update the kibana constraint to ^8.13.0. Modified the field definitions to remove ECS fields made redundant by the ecs@mappings component template.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/10162
- version: 0.4.0
  changes:
    - description: Enable secrets for sensitive fields. For more details, refer https://www.elastic.co/guide/en/fleet/current/agent-policy.html#agent-policy-secret-values
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9321
- version: 0.3.1
  changes:
    - description: Disable secrets for older stack versions due to errors.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/9279
- version: 0.3.0
  changes:
    - description: Enable 'secret' for the sensitive fields, supported from 8.12.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/9009
- version: 0.2.0
  changes:
    - description: Update the package format_version to 3.0.0.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/8203
- version: "0.1.4"
  changes:
    - description: Fix test failure by upgrading the docker image version to the latest.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/8018
- version: "0.1.3"
  changes:
    - description: Add system test cases
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6490
- version: "0.1.2"
  changes:
    - description: Fix the typos in package
      type: bugfix
      link: https://github.com/elastic/integrations/pull/6399
- version: "0.1.1"
  changes:
    - description: Update the url's in README
      type: bugfix
      link: https://github.com/elastic/integrations/pull/6331
- version: "0.1.0"
  changes:
    - description: Rename ownership from obs-service-integrations to obs-infraobs-integrations
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6298
- version: "0.0.2"
  changes:
    - description: Add base fields mappings
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6212
- version: "0.0.1"
  changes:
    - description: Initial draft of the Prometheus Input Package
      type: enhancement
      link: https://github.com/elastic/integrations/pull/6170
