title: Kubernetes Pod metrics
type: metrics
streams:
  - input: kubernetes/metrics
    vars:
      - name: add_metadata
        type: bool
        title: Add Metadata
        multi: false
        required: true
        show_user: true
        default: true
      - name: bearer_token_file
        type: text
        title: Bearer Token File
        multi: false
        required: true
        show_user: true
        default: /var/run/secrets/kubernetes.io/serviceaccount/token
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - https://${env.NODE_NAME}:10250
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
      - name: ssl.verification_mode
        type: text
        title: SSL Verification Mode
        multi: false
        required: true
        show_user: true
        default: none
      - name: ssl.certificate_authorities
        type: text
        title: SSL Certificate Authorities
        multi: true
        required: false
        show_user: false
      - name: add_resource_metadata_config
        type: yaml
        title: Add node and namespace metadata
        required: false
        show_user: false
        default: |
          # add_resource_metadata:
          #   namespace:
          #     include_labels: ["namespacelabel1"]
          #   node:
          #     include_labels: ["nodelabel2"]
          #     include_annotations: ["nodeannotation1"]
          #   deployment: false
    title: Kubernetes Pod metrics
    description: Collect Kubernetes Pod metrics
