- external: ecs
  name: ecs.version
- external: ecs
  name: service.address
- external: ecs
  name: service.type
- external: ecs
  name: orchestrator.cluster.name
- external: ecs
  name: orchestrator.cluster.url
- external: ecs
  name: container.runtime
- name: container.cpu.usage
  type: scaled_float
  format: percent
  unit: percent
  metric_type: gauge
  description: |
    Total CPU usage normalized by the number of CPU cores.
- name: container.memory.usage
  type: scaled_float
  format: percent
  unit: percent
  metric_type: gauge
  description: |
    Memory usage percentage.
