services:
  couchdb:
    image: couchdb:${COUCHDB_VERSION:-3.2.2}
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 5984
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:5984/_up" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
