type: metrics
title: Docker network metrics
release: experimental
streams:
  - input: docker/metrics
    vars:
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - unix:///var/run/docker.sock
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
    title: Docker network metrics
    description: Collect Docker network metrics
