services:
  anyrun-ioc:
    image: "docker.elastic.co/observability/stream:v0.18.0"
    hostname: "anyrun-ioc"
    ports:
      - 8080
    volumes:
      - "./files:/files:ro"
    environment:
      PORT: "8090"
    command:
      - "http-server"
      - "--addr=:8080"
      - "--config=/files/config-ioc.yml"