- name: id
  cardinality: 100000
- name: providerAlertId
  cardinality: 100000
- name: incidentId
  cardinality: 100000
- name: status
  enum:
    - active
    - new
    - resolved
- name: severity
  enum:
    - low
    - high
    - medium
    - critical
    - informational
- name: classification
  cardinality: 100000
- name: determination
  cardinality: 100000
- name: serviceSource
  cardinality: 100000
- name: detectionSource
  cardinality: 100000
- name: productName
  cardinality: 100000
- name: detectorId
  cardinality: 100000
- name: tenantId
  cardinality: 100000
- name: title
  cardinality: 100000
- name: description
  cardinality: 100000
- name: recommendedActions
  cardinality: 100000
- name: category
  cardinality: 100000
- name: assignedTo
  cardinality: 100000
- name: alertWebUrl
  cardinality: 100000
- name: incidentWebUrl
  cardinality: 100000
- name: actorDisplayName
  cardinality: 100000
- name: threatDisplayName
  cardinality: 100000
- name: threatFamilyName
  cardinality: 100000
- name: mitreTechniques
  cardinality: 100000
- name: createdDateTime
  period: -24h
- name: lastUpdateDateTime
  period: -24h
- name: resolvedDateTime
  period: -24h
- name: firstActivityDateTime
  period: -24h
- name: lastActivityDateTime
  period: -24h
- name: alertPolicyId
  cardinality: 100000
- name: additionalData
  cardinality: 100000
- name: comments
  cardinality: 100000
- name: evidence.internetMessageId
  cardinality: 100000
- name: evidence.networkMessageId
  cardinality: 100000
- name: evidence.senderIp
  cardinality: 100000
- name: evidence.@odata.type
  cardinality: 100000
- name: evidence.createdDateTime
  period: -24h
- name: evidence.verdict
  cardinality: 100000
- name: evidence.remediationStatus
  cardinality: 100000
- name: evidence.remediationStatusDetails
  cardinality: 100000
- name: evidence.roles
  cardinality: 100000
- name: evidence.detailedRoles
  cardinality: 100000
- name: evidence.tags
  cardinality: 100000
- name: evidence.firstSeenDateTime
  period: -24h
- name: evidence.mdeDeviceId
  cardinality: 100000
- name: evidence.azureAdDeviceId
  cardinality: 100000
- name: evidence.deviceDnsName
  cardinality: 100000
- name: evidence.osPlatform
  cardinality: 100000
- name: evidence.osBuild
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: evidence.version
  cardinality: 100000
- name: evidence.healthStatus
  cardinality: 100000
- name: evidence.riskScore
  cardinality: 100000
- name: evidence.rbacGroupId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: evidence.rbacGroupName
  cardinality: 100000
- name: evidence.onboardingStatus
  cardinality: 100000
- name: evidence.defenderAvStatus
  cardinality: 100000
- name: evidence.ipInterfaces
  cardinality: 100000
- name: evidence.vmMetadata
  cardinality: 100000
- name: evidence.loggedOnUsers.accountName
  cardinality: 100000
- name: evidence.loggedOnUsers.domainName
  cardinality: 100000
- name: '@odata.context'
  cardinality: 100000
- name: value
  cardinality: 100000
