fields:
  - name: schemaVersion
    enum:
      - "1.0"
      - "1.1"
      - "1.11"
  - name: alertId
    cardinality: 100000
  - name: investigationStatus
    enum:
      - New
      - In Progress
      - True Positive
      - False Positive
      - Benign True Positive
      - Closed
  - name: alertProvider
    enum:
      - SAE
      - TI
  - name: model
    cardinality: 1000
  - name: score
    range:
      min: 0
      max: 100
  - name: severity
    enum:
      - critical
      - high
      - medium
      - low
      - informational
  - name: createdDateTime
    period: -24h
  - name: updatedDateTime
    period: -24h
  - name: description
    cardinality: 10000
  - name: desktopCount
    range:
      min: 0
      max: 100
  - name: serverCount
    range:
      min: 0
      max: 50
  - name: accountCount
    range:
      min: 0
      max: 20
  - name: emailAddressCount
    range:
      min: 0
      max: 10
  - name: entityType
    enum:
      - host
      - account
      - emailAddress
      - container
      - cloudIdentity
      - cloudWorkload
  - name: entityValue
    cardinality: 10000
  - name: entityId
    cardinality: 10000
  - name: indicatorType
    enum:
      - url
      - ip
      - domain
      - file_sha1
      - file_sha256
      - command_line
      - fullpath
      - host
  - name: indicatorField
    enum:
      - request url
      - objectCmd
      - processCmd
      - objectFileHashSha1
      - objectFilePath
      - processFilePath
  - name: indicatorValue
    cardinality: 10000
  - name: ruleId
    cardinality: 10000
  - name: ruleName
    cardinality: 1000
  - name: filterName
    cardinality: 1000
  - name: mitreTechniqueId
    enum:
      - T1059.001
      - T1192
      - T1021.004
      - T1071.001
      - T1090
