http.host: "0.0.0.0"
config.reload.automatic: true
path.logs: /usr/share/logstash/logs
log.format: plain
slowlog.threshold.warn: 1nanos
slowlog.threshold.info: 1nanos
slowlog.threshold.debug: 1nanos
slowlog.threshold.trace: 1nanos
