fields:
  - name: timestamp
    period: -24h
  - name: cursor
    cardinality: 100000
  - name: id
    cardinality: 100000
  - name: analystVerdict
    enum:
      - UNDEFINED
      - TRUE_POSITIVE_BENIGN_BUT_SUSPICIOUS
      - FALSE_POSITIVE_BENIGN
      - TRUE_POSITIVE_MALWARE
      - TRUE_POSITIVE_RANSOMWARE
  - name: classification
    enum:
      - MALWARE
      - RANSOMWARE
      - PHISHING
      - EXPLOIT
      - BENIGN
      - APPLICATION_CONTROL
  - name: confidenceLevel
    enum:
      - MALICIOUS
      - SUSPICIOUS
      - INFORMATIONAL
  - name: createdAt
    cardinality: 1000
  - name: detectedAt
    cardinality: 1000
  - name: firstSeenAt
    cardinality: 1000
  - name: lastSeenAt
    cardinality: 1000
  - name: updatedAt
    cardinality: 1000
  - name: name
    cardinality: 10000
  - name: result
    enum:
      - UNMITIGATED
      - MITIGATED
      - BENIGN
  - name: severity
    enum:
      - CRITICAL
      - HIGH
      - MEDIUM
      - LOW
      - INFO
      - UNKNOWN
  - name: status
    enum:
      - NEW
      - IN_PROGRESS
      - RESOLVED
  - name: externalId
    range:
      min: 1000000000000000000
      max: 9999999999999999999
    cardinality: 10000
  - name: description
    cardinality: 1000
  - name: attackSurfaces
    enum:
      - ENDPOINT
      - EMAIL
      - NETWORK
      - IDENTITY
  - name: analytics.category
    enum:
      - Reputation
      - Manual
      - Behavioral
  - name: analytics.name
    cardinality: 100
  - name: analytics.typeValue
    enum:
      - STATIC
      - DYNAMIC
  - name: detectionSource.product
    enum:
      - CWS
      - CWP
  - name: detectionSource.vendor
    value: SentinelOne
  - name: assets.agentUuid
    cardinality: 10000
  - name: assets.agentVersion
    enum:
      - 24.2.2.20
      - 24.1.5.277
  - name: assets.osType
    enum:
      - LINUX
      - WINDOWS
      - MACOS
  - name: assets.status
    enum:
      - ACTIVE
      - INACTIVE
  - name: process.cmdLine
    cardinality: 5000
  - name: process.file.name
    cardinality: 5000
  - name: process.file.path
    cardinality: 5000
  - name: process.file.sha256
    cardinality: 100000
  - name: process.file.sha1
    cardinality: 100000
  - name: process.file.md5
    cardinality: 100000
  - name: process.parentName
    cardinality: 500
  - name: detectionTime.scope.accountId
    cardinality: 10
  - name: detectionTime.scope.accountName
    cardinality: 10
  - name: detectionTime.scope.siteName
    cardinality: 100
  - name: detectionTime.scope.groupName
    cardinality: 100
  - name: detectionTime.attacker.host
    cardinality: 5000
  - name: detectionTime.targetUser.emailAddress
    cardinality: 10000
  - name: detectionTime.targetUser.name
    cardinality: 10000
  - name: detectionTime.assets.kubernetes.clusterName
    cardinality: 100
  - name: detectionTime.assets.kubernetes.namespaceName
    cardinality: 500
  - name: detectionTime.assets.kubernetes.podName
    cardinality: 5000
  - name: detectionTime.assets.kubernetes.containerName
    cardinality: 5000
  - name: realTime.scope.account.id
    cardinality: 10
  - name: realTime.scope.site.name
    cardinality: 100
  - name: realTime.scope.group.name
    cardinality: 100
