version: '2.3'
services:
  zscaler-zia-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  zscaler-zia-udp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9538 -p=udp /sample_logs/zscaler-zia-*.log"
  zscaler-zia-tcp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9538 -p=tcp /sample_logs/zscaler-zia-*.log"
