fields:
  - name: added_at
    period: -24h
  - name: classification
    enum:
      - private
      - public
  - name: confidence
    cardinality: 100
  - name: country
    enum:
      - US
      - DE
      - IN
      - VS
      - RU
  - name: date_first
    period: -24h
  - name: date_last
    period: -24h
  - name: detail
    enum:
      - phish-kit-sig-id-43111996,Microsoft
      - first_seen=2020-04-13T09:30:20,IP=192.168.113.221,ciib,o2d,mask=192.168.2.110,popularity=high
      - 32-bit,date_added=2020-10-09T15:44:05,elf,mips
      - gnh7,Botnet-DRZ8-,popularity=low,type=2,first_seen=2020-01-07T01:38:35,Botnet-WSPDZDY,mask=192.168.113.180,popularity=low,threat=gu3wn7
  - name: detail2
    enum:
      - imported by user 1
      - imported by user 710
  - name: id
    cardinality: 1000000
  - name: itype
    enum:
      - mal_md5
      - phish_url
      - scan_ip
      - mal_url
      - mal_domain
  - name: lat
    cardinality: 100
  - name: maltype
    enum:
      - phish-kit-sig-id-43111996
      - 32-bit
      - malware:mi5n
  - name: resource_uri
    enum:
      - /api/v1/intelligence/P29675942316/
      - /api/v1/intelligence/22222/
      - /api/v1/intelligence/111111/
  - name: severity
    enum:
      - very-high
      - high
      - medium
      - low
  - name: source
    enum:
      - Default Organization
      - Phony generated indicator
  - name: source_feed_id
    cardinality: 1000000
  - name: state
    value: active
  - name: timestamp
    period: -24h
  - name: trusted_circle_ids
    cardinality: 1000000
  - name: update_id
    cardinality: 1000000
  - name: url
    enum:
      - http://onv7s.example.org/29j3q7kc/4l0za3s?viyrr-vd=hde
      - http://ureumt8.example.org/ffey/ugwd?770694=x4r5wc-k
      - https://5wcz6kck.example.net/mankgvtpl/1suq?vx-gvh=00tc4
      - https://v6cw8.example.org/yw7fom/x6xp?3ck=i3ko4
      - http://tccdg3.example.net/2vgsz9a/9tzk9?xsy9af-=jz3ibf
  - name: value_type
    enum:
      - url
      - ip
      - domain
