---
description: Benchmark 8640000 kubernetes.container events ingested
data_stream:
  name: container
corpora:
  generator:
    total_events: 8640000
    template:
      type: gotext
      path: ./container-benchmark/template.ndjson
    config:
      path: ./container-benchmark/config.yml
    fields:
      path: ./container-benchmark/fields.yml
