---
description: Benchmark 8640000 kubernetes.pod events ingested
data_stream:
  name: pod
corpora:
  generator:
    total_events: 8640000
    template:
      type: gotext
      path: ./pod-benchmark/template.ndjson
    config:
      path: ./pod-benchmark/config.yml
    fields:
      path: ./pod-benchmark/fields.yml
