version: '2.3'
services:
  darktrace-ai_analyst_alert-tls:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9571 -p=tls --insecure /sample_logs/ai_analyst_alert.log
  darktrace-ai_analyst_alert-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9571 -p=tcp /sample_logs/ai_analyst_alert.log
  darktrace-ai_analyst_alert-udp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9574 -p=udp /sample_logs/ai_analyst_alert.log
  darktrace-model_breach_alert-tls:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9572 -p=tls --insecure /sample_logs/model_breach_alert.log
  darktrace-model_breach_alert-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9572 -p=tcp /sample_logs/model_breach_alert.log
  darktrace-model_breach_alert-udp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9575 -p=udp /sample_logs/model_breach_alert.log
  darktrace-system_status_alert-tls:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9573 -p=tls --insecure /sample_logs/system_status_alert.log
  darktrace-system_status_alert-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9573 -p=tcp /sample_logs/system_status_alert.log
  darktrace-system_status_alert-udp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9576 -p=udp /sample_logs/system_status_alert.log
  darktrace:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: darktrace
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8080'
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config.yml
