version: '2.3'
services:
  cloudflare-logpush-audit-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/audit.log
  cloudflare-logpush-dns-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9561/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/dns.log
  cloudflare-logpush-firewall-event-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9562/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/firewall_event.log
  cloudflare-logpush-http-request-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9563/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/http_request.log
  cloudflare-logpush-nel-report-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9564/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/nel_report.log
  cloudflare-logpush-network-analytics-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9565/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/network_analytics.log
  cloudflare-logpush-spectrum-event-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9566/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/spectrum_event.log
  cloudflare-logpush-gateway-dns-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9567/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/gateway_dns.log
  cloudflare-logpush-gateway-http-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9568/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/gateway_http.log
  cloudflare-logpush-gateway-network-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9569/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/gateway_network.log
  cloudflare-logpush-network-session-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9570/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/network_session.log
  cloudflare-logpush-casb-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9571/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/casb.log
  cloudflare-logpush-access-request-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9572/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/access_request.log
  cloudflare-logpush-device-posture-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9573/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/device_posture.log
  cloudflare-logpush-workers-trace-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.7.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9574/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/workers_trace.log
