version: '2.3'
services:
  cloudflare-logpush-audit-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/audit
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/audit.log
  cloudflare-logpush-dns-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/dns
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/dns.log
  cloudflare-logpush-firewall-event-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/firewall_event
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/firewall_event.log
  cloudflare-logpush-http-request-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/http_request
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/http_request.log
  cloudflare-logpush-nel-report-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/nel_report
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/nel_report.log
  cloudflare-logpush-network-analytics-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/network_analytics
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/network_analytics.log
  cloudflare-logpush-spectrum-event-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/spectrum_event
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/spectrum_event.log
  cloudflare-logpush-gateway-dns-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/gateway_dns
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/gateway_dns.log
  cloudflare-logpush-gateway-http-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/gateway_http
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/gateway_http.log
  cloudflare-logpush-gateway-network-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/gateway_network
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/gateway_network.log
  cloudflare-logpush-network-session-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/network_session
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/network_session.log
  cloudflare-logpush-casb-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/casb
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/casb.log
  cloudflare-logpush-access-request-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/access_request
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/access_request.log
  cloudflare-logpush-device-posture-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/device_posture
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/device_posture.log
  cloudflare-logpush-workers-trace-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/workers_trace
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/workers_trace.log
  cloudflare-logpush-magic-ids-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/magic_ids
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/magic_ids.log
  cloudflare-logpush-sinkhole-http-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/sinkhole_http
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/sinkhole_http.log
  cloudflare-logpush-dns-firewall-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:9560/cloudflare_logpush/dns_firewall
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/dns_firewall.log
