version: '2.3'
services:
  servicenow:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: servicenow
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
  servicenow-oauth2:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: servicenow-oauth2
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config_oauth2.yml
