fields:
  - name: timestamp
    period: -24h # one day
  - name: duration_start
    enum: 
      - "-1h"
      - "-2h"
      - "-3h"
  - name: duration_end
    enum: 
      - "-30m"
      - "-20m"
      - "-10m"
  - name: id
    range:
      min: 100000
      max: 9999999
    cardinality: 100000
  - name: threat_type
    enum: 
      - "botnet_cc"
      - "payload_delivery"
      - "payload"
  - name: threat_type_desc
    enum: 
      - "Indicator that identifies a botnet command&control server (C&C)"
      - "Indicator that identifies a malware distribution server (payload delivery)"
      - "Indicator that identifies a malware sample (payload)"
  - name: ioc.type
    enum: 
      - "ip:port"
      - "domain"
      - "url"
      - "md5_hash"
      - "sha1_hash"
      - "sha256_hash"
  - name: ioc.type_desc
    enum: 
      - "ip:port combination that is used for botnet Command&control (C&C)"
      - "ip:port combination that delivery a malware payload"
      - "Domain that is used for botnet Command&control (C&C)"
      - "Domain name that delivers a malware payload"
      - "Domain used for credit card skimming (usually related to Magecart attacks)"
      - "URL that is used for botnet Command&control (C&C)"
      - "MD5 hash of a malware sample (payload)"
  - name: ioc.ip_port
    range:
      min: 0
      max: 65535
    cardinality: 10000
  - name: ioc.urlpathnum
    cardinality: 10000
  - name: ioc.domain
    cardinality: 100000
  - name: ioc.file
    cardinality: 100000
  - name: malware
    cardinality: 100000
  - name: confidence_level
    range:
      min: 0
      max: 100
    cardinality: 100
  - name: reporter
    cardinality: 1000
  - name: reference
    cardinality: 10000
