version: '2.3'
services:
  tanium-tcp-reporting:
    image: docker.elastic.co/observability/stream:v0.20.0
    volumes:
    - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9085 -p=tcp
      /sample_logs/reporting.log
  tanium-reporting-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.20.0
    volumes:
    - ./sample_logs:/sample_logs:ro
    environment:
    - STREAM_PROTOCOL=webhook
    - STREAM_WEBHOOK_PROBE=false
    - STREAM_ADDR=http://elastic-agent:9091/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/reporting.log
