version: '2.3'
services:
  exchange-online-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  exchange_online:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: exchange_online
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: "8080"
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config.yml
