- name: kubernetes.persistentvolume
  type: group
  fields:
    - name: name
      dimension: true
      type: keyword
      description: Volume name.
    - name: capacity.bytes
      type: long
      unit: byte
      metric_type: gauge
      description: Volume capacity
    - name: phase
      type: keyword
      description: Volume phase according to kubernetes
    - name: storage_class
      type: keyword
      description: Storage class for the volume
