- external: ecs
  name: ecs.version
- external: ecs
  name: service.address
- external: ecs
  name: service.type
- external: ecs
  name: orchestrator.cluster.name
- external: ecs
  name: orchestrator.cluster.url
- name: container.network.egress.bytes
  type: long
  format: bytes
  metric_type: counter
  description: |
    Total number of outgoing bytes.
- name: container.network.ingress.bytes
  type: long
  format: bytes
  metric_type: counter
  description: |
    Total number of incoming bytes.
