- name: kubernetes.pod
  type: group
  fields:
    - name: start_time
      type: date
      description: |
        Start time
    - name: network
      type: group
      fields:
        - name: rx
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: counter
              description: |
                Received bytes
            - name: errors
              type: long
              metric_type: counter
              description: |
                Rx errors
        - name: tx
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: counter
              description: |
                Transmitted bytes
            - name: errors
              type: long
              metric_type: counter
              description: |
                Tx errors
    - name: cpu
      type: group
      fields:
        - name: usage
          type: group
          fields:
            - name: nanocores
              type: long
              unit: byte
              metric_type: gauge
              description: |
                CPU used nanocores
            - name: node.pct
              type: scaled_float
              format: percent
              unit: percent
              metric_type: gauge
              description: |
                CPU usage as a percentage of the total node CPU
            - name: limit.pct
              type: scaled_float
              format: percent
              unit: percent
              metric_type: gauge
              description: |
                CPU usage as a percentage of the defined limit for the pod containers (or total node CPU if one or more containers of the pod are unlimited)
    - name: memory
      type: group
      fields:
        - name: usage
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Total memory usage
            - name: node.pct
              type: scaled_float
              format: percent
              unit: percent
              metric_type: gauge
              description: |
                Memory usage as a percentage of the total node allocatable memory
            - name: limit.pct
              type: scaled_float
              format: percent
              unit: percent
              metric_type: gauge
              description: |
                Memory usage as a percentage of the defined limit for the pod containers (or total node allocatable memory if unlimited)
        - name: available
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: percent
              metric_type: gauge
              description: |
                Total memory available
        - name: working_set
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: percent
              metric_type: gauge
              description: |
                Total working set memory
            - name: limit.pct
              type: scaled_float
              format: percent
              unit: percent
              metric_type: gauge
              description: >
                Working set memory usage as a percentage of the defined limit for the pod containers (or total node allocatable memory if unlimited)

        - name: rss
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: percent
              metric_type: gauge
              description: |
                Total resident set size memory
        - name: page_faults
          type: long
          metric_type: counter
          description: |
            Total page faults
        - name: major_page_faults
          type: long
          metric_type: counter
          description: |
            Total major page faults
    - name: ip
      type: ip
      description: Kubernetes pod IP
