---
description: Pipeline for ForgeRock IDM config logs.
# ForgeRock IDM Configuration Logs: https://backstage.forgerock.com/docs/idm/7.2/audit-guide/config-event-prop.html
processors:  
  - set: 
      field: user.id
      copy_from: forgerock.userId
      ignore_failure: true
  - set: 
      field: user.effective.id
      copy_from: forgerock.runAs
      ignore_failure: true
