version: '2.3'
services:
  gcppubsub-emulator:
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8681
    ports:
      - "8681/tcp"
  gcppubsub-audit:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command:
      - log
      - --retry=30
      - --addr=gcppubsub-emulator:8681
      - -p=gcppubsub
      - --gcppubsub-clear=true
      - --gcppubsub-project=audit
      - /sample_logs/audit.log
    depends_on:
      - gcppubsub-emulator
  gcppubsub-dns:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command:
      - log
      - --retry=30
      - --addr=gcppubsub-emulator:8681
      - -p=gcppubsub
      - --gcppubsub-clear=true
      - --gcppubsub-project=dns
      - /sample_logs/dns.log
    depends_on:
      - gcppubsub-emulator
  gcppubsub-firewall:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command:
      - log
      - --retry=30
      - --addr=gcppubsub-emulator:8681
      - -p=gcppubsub
      - --gcppubsub-clear=true
      - --gcppubsub-project=firewall
      - /sample_logs/firewall.log
    depends_on:
      - gcppubsub-emulator
  gcppubsub-vpcflow:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command:
      - log
      - --retry=30
      - --addr=gcppubsub-emulator:8681
      - -p=gcppubsub
      - --gcppubsub-clear=true
      - --gcppubsub-project=vpcflow
      - /sample_logs/vpcflow.log
    depends_on:
      - gcppubsub-emulator
  gcppubsub-load-balancer:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command:
      - log
      - --retry=30
      - --addr=gcppubsub-emulator:8681
      - -p=gcppubsub
      - --gcppubsub-clear=true
      - --gcppubsub-project=load_balancer
      - /sample_logs/load_balancer.log
    depends_on:
      - gcppubsub-emulator
