- name: data_stream.type
  type: constant_keyword
  description: Data stream type.
- name: data_stream.dataset
  type: constant_keyword
  description: Data stream dataset.
- name: data_stream.namespace
  type: constant_keyword
  description: Data stream namespace.
- name: event.dataset
  type: constant_keyword
  description: Event Dataset.
  value: kubernetes.audit_logs
- name: '@timestamp'
  type: date
  description: Event timestamp.
- name: log.offset
  type: long
  description: Offset of the entry in the log file.
- name: log.file.path
  type: keyword
  description: Path to the log file.
- name: input.type
  description: Type of input.
  type: keyword
