version: '2.3'
services:
  wiz-audit:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: wiz-audit
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config-audit.yml
  wiz-issue:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: wiz-issue
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config-issue.yml
  wiz-vulnerability:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: wiz-vulnerability
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config-vulnerability.yml
