services:
  postgresql_input_otel:
    build:
      context: .
      args:
        SERVICE_VERSION: ${SERVICE_VERSION}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # Enable logging
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - 5432
