- external: ecs
  name: ecs.version
- external: ecs
  name: error.message
- external: ecs
  name: event.ingested
- external: ecs
  name: agent.name
- external: ecs
  name: agent.type
- external: ecs
  name: agent.id
- external: ecs
  name: agent.ephemeral_id
- external: ecs
  name: agent.version
- external: ecs
  name: message
- external: ecs
  name: container.runtime
- external: ecs
  name: orchestrator.cluster.name
- external: ecs
  name: orchestrator.cluster.url
- external: ecs
  name: service.name
- external: ecs
  name: service.version
- external: ecs
  name: tags
