fields:
  - name: eventTime
    range:
      min: 1735689600000
      max: 1771977600000
  - name: authId
    enum:
      - "999"
  - name: endpointGuid
    cardinality: 10000
  - name: endpointHostName
    cardinality: 10000
  - name: endpointIp
    cardinality: 10000
  - name: endpointMacAddress
    cardinality: 10000
  - name: eventHashId
    cardinality: 100000
  - name: eventId
    range:
      min: 1
      max: 20
  - name: eventSourceType
    range:
      min: 1
      max: 5
  - name: eventSubId
    range:
      min: 0
      max: 700
  - name: firstSeen
    range:
      min: 1735689600000
      max: 1771977600000
  - name: integrityLevel
    range:
      min: 4096
      max: 16384
  - name: lastSeen
    range:
      min: 1735689600000
      max: 1771977600000
  - name: logReceivedTime
    range:
      min: 1735689600000
      max: 1771977600000
  - name: objectFilePath
    cardinality: 10000
  - name: objectFileSize
    range:
      min: 0
      max: 100000000
  - name: objectHashId
    cardinality: 100000
  - name: osDescription
    enum:
      - "Windows 10 Pro (64 bit) build 19045"
      - "Windows 11 Pro (64 bit) build 22621"
      - "Windows Server 2022 Datacenter"
  - name: osName
    enum:
      - Windows
      - Linux
      - macOS
  - name: osVer
    enum:
      - "10.0.19045"
      - "10.0.22621"
      - "6.1.7601"
  - name: processCmd
    cardinality: 10000
  - name: processFileHashMd5
    cardinality: 100000
  - name: processFileHashSha1
    cardinality: 100000
  - name: processFileHashSha256
    cardinality: 100000
  - name: processFilePath
    cardinality: 10000
  - name: processFileSize
    range:
      min: 1000
      max: 10000000
  - name: processName
    cardinality: 10000
  - name: processPid
    range:
      min: 1
      max: 65535
    cardinality: 10000
  - name: processUser
    enum:
      - SYSTEM
      - NETWORK SERVICE
      - LOCAL SERVICE
  - name: processUserDomain
    enum:
      - NT AUTHORITY
      - WORKGROUP
  - name: productCode
    enum:
      - xes
  - name: pver
    enum:
      - "1.2.0.5960"
      - "1.2.0.5961"
  - name: sessionId
    range:
      min: 0
      max: 10
  - name: timezone
    enum:
      - "UTC+00:00"
      - "UTC-05:00"
      - "UTC+08:00"
  - name: uuid
    cardinality: 100000
  - name: dpt
    range:
      min: 1
      max: 65535
    cardinality: 1000
  - name: dst
    cardinality: 10000
  - name: spt
    range:
      min: 1024
      max: 65535
    cardinality: 10000
  - name: src
    cardinality: 10000
