rules:
  - path: /auth/jwt_access_token
    methods: ["POST"]
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - application/json
        body: |
          {
            "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlRlc3QgVXNlciIsImlhdCI6MTUxNjIzOTAyMn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
            "expires": "2099-12-31T23:59:59.999Z"
          }
  - path: /events
    methods: ["GET"]
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - application/json
        body: |
          {
            "paging": {
              "pit_id": "cmFuZG9tX3ZhbHVl",
              "search_after": null,
              "size": "500",
              "next_search_after": null
            },
            "hits": 2,
            "results": [
              {
                "request": {
                  "id": "1234zID",
                  "type": "email_settings#create_organization_email"
                },
                "performer": {
                  "meta": {
                    "name": "Allison Jamie",
                    "username": "allison.j@omniva-corp.com"
                  },
                  "id": 12345,
                  "ip_address": "192.168.0.1",
                  "type": "user"
                },
                "organization_id": 123,
                "event": {
                  "meta": null,
                  "target_type": "Global Email Added",
                  "type": "action"
                },
                "event_time": "2023-06-02T16:06:19.217Z"
              },
              {
                "request": {
                  "id": "1234zID",
                  "type": "email_settings#create_organization_email"
                },
                "performer": {
                  "meta": {
                    "name": "Allison Jamie",
                    "username": "allison.j@omniva-corp.com"
                  },
                  "id": 12345,
                  "ip_address": "192.168.0.1",
                  "type": "user"
                },
                "organization_id": 123,
                "event": {
                  "meta": {
                    "id": [null, 1234],
                    "value": [null, "johnny.c@omniva-corp.com"]
                  },
                  "target_type": "OrganizationEmail",
                  "target_id": 1234,
                  "type": "data_change_create"
                },
                "event_time": "2023-06-02T16:06:19.137Z"
              }
            ]
          }
