- name: docker.container.labels.*
  type: object
  object_type: keyword
  object_type_mapping_type: "*"
  description: |
    Container labels
- name: docker.memory
  type: group
  fields:
    - name: stats.*
      type: object
      description: |
        Raw memory stats from the cgroups memory.stat interface
    - name: commit
      type: group
      fields:
        - name: total
          type: long
          format: bytes
          unit: byte
          metric_type: counter
          description: |
            Total bytes
        - name: peak
          type: long
          format: bytes
          unit: byte
          metric_type: gauge
          description: |
            Peak committed bytes on Windows
    - name: private_working_set.total
      type: long
      format: bytes
      unit: byte
      metric_type: gauge
      description: |
        private working sets on Windows
    - name: fail.count
      type: scaled_float
      metric_type: counter
      description: |
        Fail counter.
    - name: limit
      type: long
      format: bytes
      unit: byte
      metric_type: gauge
      description: |
        Memory limit.
    - name: rss
      type: group
      fields:
        - name: total
          type: long
          format: bytes
          unit: byte
          metric_type: gauge
          description: |
            Total memory resident set size.
        - name: pct
          type: scaled_float
          format: percent
          unit: percent
          metric_type: gauge
          description: |
            Memory resident set size percentage.
    - name: usage
      type: group
      fields:
        - name: max
          type: long
          format: bytes
          unit: byte
          metric_type: gauge
          description: |
            Max memory usage.
        - name: pct
          type: scaled_float
          format: percent
          unit: percent
          metric_type: gauge
          description: |
            Memory usage percentage.
        - name: total
          type: long
          format: bytes
          unit: byte
          metric_type: gauge
          description: |
            Total memory usage.
