rules:
  - path: /as/token.oauth2
    methods: ['POST']
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |
          {"access_token":"xxxx","expires_in":3600,"token_type":"Bearer"}
  - path: /rest/1.0/export_profiles/abc123/export_and_ack
    methods: ['POST']
    request_headers:
      Accept:
        - "application/json"
    responses:
      - status_code: 200
        body: |-
          {{ minify_json `
          {
            "fields": [
                {
                    "array": false,
                    "name": "dg_name",
                    "type": "string",
                    "display_name": "Name",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "inc_creator",
                    "type": "string",
                    "display_name": "Creator",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "inc_assign",
                    "type": "string",
                    "display_name": "Assignee",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "inc_state",
                    "type": "string",
                    "display_name": "Incident State",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "dg_description",
                    "type": "string",
                    "display_name": "Description",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "inc_id",
                    "type": "string",
                    "display_name": "Incident ID",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "dg_comment",
                    "type": "string",
                    "display_name": "Comment",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "inc_mtime",
                    "type": "timestamp",
                    "display_name": "Modified Time",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "dg_guid",
                    "type": "string",
                    "display_name": "Unique ID",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "inc_sev",
                    "type": "int",
                    "display_name": "Severity",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "dg_utype",
                    "type": "string",
                    "display_name": "Operation Type",
                    "tags": [],
                    "encrypt": false
                },
                {
                    "array": false,
                    "name": "dg_tenant",
                    "type": "guid",
                    "display_name": "Tenant ID",
                    "tags": [],
                    "encrypt": false
                }
            ],
            "data": [
                [
                    "test has attached a Salesforce data to an email",
                    "dg",
                    "test@dgdemo",
                    "Created",
                    "This file outlook.exe was going to [demo.digitalg@gmail.com]",
                    "230523-WIQHA",
                    "-",
                    "2023-05-23 06:56:39",
                    "1dc3c1fa-5474-4fc0-a7c3-74ff42d28e5e",
                    "Critical",
                    "Incident",
                    "279b59f3-02f3-44ea-a7c3-9bac2eb0224d"
                ],
                [
                    "Demo 10",
                    "demo@dgdemo",
                    "demo@dgdemo",
                    "Escalated",
                    "-",
                    "230523-RG0AB",
                    "-",
                    "2023-05-23 11:53:11",
                    "c742c377-b429-428a-b0c9-515cbbf143be",
                    "Critical",
                    "Incident",
                    "279b59f3-02f3-44ea-a7c3-9bac2eb0224d"
                ],
                [
                    "Demo 11",
                    "demo11@dgdemo",
                    "demo11@dgdemo",
                    "Escalated",
                    "-",
                    "230624-RG1AB",
                    "-",
                    "2024-06-23 11:53:11",
                    "a842c377-b429-428a-b0c9-515cbbf133be",
                    "Critical",
                    "Incident",
                    "129b59f3-02f3-44ea-a7c3-9bac2eb0124d"
                ],
                [
                    "Demo 12",
                    "demo12@dgdemo",
                    "demo12@dgdemo",
                    "Escalated",
                    "-",
                    "210624-RG1AB",
                    "-",
                    "2024-07-23 12:53:11",
                    "a942b377-b429-428a-b0c9-515cbbf133be",
                    "Critical",
                    "Incident",
                    "128b59f3-01f3-44ea-a7c3-9bac2eb0124d"
                ],
                [
                    "Demo 13",
                    "demo13@dgdemo",
                    "demo13@dgdemo",
                    "Created",
                    "-",
                    "200624-RG1AB",
                    "-",
                    "2024-07-21 10:53:11",
                    "aa42b379-b429-428a-b0c9-515cbbf133be",
                    "Medium",
                    "Incident",
                    "128b59f3-01f3-44ea-a7c3-9bac2eb0124d"
                ],
                [
                    "Demo 14",
                    "demo14@dgdemo",
                    "demo14@dgdemo",
                    "Created",
                    "-",
                    "200524-RG1AB",
                    "-",
                    "2024-07-22 05:43:11",
                    "ba42f379-b329-428a-b0c9-515cbbf133be",
                    "High",
                    "Incident",
                    "128b59f3-01f3-44ea-a7c3-9bac2eb0124d"
                ],
                [
                    "Demo 15",
                    "demo15@dgdemo",
                    "demo15@dgdemo",
                    "Created",
                    "-",
                    "201524-RG3AB",
                    "-",
                    "2024-07-25 05:43:11",
                    "da42fg79-b129-428a-b0c9-515cbbf133be",
                    "Minor",
                    "Incident",
                    "128b59f3-01f3-44ea-a7c3-9bac2eb0124d"
                ],
                [
                    "Demo 16",
                    "demo16@dgdemo",
                    "demo16@dgdemo",
                    "Created",
                    "-",
                    "201424-RG3AB",
                    "-",
                    "2024-07-26 05:43:11",
                    "db42ff79-b129-428a-b0c9-515cbbf133be",
                    "Informational",
                    "Incident",
                    "128b59f3-01f3-44ea-a7c3-9bac2eb0124d"
                ],
                [
                    "Demo 17",
                    "demo17@dgdemo",
                    "demo17@dgdemo",
                    "Created",
                    "-",
                    "201224-RG3AB",
                    "-",
                    "2024-07-28 05:45:11",
                    "db31ff78-b129-428a-b0c9-515cbbf133be",
                    "Informational",
                    "Incident",
                    "128b59f3-01f3-44ea-a7c3-9bac2eb0124d"
                ],
                [
                    "Demo 18",
                    "demo18@dgdemo",
                    "demo18@dgdemo",
                    "Created",
                    "-",
                    "201214-RG2AB",
                    "-",
                    "2024-07-29 05:41:11",
                    "db21fg78-b129-428a-b0c9-515cbbf133be",
                    "Informational",
                    "Incident",
                    "128b59f3-01f3-44ea-a7c3-9bac2eb0124d"
                ]
            ],
            "total_hits": 10
            }
          `}}
