version: '2.3'
services:
  cyberark-corepas-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  cyberark-corepas-udp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9543 -p=udp /sample_logs/cyberark-corepas-*.log"
  cyberark-corepas-tcp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9543 -p=tcp /sample_logs/cyberark-corepas-*.log"
