title: Prometheus query metrics
release: experimental
type: metrics
streams:
  - input: prometheus/metrics
    vars:
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - localhost:9090
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
      - name: queries
        type: yaml
        title: Queries
        multi: false
        required: true
        show_user: true
        default: |
          - name: instant_vector
            params:
              query: sum(rate(prometheus_http_requests_total[1m]))
            path: /api/v1/query
          - name: range_vector
            params:
              end: "2019-12-21T00:00:00.000Z"
              query: up
              start: "2019-12-20T00:00:00.000Z"
              step: 1h
            path: /api/v1/query_range
          - name: scalar
            params:
              query: "100"
            path: /api/v1/query
          - name: string
            params:
              query: some_value
            path: /api/v1/query
      - name: leaderelection
        type: bool
        title: Leader Election
        multi: false
        required: true
        show_user: false
        default: true
    title: Prometheus query metrics
    enabled: false
    description: Collect Prometheus query metrics
