rules:
  - path: /services/search/v2/jobs
    methods: ['POST']
    request_headers:
      Authorization:
        - "Basic dXNlcm5hbWU6cGFzc3dvcmQ="
    responses:
      - status_code: 201
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "sid": "test_sid"
          }
          `}}
  - path: /services/search/v2/jobs/test_sid
    methods: ['GET']
    query_params:
      output_mode: json
    request_headers:
      Authorization:
        - "Basic dXNlcm5hbWU6cGFzc3dvcmQ="
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "entry": [{"content":{"dispatchState": "DONE"}}]
          }
          `}}
  - path: /services/search/v2/jobs/test_sid/events
    methods: ['GET']
    query_params:
      count: 2
      offset: 2
      output_mode: json
    request_headers:
      Authorization:
        - "Basic dXNlcm5hbWU6cGFzc3dvcmQ="
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "preview": false,
            "init_offset": 0,
            "messages": [],
            "fields": [
              {
                "name": "_bkt"
              },
              {
                "name": "_cd"
              },
              {
                "name": "_indextime"
              },
              {
                "name": "_raw"
              },
              {
                "name": "_serial"
              },
              {
                "name": "_si"
              },
              {
                "name": "_sourcetype"
              },
              {
                "name": "_time"
              },
              {
                "name": "host"
              },
              {
                "name": "index"
              },
              {
                "name": "linecount"
              },
              {
                "name": "source"
              },
              {
                "name": "sourcetype"
              },
              {
                "name": "splunk_server"
              }
            ],
            "results": [
              {
                "_bkt": "notable~70~E10E99CE-2B29-4D28-B797-57BEABF6E876",
                "_cd": "70:13771",
                "_indextime": "1739168416",
                "_raw": "1739259266.000, search_name=\"Threat - Crowdstrike - Detection Found - Rule\", orig_time=\"1739259266.000\", action=\"blocked\", event.SeverityName=\"Low\", event.UserName=\"keval.sabhani\", file_hash=\"b9ef39e591886f5ea06521952ece1320e14928ddf4db440365babe3d410298c1\", file_name=\"go.exe\", file_path=\"\\\\Device\\\\HarddiskVolume3\\\\Program Files\\\\Go\\\\bin\\\\go.exe\", info_max_time=\"1739260620.000000000\", info_min_time=\"1739258820.000000000\", info_search_time=\"1739261221.082071000\"",
                "_serial": "476",
                "_si": [
                  "89.160.20.156",
                  "notable"
                ],
                "_sourcetype": "stash",
                "_time": "2025-02-12T13:37:05.000+05:30",
                "host": "89.160.20.156",
                "index": "notable",
                "linecount": "1",
                "source": "Threat - Crowdstrike - Detection Found - Rule",
                "sourcetype": "stash",
                "splunk_server": "89.160.20.156"
              }
            ],
            "highlighted": {}
          }
          `}}
  - path: /services/search/v2/jobs/test_sid/events
    methods: ['GET']
    query_params:
      count: 2
      offset: 0
      output_mode: json
    request_headers:
      Authorization:
        - "Basic dXNlcm5hbWU6cGFzc3dvcmQ="
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "preview": false,
            "init_offset": 0,
            "messages": [],
            "fields": [
              {
                "name": "_bkt"
              },
              {
                "name": "_cd"
              },
              {
                "name": "_indextime"
              },
              {
                "name": "_raw"
              },
              {
                "name": "_serial"
              },
              {
                "name": "_si"
              },
              {
                "name": "_sourcetype"
              },
              {
                "name": "_time"
              },
              {
                "name": "host"
              },
              {
                "name": "index"
              },
              {
                "name": "linecount"
              },
              {
                "name": "source"
              },
              {
                "name": "sourcetype"
              },
              {
                "name": "splunk_server"
              }
            ],
            "results": [
              {
                "_bkt": "notable~70~E10E99CE-2B29-4D28-B797-57BEABF6E876",
                "_cd": "70:13771",
                "_indextime": "1739168416",
                "_raw": "1739259266.000, search_name=\"Threat - Crowdstrike - Detection Found - Rule\", orig_time=\"1739259266.000\", action=\"blocked\", event.SeverityName=\"Low\", event.UserName=\"keval.sabhani\", file_hash=\"b9ef39e591886f5ea06521952ece1320e14928ddf4db440365babe3d410298c1\", file_name=\"go.exe\", file_path=\"\\\\Device\\\\HarddiskVolume3\\\\Program Files\\\\Go\\\\bin\\\\go.exe\", info_max_time=\"1739260620.000000000\", info_min_time=\"1739258820.000000000\", info_search_time=\"1739261221.082071000\"",
                "_serial": "476",
                "_si": [
                  "89.160.20.156",
                  "notable"
                ],
                "_sourcetype": "stash",
                "_time": "2025-02-11T13:37:05.000+05:30",
                "host": "89.160.20.156",
                "index": "notable",
                "linecount": "1",
                "source": "Threat - Crowdstrike - Detection Found - Rule",
                "sourcetype": "stash",
                "splunk_server": "89.160.20.156"
              },
              {
                "_bkt": "notable~70~E10E99CE-2B29-4D28-B797-57BEABF6E876",
                "_cd": "70:13771",
                "_indextime": "1739168416",
                "_raw": "1739168412, search_name=\"Access - Excessive Failed Logins - Rule\", app=\"ssl-web\", count=\"5\", ip=\"127.0.0.1\", dest_count=\"1\", info_max_time=\"1739168100.000000000\", info_min_time=\"1739164500.000000000\", info_search_time=\"1739168403.176027000\", src=\"89.160.20.112\", orig_tag=\"authentication\", orig_tag=\"default\", orig_tag=\"error\", orig_tag=\"failure\", user_count=\"1\"",
                "_serial": "476",
                "_si": [
                  "89.160.20.156",
                  "notable"
                ],
                "_sourcetype": "stash",
                "_time": "2025-02-10T11:50:16.000+05:30",
                "host": "89.160.20.156",
                "index": "notable",
                "linecount": "1",
                "source": "Access - Excessive Failed Logins - Rule",
                "sourcetype": "stash",
                "splunk_server": "89.160.20.156"
              }
            ],
            "highlighted": {}
          }
          `}}

  - path: /services/search/v2/jobs
    methods: ['POST']
    request_headers:
      Authorization:
        - "Basic c2VhcmNoX3VzZXI6cGFzc3dvcmQ="
    query_params:
      output_mode: json
      search: "search *"
    responses:
      - status_code: 201
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "sid": "1756080001.364431"
          }
          `}}
  - path: /services/search/v2/jobs/1756080001.364431
    methods: ['GET']
    query_params:
      output_mode: json
    request_headers:
      Authorization:
        - "Basic c2VhcmNoX3VzZXI6cGFzc3dvcmQ="
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "entry": [
              {
                "author": "search_user",
                "content": {
                  "dispatchState": "DONE"
                }
              }
            ]
          }
          `}}
  - path: /services/search/v2/jobs/1756080001.364431/events
    methods: ['GET']
    query_params:
      count: 2
      offset: 2
      output_mode: json
    request_headers:
      Authorization:
        - "Basic c2VhcmNoX3VzZXI6cGFzc3dvcmQ="
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "fields": [
              {
                "name": "_bkt"
              },
              {
                "name": "_cd"
              },
              {
                "name": "_indextime"
              },
              {
                "name": "_raw"
              },
              {
                "name": "_serial"
              },
              {
                "name": "_si"
              },
              {
                "name": "_sourcetype"
              },
              {
                "name": "_time"
              },
              {
                "name": "host"
              },
              {
                "name": "index"
              },
              {
                "name": "linecount"
              },
              {
                "name": "source"
              },
              {
                "name": "sourcetype"
              },
              {
                "name": "splunk_server"
              }
            ],
            "highlighted": {},
            "init_offset": 0,
            "messages": [],
            "preview": false,
            "results": [
              {
                "_bkt": "main~0~2cf47a7b-49fd-4166-a3eb-dead18b7e23a",
                "_cd": "0:10",
                "_indextime": "1740148016",
                "_raw": "02/21/2025 14:26:56 +0000, info_min_time=1740060000.000, info_max_time=1740148015.000, info_search_time=1740148015.943, field1=test",
                "_serial": "0",
                "_si": [
                  "ip-186-86-82-48",
                  "main"
                ],
                "_sourcetype": "stash",
                "_time": "2025-02-21T14:26:56.000+00:00",
                "host": "ip-186-86-82-48",
                "index": "main",
                "linecount": "1",
                "source": "/opt/splunk/var/spool/splunk/cafc46ad8c914957_a9876ea14cfe7ac8_events.stash_new",
                "sourcetype": "stash",
                "splunk_server": "ip-186-86-82-49"
              }
            ]
          }
          `}}
  - path: /services/search/v2/jobs/1756080001.364431/events
    methods: ['GET']
    query_params:
      count: 2
      offset: 0
      output_mode: json
    request_headers:
      Authorization:
        - "Basic c2VhcmNoX3VzZXI6cGFzc3dvcmQ="
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |-
          {{ minify_json `
          {
            "fields": [
              {
                "name": "_bkt"
              },
              {
                "name": "_cd"
              },
              {
                "name": "_indextime"
              },
              {
                "name": "_raw"
              },
              {
                "name": "_serial"
              },
              {
                "name": "_si"
              },
              {
                "name": "_sourcetype"
              },
              {
                "name": "_time"
              },
              {
                "name": "host"
              },
              {
                "name": "index"
              },
              {
                "name": "linecount"
              },
              {
                "name": "source"
              },
              {
                "name": "sourcetype"
              },
              {
                "name": "splunk_server"
              }
            ],
            "highlighted": {},
            "init_offset": 0,
            "messages": [],
            "preview": false,
            "results": [
              {
                "_bkt": "main~0~2cf47a7b-49fd-4166-a3eb-dead18b7e23a",
                "_cd": "0:10",
                "_indextime": "1740148017",
                "_raw": "02/21/2025 14:26:56 +0000, info_min_time=1740060000.000, info_max_time=1740148016.000, info_search_time=1740148016.943, field1=test, field2=test",
                "_serial": "0",
                "_si": [
                  "ip-186-86-82-48",
                  "main"
                ],
                "_sourcetype": "stash",
                "_time": "2025-02-21T14:26:57.000+00:00",
                "host": "ip-186-86-82-48",
                "index": "main",
                "linecount": "1",
                "source": "/opt/splunk/var/spool/splunk/cafc46ad8c914957_a9876ea14cfe7ac8_events.stash_new",
                "sourcetype": "stash",
                "splunk_server": "ip-186-86-82-49"
              },
              {
                "_bkt": "main~0~2cf47a7b-49fd-4166-a3eb-dead18b7e23a",
                "_cd": "0:10",
                "_indextime": "1740148018",
                "_raw": "02/21/2025 14:26:56 +0000, info_min_time=1740060000.000, info_max_time=1740148017.000, info_search_time=1740148017.943, field1=test, field2=test, field3=test",
                "_serial": "0",
                "_si": [
                  "ip-186-86-82-48",
                  "main"
                ],
                "_sourcetype": "stash",
                "_time": "2025-02-21T14:26:58.000+00:00",
                "host": "ip-186-86-82-48",
                "index": "main",
                "linecount": "1",
                "source": "/opt/splunk/var/spool/splunk/cafc46ad8c914957_a9876ea14cfe7ac8_events.stash_new",
                "sourcetype": "stash",
                "splunk_server": "ip-186-86-82-49"
              }
            ]
          }
          `}}
