---
description: Pipeline for parsing Traefik access logs.
processors:
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'
  - set:
      field: ecs.version
      value: '1.12.0'
  - rename:
      field: '@timestamp'
      target_field: event.created
      ignore_missing: true
  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
  - grok:
      field: event.original
      patterns:
        - ^%{CHAR:first_char}
      pattern_definitions:
        CHAR: .
  - pipeline:
      if: ctx.first_char != '{'
      name: '{{ IngestPipeline "format-common" }}'
  - pipeline:
      if: ctx.first_char == '{'
      name: '{{ IngestPipeline "format-json" }}'
  - remove:
      field:
        - first_char
  - remove:
      field: temp
      ignore_missing: true
  - user_agent:
      field: user_agent.original
      ignore_failure: true
  - geoip:
      field: source.ip
      target_field: source.geo
      ignore_missing: true
  - geoip:
      database_file: GeoLite2-ASN.mmdb
      field: source.ip
      target_field: source.as
      properties:
        - asn
        - organization_name
      ignore_missing: true
  - rename:
      field: source.as.asn
      target_field: source.as.number
      ignore_missing: true
  - rename:
      field: source.as.organization_name
      target_field: source.as.organization.name
      ignore_missing: true
  - set:
      field: event.kind
      value: event
  - append:
      field: event.category
      value: web
      allow_duplicates: false
      if: "ctx?.http?.request?.method != null && ctx.http.request.method != '-'"
  - append:
      field: event.type
      value: access
      allow_duplicates: false
      if: "ctx?.http?.request?.method != null && ctx.http.request.method != '-'"
  - set:
      field: event.outcome
      value: success
      if: "ctx?.http?.response?.status_code != null && ctx.http.response.status_code < 400"
  - set:
      field: event.outcome
      value: failure
      if: "ctx?.http?.response?.status_code != null && ctx.http.response.status_code >= 400"
  - append:
      field: related.ip
      value: "{{source.ip}}"
      allow_duplicates: false
      if: "ctx?.source?.ip != null"
  - append:
      field: related.ip
      value: "{{destination.ip}}"
      allow_duplicates: false
      if: "ctx?.destination?.ip != null"
  - append:
      field: related.user
      value: "{{user.name}}"
      allow_duplicates: false
      if: "ctx?.user?.name != null && ctx.user.name != '-'"
  - set:
      field: network.transport
      value: tcp
  - community_id:
      if: "ctx?.source?.ip != null && ctx?.source?.port != null && ctx?.destination?.ip != null && ctx?.destination?.ip != null"
  - remove:
      field: event.original
      if: "ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))"
      ignore_failure: true
      ignore_missing: true
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'