- name: data_stream.type
  external: ecs
- name: data_stream.dataset
  external: ecs
- name: data_stream.namespace
  external: ecs
- name: '@timestamp'
  external: ecs
- name: kubernetes
  type: group
  fields:
    - name: pod.name
      type: keyword
      description: >
        Kubernetes pod name

    - name: pod.uid
      dimension: true
      type: keyword
      description: >
        Kubernetes pod UID

    - name: pod.ip
      type: ip
      description: >
        Kubernetes pod IP

    - name: namespace
      type: keyword
      description: >
        Kubernetes namespace

    - name: namespace_uid
      type: keyword
      description: >
        Kubernetes namespace UID

    - name: node.name
      type: keyword
      description: >
        Kubernetes node name

    - name: node.hostname
      type: keyword
      description: >
        Kubernetes hostname as reported by the nodeâ€™s kernel

    - name: labels.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes labels map

    - name: annotations.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes annotations map

    - name: node.labels.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes node labels map

    - name: node.annotations.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes node annotations map

    - name: node.uid
      type: keyword
      description: >
        Kubernetes node UID

    - name: namespace_labels.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes namespace labels map

    - name: namespace_annotations.*
      type: object
      object_type: keyword
      object_type_mapping_type: "*"
      description: >
        Kubernetes namespace annotations map

    - name: replicaset.name
      type: keyword
      description: >
        Kubernetes replicaset name

    - name: deployment.name
      type: keyword
      description: >
        Kubernetes deployment name

    - name: daemonset.name
      type: keyword
      description: >
        Kubernetes daemonset name

    - name: statefulset.name
      type: keyword
      description: >
        Kubernetes statefulset name

    - name: job.name
      type: keyword
      description: >
        Name of the Job to which the Pod belongs

    - name: cronjob.name
      type: keyword
      description: >
        Name of the CronJob to which the Pod belongs

    - name: container.name
      type: keyword
      description: >
        Kubernetes container name

