version: '2.3'
services:
  haproxy-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  haproxy:
    image: docker.elastic.co/integrations-ci/beats-haproxy:${HAPROXY_VERSION:-2.8}-2
    build: .
    ports:
      - 14567
      - 14568
      - 14569
      - 14570
