- name: kubernetes.pod
  type: group
  fields:
    - name: ip
      type: ip
      description: |
        Kubernetes pod IP
    - name: host_ip
      type: ip
      description: |
        Kubernetes pod host IP
    - name: status
      type: group
      fields:
        - name: phase
          type: keyword
          description: |
            Kubernetes pod phase (Running, Pending...)
        - name: ready
          type: keyword
          description: |
            Kubernetes pod ready status (true, false or unknown)
        - name: scheduled
          type: keyword
          description: |
            Kubernetes pod scheduled status (true, false, unknown)
