version: '2.3'
services:
  azure-blob-storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000/tcp"
  azure-blob-storage:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command:
      - log
      - --retry=30
      - --addr=azure-blob-storage-emulator
      - -p=azureblobstorage
      - --azure-blob-storage-port=10000
      - --azure-blob-storage-container=azure-container1
      - /sample_logs/testdata.log
    depends_on:
      - azure-blob-storage-emulator
