version: '2.3'
services:
  redis_input_otel:
    image: redis:${SERVICE_VERSION:-7.2}-alpine
    build:
      context: .
      args:
        SERVICE_VERSION: ${SERVICE_VERSION:-7.2}
    ports:
      - 6379
