version: '2.3'
services:
  f5-bigipapm-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  f5-bigipapm-udp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9526 -p=udp /sample_logs/f5-bigipapm-*.log"
  f5-bigipapm-tcp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9526 -p=tcp /sample_logs/f5-bigipapm-*.log"
  f5-bigipafm-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  f5-bigipafm-udp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9544 -p=udp /sample_logs/f5-bigipafm-*.log"
  f5-bigipafm-tcp:
    image: akroh/stream:v0.0.1
    volumes:
      - ./sample_logs:/sample_logs:ro
    entrypoint: /bin/bash
    command: -c "/stream log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9544 -p=tcp /sample_logs/f5-bigipafm-*.log"
