version: '2.3'
services:
  forescout-event-tcp:
    image: docker.elastic.co/observability/stream:v0.20.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9532 -p=tcp /sample_logs/forescout-event.log
  forescout-event-udp:
    image: docker.elastic.co/observability/stream:v0.20.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9533 -p=udp /sample_logs/forescout-event.log
