version: "2.3"
services:
  assets:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/files/assets-config.yml
  events:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/files/events-config.yml
  system_log:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/files/system_log-config.yml
