version: '2.3'
services:
  iptables-log-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  iptables-log-udp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9514 -p=udp /sample_logs/iptables-syslog.log
  iptables-log-journald:
    build: .
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    # Use journalctl -o export _TRANSPORT=kernel -g "IN=" > iptables.journal.export
    # to write logs to journald export format. Then this creates a new binary journal
    # file from those logs to use in testing.
    command: /bin/sh -c "/lib/systemd/systemd-journal-remote -o /var/log/iptables.journal /sample_logs/*.export"
