rules:
  - path: /v1/payloads/recent/
    methods: ["GET"]
    request_headers:
      Content-Type: "application/json"
    responses:
      - status_code: 200
        body: |-
          {
            "query_status": "ok",
            "payloads": [{
                "md5_hash": "9cd5a4f0231a47823c4adba7c8ef370f",
                "sha256_hash": "7c0852d514df7faf8fdbfa4f358cc235dd1b1a2d843cc65495d03b502e4099f2",
                "file_type": "unknown",
                "file_size": "1563",
                "signature": null,
                "firstseen": "2021-10-05 04:17:02",
                "urlhaus_download": "https://urlhaus-api.abuse.ch/v1/download/7c0852d514df7faf8fdbfa4f358cc235dd1b1a2d843cc65495d03b502e4099f2/",
                "virustotal": null,
                "imphash": null,
                "ssdeep": "48:yazkS7neW+mfe4CJjNXcq5Co4Fr1PpsHn:yrmGNt5mbP2n",
                "tlsh": "T109314C5E7822CA70B91AD69300C22D8C2F53EAF229E6686C3BDD4C86FA1344208CF1"
              },
              {
                "md5_hash": "31da38bee299f10d40b307828239af98",
                "sha256_hash": "e1a5ef457aca7c27768917c8dfd9a0647799be2bd5185f61d889830e2ac4125d",
                "file_type": "unknown",
                "file_size": "1565",
                "signature": null,
                "firstseen": "2021-10-05 04:16:59",
                "urlhaus_download": "https://urlhaus-api.abuse.ch/v1/download/e1a5ef457aca7c27768917c8dfd9a0647799be2bd5185f61d889830e2ac4125d/",
                "virustotal": null,
                "imphash": null,
                "ssdeep": "24:SpbS988bp6qdsehrRASqw/VVyz9YhmqgcqiWHPsul0eGqa3gm4pwas6rx30ixN05:Spu16qS8v9hZqixul1GtvoRlkKy9O5k",
                "tlsh": "T165310A8254FCC87563EBCA5B7793F31B6219740961E3227A63B790CAA3458985C4F8"
              }
            ]
          }
  - path: /v1/urls/recent/
    methods: ["GET"]
    request_headers:
      Content-Type: "application/json"
    responses:
      - status_code: 200
        body: |-
          {
            "query_status": "ok",
            "urls": [{
                "id": "1656008",
                "urlhaus_reference": "https://urlhaus.abuse.ch/url/1656008/",
                "url": "http://120.85.169.98:55871/mozi.m",
                "url_status": "online",
                "host": "120.85.169.98",
                "date_added": "2021-10-05 13:57:05 UTC",
                "threat": "malware_download",
                "blacklists": {
                  "spamhaus_dbl": "not listed",
                  "surbl": "not listed"
                },
                "reporter": "tammeto",
                "larted": "true",
                "tags": null
              },
              {
                "id": "1656007",
                "urlhaus_reference": "https://urlhaus.abuse.ch/url/1656007/",
                "url": "http://59.40.83.17:42989/i",
                "url_status": "online",
                "host": "59.40.83.17",
                "date_added": "2021-10-05 13:54:10 UTC",
                "threat": "malware_download",
                "blacklists": {
                  "spamhaus_dbl": "not listed",
                  "surbl": "not listed"
                },
                "reporter": "geenensp",
                "larted": "true",
                "tags": [
                  "32-bit",
                  "elf",
                  "mips",
                  "Mozi"
                ]
              }
            ]
          }
  - path: /downloads/json
    methods: ["GET"]
    request_headers:
      Content-Type: ["application/zip"]
    responses:
      - status_code: 200
        body: |
          {{file "/files/urlhaus_full.json.zip"}}
  - path: /api/v1/
    methods: ["POST"]
    request_headers:
      Content-Type: "application/x-www-form-urlencoded"
    query_params:
      query: "get_recent"
      selector: "time"
    responses:
      - status_code: 200
        body: |-
          {
            "query_status": "ok",
            "data": [{
                "sha256_hash": "7a6c03013a2f2ab8b9e8e7e5d226ea89e75da72c1519e78fd28b2253ea755c28",
                "sha3_384_hash": "d63e73b68973bc73ab559549aeee2141a48b8a3724aabc0d81fb14603c163a098a5a10be9f6d33b888602906c0d89955",
                "sha1_hash": "42c7153680d7402e56fe022d1024aab49a9901a0",
                "md5_hash": "1fc1c2997c8f55ac10496b88e23f5320",
                "first_seen": "2021-10-05 14:02:45",
                "last_seen": null,
                "file_name": "7a6c03013a2f2ab8b9e8e7e5d226ea89e75da72c1519e.exe",
                "file_size": 432640,
                "file_type_mime": "application/x-dosexec",
                "file_type": "exe",
                "reporter": "abuse_ch",
                "origin_country": "FR",
                "anonymous": 0,
                "signature": "RedLineStealer",
                "imphash": "f34d5f2d4577ed6d9ceec516c1f5a744",
                "tlsh": "T13794242864BFC05994E3EEA12DDCA8FBD99A55E3640C743301B4633B8B52B84DE4F479",
                "telfhash": null,
                "ssdeep": "12288:jhhl1Eo+iEXvpb1C7drqAd1uUaJvzXGyO2F5V3bS1jsTacr:7lL",
                "dhash_icon": null,
                "tags": [
                  "exe",
                  "RedLineStealer"
                ],
                "code_sign": [],
                "intelligence": {
                  "clamav": null,
                  "downloads": "11",
                  "uploads": "1",
                  "mail": null
                }
              },
              {
                "sha256_hash": "670e59f677706e51b84984f42f8f89229e294e4c482dfa4fc72964def42a3626",
                "sha3_384_hash": "60b388f9e2d0e24328af41421cc71f6cf097a432b7393e122c1f2103a4be0c1f1ab8b3e0a61a4393ac4eb27716e4bab2",
                "sha1_hash": "47da737c89777cd1d08c5427d08ec3e77ef0da2c",
                "md5_hash": "657edf01cd9100a52abd7a9d8e585a28",
                "first_seen": "2021-10-05 14:00:50",
                "last_seen": null,
                "file_name": "657edf01cd9100a52abd7a9d8e585a28",
                "file_size": 414720,
                "file_type_mime": "application/x-dosexec",
                "file_type": "exe",
                "reporter": "zbetcheckin",
                "origin_country": "FR",
                "anonymous": 0,
                "signature": "Loki",
                "imphash": "f34d5f2d4577ed6d9ceec516c1f5a744",
                "tlsh": "T1C7949D69322F5917CE288EF5185EA1C183F90C3B155AE7E85DCAF1FA65C3FB01A81493",
                "telfhash": null,
                "ssdeep": "6144:FQq8qc0WpMge4UPvaMmdtq1a/tZFJYhVFyWpEGDNi0x7ynZPppgjQ+3HwO/A:FQq8qc0WfqaFq8tfJWVFL1Ri0x453o4",
                "dhash_icon": null,
                "tags": [
                  "32",
                  "exe",
                  "Loki",
                  "trojan"
                ],
                "code_sign": [],
                "intelligence": {
                  "clamav": null,
                  "downloads": "11",
                  "uploads": "1",
                  "mail": null
                }
              }
            ]
          }
