fields:
  - name: timestamp
    period: -24h
  - name: loggedDateTime
    period: -24h
  - name: loggedUser
    cardinality: 100
  - name: loggedRole
    enum:
      - Master Administrator
      - Operator
      - Auditor
      - Analyst
  - name: accessType
    enum:
      - Console
      - API
  - name: category
    enum:
      - Logon and Logoff
      - Product Connector
      - Account Management
      - Notifications
      - Detection Model Management
      - Workbench
      - Response Management
      - Search
      - Managed XDR
      - Endpoint Inventory
      - Endpoint Policies
      - API Keys
      - Console Settings
  - name: activity
    cardinality: 1000
  - name: result
    enum:
      - Successful
      - Unsuccessful
  - name: detailKey
    cardinality: 100
  - name: detailValue
    cardinality: 1000
