version: '2.3'
services:
  cylance-protect-logfile:
    image: alpine
    volumes:
      - ./sample_logs:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/* /var/log/"
  cylance-protect-udp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9529 -p=udp /sample_logs/cylance-protect-*.log
  cylance-protect-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9529 -p=tcp /sample_logs/cylance-protect-*.log
