fields:
  - name: added_at
    period: -24h
  - name: classification
    enum:
      - "private"
      - "public"
  - name: confidence
    cardinality: 100
  - name: country
    enum:
      - US
      - DE
      - IN
      - VS
      - RU
  - name: date_first
    period: -24h
  - name: date_last
    period: -24h
  - name: detail2
    enum:
      - imported by user 1
      - imported by user 710
  - name: id
    cardinality: 1000000
  - name: import_session_id
    cardinality: 1000000
  - name: itype
    enum:
      - mal_md5
      - phish_url
      - scan_ip
      - mal_url
      - mal_domain
  - name: lat
    cardinality: 100
  - name: lon
    cardinality: 100
  - name: org
    enum:
      - Example Org
      - Test Organization
  - name: resource_uri
    enum:
      - /api/v1/intelligence/P29675942316/
      - /api/v1/intelligence/22222/
      - /api/v1/intelligence/111111/
  - name: severity
    enum:
      - very-high
      - high
      - medium
      - low
  - name: source
    enum:
      - Default Organization
      - Phony generated indicator
  - name: source_feed_id
    cardinality: 1000000
  - name: state
    enum: 
      - active
      - inactive
  - name: trusted_circle_ids
    cardinality: 1000000
  - name: update_id
    cardinality: 1000000
  - name: value_type
    enum:
      - url
      - ip
      - domain
