title: "Kubernetes container logs"
type: logs
dataset: kubernetes.container_logs
streams:
  - input: filestream
    title: Collect Kubernetes container logs
    description: Collect Kubernetes container logs
    vars:
      - name: paths
        type: text
        required: true
        title: Kubernetes container log path
        multi: true
        default:
          - /var/log/containers/*${kubernetes.container.id}.log
      - name: symlinks
        type: bool
        title: Use Symlinks
        multi: false
        required: true
        show_user: true
        default: true
      - name: data_stream.dataset
        required: true
        default: kubernetes.container_logs
        title: Dataset name
        description: >
          Set the name for your dataset. Changing the dataset will send the data to a different index. For more info look at [data_stream field](https://www.elastic.co/guide/en/ecs/master/ecs-data_stream.html).

        type: text
      - name: containerParserStream
        type: text
        title: Container parser's stream configuration
        multi: false
        required: true
        default: all
      - name: containerParserFormat
        type: text
        title: Container parser's format configuration
        multi: false
        required: true
        default: auto
      - name: condition
        title: Condition
        description: Condition to filter when to apply this datastream. Refer to [Kubernetes provider](http://localhost:8000/guide/providers.html#kubernetes-provider) to find the available keys and to [Conditions](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html#conditions) on how to use the available keys in conditions.
        type: text
        multi: false
        required: false
        show_user: true
      - name: additionalParsersConfig
        type: yaml
        title: Additional parsers configuration
        multi: false
        required: true
        default: |
          # - ndjson:
          #     target: json
          #     ignore_decoding_error: true
          # - multiline:
          #     type: pattern
          #     pattern: '^\['
          #     negate: true
          #     match: after
      - name: processors
        type: yaml
        title: Processors
        multi: false
        required: false
        show_user: false
        description: >-
          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the events are shipped. See [Processors](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) for details.
      - name: custom
        title: Custom configurations
        show_user: false
        description: >
          Here YAML configuration options can be used to be added to your configuration. Be careful using this as it might break your configuration file.

        type: yaml
        default: ""
# Ensures agents have permissions to write data to `logs-*-*`
elasticsearch:
  dynamic_dataset: true
  dynamic_namespace: true
