version: '2.3'
services:
  panw-cortex-xdr-mock:
    image: docker.elastic.co/observability/stream:v0.15.0
    ports:
      - 8080
    volumes:
      - ./http-mock-config.yml:/config.yml
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/config.yml
