rules:
  - path: /public_api/v1/alerts/get_alerts_multi_events
    methods: [POST]
    request_headers:
      Authorization: testing-token
      X-Xdr-Auth-Id: 1
    request_body: '/.*/'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json"
        body: |-
          {
             "reply":{
                "total_count":45,
                "result_count":1,
                "alerts":[
                   {
                      "external_id":"800800",
                      "severity":"high",
                      "matching_status":"FAILED",
                      "end_match_attempt_ts":1603552062824,
                      "local_insert_ts":1603279967500,
                      "bioc_indicator":null,
                      "matching_service_rule_id":null,
                      "attempt_counter":55,
                      "bioc_category_enum_key":null,
                      "is_whitelisted":false,
                      "starred":false,
                      "deduplicate_tokens":null,
                      "filter_rule_id":null,
                      "mitre_technique_id_and_name":[
                         ""
                      ],
                      "mitre_tactic_id_and_name":[
                         ""
                      ],
                      "agent_version":"1.2.3.4",
                      "agent_device_domain":null,
                      "agent_fqdn":"test",
                      "agent_os_type":"Windows",
                      "agent_os_sub_type":"XP",
                      "agent_data_collection_status":true,
                      "mac":null,
                      "mac_address": [
                         "00:11:22:33:44:55"
                      ],
                      "agent_is_vdi": null,
                      "events":[
                         {
                            "agent_install_type":"NA",
                            "agent_host_boot_time":null,
                            "event_sub_type":null,
                            "module_id":"Privilege Escalation Protection",
                            "association_strength":null,
                            "dst_association_strength":null,
                            "story_id":null,
                            "event_id":null,
                            "event_type":"Process Execution",
                            "event_timestamp":1603279888980,
                            "actor_process_instance_id":"1234",
                            "actor_process_image_path":"c:\\tmp\\virus.exe",
                            "actor_process_image_name":"virus.exe",
                            "actor_process_command_line":"c:\\tmp\\virus.exe",
                            "actor_process_signature_status":"N/A",
                            "actor_process_signature_vendor":null,
                            "actor_process_image_sha256":"133ee989293f92736301280c6f14c89d521200c17dcdcecca30cd20705332d44",
                            "actor_process_image_md5":null,
                            "actor_process_causality_id":null,
                            "actor_causality_id":null,
                            "actor_process_os_pid":1234,
                            "actor_thread_thread_id":null,
                            "causality_actor_process_image_name":null,
                            "causality_actor_process_command_line":null,
                            "causality_actor_process_image_path":null,
                            "causality_actor_process_signature_vendor":null,
                            "causality_actor_process_signature_status":"N/A",
                            "causality_actor_causality_id":null,
                            "causality_actor_process_execution_time":null,
                            "causality_actor_process_image_md5":null,
                            "causality_actor_process_image_sha256":null,
                            "action_file_path":null,
                            "action_file_name":null,
                            "action_file_md5":null,
                            "action_file_sha256":null,
                            "action_file_macro_sha256":null,
                            "action_registry_data":null,
                            "action_registry_key_name":null,
                            "action_registry_value_name":null,
                            "action_registry_full_key":null,
                            "action_local_ip":null,
                            "action_local_port":null,
                            "action_remote_ip":null,
                            "action_remote_port":null,
                            "action_external_hostname":null,
                            "action_country":"UNKNOWN",
                            "action_process_instance_id":null,
                            "action_process_causality_id":null,
                            "action_process_image_name":null,
                            "action_process_image_sha256":null,
                            "action_process_image_command_line":null,
                            "action_process_signature_status":"N/A",
                            "action_process_signature_vendor":null,
                            "os_actor_effective_username":null,
                            "os_actor_process_instance_id":null,
                            "os_actor_process_image_path":null,
                            "os_actor_process_image_name":null,
                            "os_actor_process_command_line":null,
                            "os_actor_process_signature_status":"N/A",
                            "os_actor_process_signature_vendor":null,
                            "os_actor_process_image_sha256":null,
                            "os_actor_process_causality_id":null,
                            "os_actor_causality_id":null,
                            "os_actor_process_os_pid":null,
                            "os_actor_thread_thread_id":null,
                            "fw_app_id":null,
                            "fw_interface_from":null,
                            "fw_interface_to":null,
                            "fw_rule":null,
                            "fw_rule_id":null,
                            "fw_device_name":null,
                            "fw_serial_number":null,
                            "fw_url_domain":null,
                            "fw_email_subject":null,
                            "fw_email_sender":null,
                            "fw_email_recipient":null,
                            "fw_app_subcategory":null,
                            "fw_app_category":null,
                            "fw_app_technology":null,
                            "fw_vsys":null,
                            "fw_xff":null,
                            "fw_misc":null,
                            "fw_is_phishing":"N/A",
                            "dst_agent_id":null,
                            "dst_causality_actor_process_execution_time":null,
                            "dns_query_name":null,
                            "dst_action_external_hostname":null,
                            "dst_action_country":null,
                            "dst_action_external_port":null,
                            "user_name":null
                         }
                      ],
                      "alert_id":"1001",
                      "detection_timestamp":1603279888980,
                      "name":"Kernel Privilege Escalation",
                      "category":"Exploit",
                      "endpoint_id":"12345678",
                      "description":"Local privilege escalation prevented",
                      "host_ip":[
                         "10.0.255.20"
                      ],
                      "host_name":"Test",
                      "source":"XDR Agent",
                      "action":"BLOCKED",
                      "action_pretty":"Prevented (Blocked)"
                   }
                ]
             }
          }
  - path: /public_api/v1/incidents/get_incidents
    methods:
      - POST
    request_headers:
      Authorization: testing-token
      X-Xdr-Auth-Id: 1
    request_body: /.*/
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - application/json
        body: |-
          {
            "reply": {
            "total_count": 390,
            "result_count": 1,
            "incidents": [
                {
                  "incident_id": "893",
                  "incident_name": null,
                  "creation_time": 1691976000230,
                  "modification_time": 1691976000230,
                  "detection_time": null,
                  "status": "new",
                  "severity": "low",
                  "description": "'Large Upload (Generic)' generated by XDR Analytics detected on host test1234 involving user nt authority\\system",
                  "assigned_user_mail": null,
                  "assigned_user_pretty_name": null,
                  "alert_count": 1,
                  "low_severity_alert_count": 1,
                  "med_severity_alert_count": 0,
                  "high_severity_alert_count": 0,
                  "critical_severity_alert_count": 0,
                  "user_count": 1,
                  "host_count": 1,
                  "notes": null,
                  "resolve_comment": null,
                  "resolved_timestamp": null,
                  "manual_severity": null,
                  "manual_description": null,
                  "xdr_url": "https://test.xdr.eu.paloaltonetworks.com/incident-view?caseId=893",
                  "starred": false,
                  "hosts": [
                      "test1234:b567c1a651e66999158aef5d864dad25"
                  ],
                  "users": [
                      "nt authority\\system"
                  ],
                  "incident_sources": [
                      "XDR Analytics"
                  ],
                  "rule_based_score": null,
                  "predicted_score": 5,
                  "manual_score": null,
                  "aggregated_score": 5,
                  "wildfire_hits": 0,
                  "alerts_grouping_status": "Enabled",
                  "mitre_tactics_ids_and_names": [
                      "TA0010 - Exfiltration"
                  ],
                  "mitre_techniques_ids_and_names": [
                      "T1048 - Exfiltration Over Alternative Protocol"
                  ],
                  "alert_categories": [
                      "Exfiltration"
                  ],
                  "original_tags": [
                      "DS:PANW/XDR Agent",
                      "EG:win-server-ex-ransomeware_report",
                      "EG:win-server-default"
                  ],
                  "tags": [
                      "DS:PANW/XDR Agent",
                      "EG:win-server-default",
                      "EG:win-server-ex-ransomeware_report"
                  ]
                }
            ],
            "restricted_incident_ids": []
            }
          }
