- name: docker.info
  type: group
  release: ga
  fields:
    - name: containers
      type: group
      fields:
        - name: paused
          type: long
          description: |
            Total number of paused containers.
        - name: running
          type: long
          description: |
            Total number of running containers.
        - name: stopped
          type: long
          description: |
            Total number of stopped containers.
        - name: total
          type: long
          description: |
            Total number of existing containers.
    - name: id
      type: keyword
      description: |
        Unique Docker host identifier.
    - name: images
      type: long
      description: |
        Total number of existing images.
