fields:
  - name: act
    enum:
      - Clean
      - Block
      - not blocked
      - Quarantine
      - Delete
  - name: actResult
    enum:
      - Quarantined successfully
      - Unable to clean file
      - Blocked
      - Deleted
  - name: app
    enum:
      - HTTP
      - HTTPS
      - KERBEROS
      - TCP
      - SMB
      - SMB2
      - DCE-RPC
      - LDAP
      - DNS Response
      - FTP
  - name: appGroup
    enum:
      - HTTP
      - AUTH
      - CIFS
      - TCP
      - LDAP
      - DNS Response
      - FTP
  - name: behaviorCat
    enum:
      - Grey-Detection
      - Malware
      - Suspicious
  - name: blocking
    enum:
      - Web reputation
      - File reputation
      - Behavior monitoring
  - name: cat
    range:
      min: 1
      max: 100
  - name: detectionType
    enum:
      - File
      - Web Reputation Service
      - Behavior Monitoring
      - Network
  - name: deviceDirection
    enum:
      - inbound
      - outbound
      - unknown
  - name: deviceGUID
    cardinality: 10000
  - name: dpt
    range:
      min: 1
      max: 65535
    cardinality: 1000
  - name: dst
    cardinality: 10000
  - name: endpointGUID
    cardinality: 10000
  - name: endpointHostName
    cardinality: 10000
  - name: endpointIp
    cardinality: 10000
  - name: eventId
    cardinality: 100
  - name: eventName
    enum:
      - INTEGRITY_MONITORING_EVENT
      - SECURITY_RISK_DETECTION
      - WEB_POLICY_VIOLATION
      - MESSAGE_SUSPICIOUS_DETECTION
  - name: eventSubName
    enum:
      - Attack Discovery
      - Malware Detection
      - Web Reputation
  - name: eventTime
    range:
      min: 1735689600000
      max: 1771977600000
  - name: eventTimeDT
    period: -24h
  - name: fileHash
    cardinality: 100000
  - name: fileName
    cardinality: 10000
  - name: fileSize
    range:
      min: 0
      max: 10000000
  - name: hostName
    cardinality: 10000
  - name: malName
    cardinality: 1000
  - name: malType
    enum:
      - Virus/Malware
      - Spyware/Grayware
      - OTHERS
      - Trojan
  - name: objectCmd
    cardinality: 10000
  - name: objectFileHashSha1
    cardinality: 100000
  - name: objectFileHashSha256
    cardinality: 100000
  - name: objectFilePath
    cardinality: 10000
  - name: objectName
    cardinality: 10000
  - name: pname
    enum:
      - Apex One
      - Deep Discovery Inspector
      - Secure Web Gateway
      - Cloud One - Workload Security
      - Email Sensor
  - name: processCmd
    cardinality: 10000
  - name: processFileHashSha1
    cardinality: 100000
  - name: processFileHashSha256
    cardinality: 100000
  - name: processFilePath
    cardinality: 10000
  - name: processName
    cardinality: 1000
  - name: productCode
    enum:
      - sao
      - pdi
      - sig
      - xms
  - name: pver
    cardinality: 100
  - name: request
    cardinality: 100000
  - name: rt
    period: -24h
  - name: searchDL
    enum:
      - DDL
  - name: severity
    range:
      min: 1
      max: 10
  - name: spt
    range:
      min: 1024
      max: 65535
    cardinality: 10000
  - name: src
    cardinality: 10000
  - name: tags
    enum:
      - XSAE.F2140
      - XSAE.F3066
      - MITRE.T1090
      - MITRE.T1566.002
  - name: uuid
    cardinality: 100000
