- external: ecs
  name: ecs.version
- external: ecs
  name: service.address
- external: ecs
  name: service.type
- external: ecs
  name: container.id
- external: ecs
  name: container.name
- external: ecs
  name: container.runtime
- external: ecs
  name: container.image.name
- external: ecs
  name: host
- external: ecs
  name: host.architecture
- external: ecs
  name: host.ip
- external: ecs
  name: host.mac
- external: ecs
  name: host.name
- external: ecs
  name: host.os.family
- external: ecs
  name: host.os.full
- external: ecs
  name: host.os.kernel
- external: ecs
  name: host.os.name
- external: ecs
  name: host.os.platform
- external: ecs
  name: host.os.version
- external: ecs
  name: host.type
- name: container.network.egress.bytes
  type: long
  format: bytes
  metric_type: counter
  description: |
    Total number of outgoing bytes.
- name: container.network.ingress.bytes
  type: long
  format: bytes
  metric_type: counter
  description: |
    Total number of incoming bytes.
