- name: docker.container.labels.*
  type: object
  release: ga
  description: |
    Container labels
- name: docker.network
  type: group
  release: ga
  fields:
    - name: interface
      type: keyword
      description: |
        Network interface name.
    - name: inbound
      type: group
      fields:
        - name: bytes
          type: long
          format: bytes
          metric_type: counter
          description: |
            Total number of incoming bytes.
        - name: dropped
          type: long
          metric_type: counter
          description: |
            Total number of dropped incoming packets.
        - name: errors
          type: long
          metric_type: counter
          description: |
            Total errors on incoming packets.
        - name: packets
          type: long
          metric_type: counter
          description: |
            Total number of incoming packets.
    - name: outbound
      type: group
      fields:
        - name: bytes
          type: long
          format: bytes
          metric_type: counter
          description: |
            Total number of outgoing bytes.
        - name: dropped
          type: long
          metric_type: counter
          description: |
            Total number of dropped outgoing packets.
        - name: errors
          type: long
          metric_type: counter
          description: |
            Total errors on outgoing packets.
        - name: packets
          type: long
          metric_type: counter
          description: |
            Total number of outgoing packets.
