- name: prometheus
  type: group
  fields:
    - name: labels.*
      type: object
      object_type: keyword
      description: |
        Prometheus metric labels
    - name: metrics.*
      type: object
      object_type: double
      object_type_mapping_type: "*"
      description: |
        Prometheus metric
- name: prometheus.*.value
  type: object
  object_type: double
  object_type_mapping_type: "*"
  description: >
    Prometheus gauge metric

- name: prometheus.*.counter
  type: object
  object_type: double
  object_type_mapping_type: "*"
  description: >
    Prometheus counter metric

- name: prometheus.*.rate
  type: object
  object_type: double
  object_type_mapping_type: "*"
  description: >
    Prometheus rated counter metric

- name: prometheus.*.histogram
  type: object
  object_type: histogram
  object_type_mapping_type: "*"
  description: >
    Prometheus histogram metric

