version: '2.3'
services:
  kafka-service:
    image: bashj79/kafka-kraft
    healthcheck:
      test: nc -z kafka-service 9094 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    hostname: kafka-service
    environment:
      KAFKA_LISTENERS: "INTERNAL://kafka-service:9092,EXTERNAL://:9094, CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-service:9092,EXTERNAL://kafka-service:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 9094
  kafka-generic:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command:
      - log
      - --retry=30
      - --addr=kafka-service:9094
      - -p=kafka
      - --kafka-topic=testTopic
      - /sample_logs/testdata.log
    depends_on:
      kafka-service:
        condition: service_healthy
