rules:
  - path: /test/api
    methods: [GET]
    responses:
      - status_code: 200
        body: |
          {"message": "success"}
  - path: /testoauth/token
    #basic authentication is not supported until 8.7.1:
    # - path: /testbasicauth/api
    #   methods: [GET]
    #   request_headers:
    #     Authorization: "Basic dGVzdDp0ZXN0"
    #   responses:
    #     - status_code: 200
    #       body: |
    #         {"message": "success"}
    #
    #Associated test: add as data_stream/generic/_dev/test/system:
    # input: cel
    # service: cel
    # data_stream:
    #   vars:
    #     data_stream.dataset: cel.generic
    #     username: test
    #     password: test
    #     resource_url: http://{{Hostname}}:{{Port}}/testbasicauth/api
    #     program: |
    #       bytes(get(state.url).Body).as(body, {"events": [body.decode_json()]})

    methods: [POST]
    query_params:
      grant_type: client_credentials
    request_headers:
      Content-Type:
        - application/x-www-form-urlencoded
      Authorization:
        - "Basic dGVzdDp0ZXN0"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json"
        body: |-
          {"access_token": "testaccess","token_type": "Bearer","expires_in": 172799,"refresh_token": "testrefresh"}
  - path: /testoauth/scopedtoken
    methods: [POST]
    query_params:
      scope: token_scope
    request_headers:
      Content-Type:
        - application/x-www-form-urlencoded
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - "application/json"
        body: |-
          {"access_token": "testaccess","token_type": "Bearer","expires_in": 172799,"refresh_token": "testrefresh"}
  - path: /testoauth/api
    methods: [GET]
    request_headers:
      Authorization: "Bearer testaccess"
    responses:
      - status_code: 200
        body: |-
          {"message": "success"}
