version: '2.3'
services:
  statsd_input:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:8125 -p=udp /sample_logs/test-statsd.log
