version: "2.3"
services:
  jamf-protect-telemetry-legacy-http-endpoint:
    image: docker.elastic.co/observability/stream:v0.20.0
    volumes:
    - ./sample_logs:/sample_logs:ro
    environment:
    - STREAM_PROTOCOL=webhook
    - STREAM_WEBHOOK_PROBE=false
    - STREAM_ADDR=http://elastic-agent:9555/
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/telemetry-legacy.log
