version: '2.3'
services:
  vsphere-metrics:
    image: docker.elastic.co/integrations-ci/beats-vsphere:${VSPHERE_GOLANG_VERSION:-1.17}-1
    build:
      context: .
      args:
        VSPHERE_GOLANG_VERSION: ${VSPHERE_GOLANG_VERSION:-1.17}
    ports:
      - 8989
  vsphere-log-udp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9514 -p=udp /sample_logs/syslog.log
  vsphere-log-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_logs:/sample_logs:ro
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9515 -p=tcp /sample_logs/syslog.log
