---
description: Benchmark 100000 application_risk events ingested
input: cel
vars:
  url: http://{{Hostname}}:{{Port}}
  api_token: xxxx
data_stream:
  name: application_risk
  vars:
    enable_request_tracer: true
    preserve_original_event: true
warmup_time_period: 2s
corpora:
  input_service:
    name: sentinel_one
  generator:
    total_events: 10000
    template:
      path: ./application_risk-benchmark/template.ndjson
      type: gotext
    config:
      path: ./application_risk-benchmark/config.yml
    fields:
      path: ./application_risk-benchmark/fields.yml
