fields:
  - name: endpointHostName
    cardinality: 10000
  - name: customerId
    cardinality: 100
  - name: osName
    enum:
      - Windows 10
      - Windows 11
      - Windows Server 2022
      - macOS Sonoma
      - Ubuntu 22.04
  - name: dst
    cardinality: 10000
  - name: endpointGuid
    cardinality: 10000
  - name: principalName
    cardinality: 10000
  - name: request
    cardinality: 100000
  - name: act
    range:
      min: 1
      max: 10
  - name: src
    cardinality: 10000
  - name: serverTls
    enum:
      - TLS 1.2
      - TLS 1.3
  - name: eventTime
    range:
      min: 1735689600000
      max: 1771977600000
  - name: serverProtocol
    enum:
      - HTTP/1.1
      - HTTP/2
  - name: userAgent
    cardinality: 1000
  - name: rt
    range:
      min: 1600000000
      max: 1800000000
  - name: tenantGuid
    cardinality: 100
  - name: eventName
    enum:
      - SWG_ACTIVITY_LOG
  - name: application
    cardinality: 1000
  - name: ruleName
    cardinality: 1000
  - name: clientIp
    cardinality: 10000
  - name: requestBase
    cardinality: 10000
  - name: score
    range:
      min: 0
      max: 100
  - name: userDomain
    cardinality: 1000
  - name: suid
    cardinality: 10000
  - name: duration
    range:
      min: 1
      max: 3600
  - name: eventSubName
    cardinality: 1000
  - name: fileHash
    cardinality: 100000
  - name: fileHashSha256
    cardinality: 100000
  - name: fileName
    cardinality: 10000
  - name: fileSize
    range:
      min: 0
      max: 100000000
  - name: fileType
    enum:
      - Microsoft Excel
      - Adobe PDF
      - Windows Executable
      - ASCII Text
      - HTML
  - name: sender
    enum:
      - Corporate Gateway
      - Remote VPN Gateway
      - Internal Gateway
  - name: detectionType
    range:
      min: 0
      max: 100
  - name: profile
    enum:
      - standard
      - dlp_strict
      - threat_protection
      - api_default
  - name: userDepartment
    enum:
      - Finance
      - Sales
      - HR
      - IT
      - Engineering
  - name: requestMethod
    enum:
      - GET
      - POST
      - PUT
      - DELETE
  - name: pname
    cardinality: 100
  - name: pver
    cardinality: 100
  - name: deviceGUID
    cardinality: 10000
  - name: ruleType
    enum:
      - access
      - dlp
      - threat
  - name: ruleUuid
    cardinality: 10000
  - name: spt
    range:
      min: 1024
      max: 65535
    cardinality: 10000
  - name: dpt
    range:
      min: 1
      max: 65535
    cardinality: 1000
  - name: policyUuid
    cardinality: 1000
  - name: companyName
    cardinality: 100
