fields:
  - name: timestamp
    period: -24h # one day
  - name: duration_start
    enum: 
      - "-1h"
      - "-2h"
      - "-3h"
  - name: filesize
    range:
      min: 1
      max: 99999999
  - name: filetype
    enum: 
      - "html"
      - "elf"
      - "unknown"
      - "json"
      - "txt"
      - "sh"
      - "powershell"
  - name: imp_hash
    cardinality: 100000
  - name: md5_hash
    cardinality: 100000
  - name: sha256_hash
    cardinality: 100000
  - name: signature
    cardinality: 1000
  - name: ssdeep
    cardinality: 100000
  - name: tlsh
    cardinality: 100000
  - name: virustotal.percent
    range:
      min: 0.0
      max: 99.99
  - name: virustotal.detection_id
    cardinality: 1000
  - name: virustotal.result_num
    range:
      min: 1
      max: 50
  - name: virustotal.result_den
    range:
      min: 51
      max: 100
