fields:
  - name: dpt
    range:
      min: 1
      max: 65535
    cardinality: 1000
  - name: dst
    cardinality: 10000
  - name: endpointGuid
    cardinality: 10000
  - name: endpointHostName
    cardinality: 10000
  - name: endpointIp
    cardinality: 10000
  - name: eventId
    enum:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
  - name: eventSubId
    enum:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "101"
      - "102"
      - "103"
      - "104"
      - "105"
      - "106"
      - "107"
      - "108"
      - "109"
      - "201"
      - "202"
      - "203"
      - "204"
      - "301"
      - "401"
      - "402"
      - "403"
      - "404"
      - "501"
      - "502"
      - "503"
      - "504"
      - "601"
      - "602"
      - "603"
      - "701"
      - "702"
      - "703"
      - "704"
      - "705"
      - "801"
      - "901"
      - "1001"
      - "1002"
      - "1003"
      - "1101"
      - "1102"
  - name: eventTime
    range:
      min: 1735689600000
      max: 1771977600000
  - name: eventTimeDT
    period: -24h
  - name: hostName
    cardinality: 10000
  - name: logonUser
    cardinality: 10000
  - name: objectCmd
    cardinality: 10000
  - name: objectFileHashSha1
    cardinality: 100000
  - name: objectFilePath
    cardinality: 10000
  - name: objectHostName
    cardinality: 10000
  - name: objectIntegrityLevel
    enum:
      - "0"
      - "4096"
      - "8192"
      - "12288"
      - "16384"
  - name: objectIp
    cardinality: 10000
  - name: objectPort
    range:
      min: 1
      max: 65535
  - name: objectRegistryData
    cardinality: 10000
  - name: objectRegistryKeyHandle
    cardinality: 1000
  - name: objectRegistryValue
    cardinality: 1000
  - name: objectSigner
    enum:
      - Microsoft Windows
      - Google LLC
      - OpenBSD Project
      - Mozilla Corporation
  - name: objectUser
    cardinality: 10000
  - name: os
    enum:
      - Windows 10
      - Windows 11
      - Windows Server 2019
      - Windows Server 2022
  - name: parentCmd
    cardinality: 10000
  - name: parentFileHashSha1
    cardinality: 100000
  - name: parentFilePath
    cardinality: 10000
  - name: processCmd
    cardinality: 10000
  - name: processFileHashSha1
    cardinality: 100000
  - name: processFilePath
    cardinality: 10000
  - name: request
    cardinality: 100000
  - name: searchDL
    enum:
      - EDR
      - XDR
      - SDL
  - name: spt
    range:
      min: 1024
      max: 65535
    cardinality: 10000
  - name: src
    cardinality: 10000
  - name: srcFileHashSha1
    cardinality: 100000
  - name: srcFilePath
    cardinality: 10000
  - name: tags
    enum:
      - MITRE.T1059.001
      - MITRE.T1021.004
      - MITRE.T1071.001
      - XSAE.F1001
      - XSAE.F2003
  - name: uuid
    cardinality: 100000
