version: '3.0'
services:
  tines_api_mock:
    image: docker.elastic.co/observability/stream:v0.15.0
    hostname: tines_api_mock
    ports:
      - 8080
    volumes:
      - ./config.yml:/config.yml
    environment:
      PORT: "8080"
    command:
      - http-server
      - --addr=:8080
      - --config=/config.yml
