# newer versions go on top
- version: "0.1.0"
  changes:
    - description: Initial draft of the package with Guided and Raw Config modes
      type: enhancement
      link: https://github.com/elastic/integrations/pull/17117
