fields:
  - name: ListItemUniqueId
    cardinality: 10000
  - name: Id
    range:
      min: 100000000000000000
      max: 999999999999999999
      cardinality: 1000000
  - name: ObjectId
    cardinality: 10000
  - name: Operation
    enum:
      - Add app role assignment to service principal.
      - Add OAuth2PermissionGrant.
      - Consent to application.
      - Add app role assignment grant to user.
      - Update application.
  - name: OrganizationId
    cardinality: 10000
  - name: RecordType
    range:
      min: 1
      max: 181
      cardinality: 100
  - name: UserId
    enum:
      - asr@testsiem.onmicrosoft.com
      - bsr@testsiem.onmicrosoft.com
  - name: UserKey
    enum:
      - 1003200096971F55@testsiem.onmicrosoft.com
      - 1003200096971F56@testsiem.onmicrosoft.com
  - name: UserType
    range:
      min: 1
      max: 9
      cardinality: 10
  - name: Version
    range:
      min: 1
      max: 5
      cardinality: 10
  - name: Workload
    enum:
      - ExchangeAdmin
      - ExchangeItem
      - ExchangeItemGroup
      - SharePoint
      - SharePointFileOperation
      - OneDrive
      - AzureActiveDirectory
      - AzureActiveDirectoryAccountLogon
      - DataCenterSecurityCmdlet
  - name: ItemType
    enum:
      - Page
      - File
      - Web
      - List
  - name: Site
    cardinality: 10000
  - name: WebId
    cardinality: 10000
  - name: CorrelationId
    cardinality: 10000
