fields:
  - name: ListItemUniqueId
    enum:
      - b86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - a86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - c86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - d86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - e86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
  - name: Id
    range:
      min: 100000000000000000
      max: 999999999999999999
      cardinality: 1000000
  - name: ObjectId
    enum:
      - Not Available
      - 71a0194b-b70c-44a6-82f2-d4670aee4585
      - c5393580-f805-4401-95e8-94b7a6ef2fc2
      - 71a0194b-b70c-44a6-82f2-d4670aee4585
  - name: Operation
    enum:
      - Add app role assignment to service principal.
      - Add OAuth2PermissionGrant.
      - Consent to application.
      - Add app role assignment grant to user.
      - Update application.
  - name: OrganizationId
    enum:
      - b86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - a86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - c86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - d86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - e86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
  - name: RecordType
    range:
      min: 1
      max: 181
      cardinality: 100
  - name: UserId
    enum:
      - asr@testsiem.onmicrosoft.com
      - bsr@testsiem.onmicrosoft.com
  - name: UserKey
    enum:
      - 1003200096971F55@testsiem.onmicrosoft.com
      - 1003200096971F56@testsiem.onmicrosoft.com
  - name: UserType
    range:
      min: 1
      max: 9
      cardinality: 10
  - name: Version
    range:
      min: 1
      max: 5
      cardinality: 10
  - name: Workload
    enum:
      - ExchangeAdmin
      - ExchangeItem
      - ExchangeItemGroup
      - SharePoint
      - SharePointFileOperation
      - OneDrive
      - AzureActiveDirectory
      - AzureActiveDirectoryAccountLogon
      - DataCenterSecurityCmdlet
  - name: ItemType
    enum:
      - Page
      - File
      - Web
      - List
  - name: Site
    enum:
      - b86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - a86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - c86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - d86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - e86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
  - name: WebId
    enum:
      - b86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - a86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - c86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - d86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - e86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
  - name: CorrelationId
    enum:
      - b86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - a86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - c86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - d86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
      - e86ab9d4-fcf1-4b11-8a06-7a8f91b47fbd
