rules:
  - path: /oauth2/token
    methods: ['POST']
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - 'application/json'
        body: |
          {"access_token":"xxxx","expires_in":3600,"token_type":"Bearer","refresh_token":"yyyy"}
  - path: /intel/combined/indicators/v1
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    query_params:
      offset: 0
      limit: 1
      filter: '{filter:_marker:>"[0-9]+"}'
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - application/json
          Next-Page:
            - /intel/combined/indicators/v1?_marker=123
        body: |-
          {
              "meta": {
                  "query_time": 0.012677735,
                  "pagination": {
                      "limit": 1,
                      "total": 2,
                      "offset": 0
                  }
              },
              "resources": [
                  {
                      "id": "hash_sha256_c98e1a7f563824cd448b47613743dcd1c853742b78f42b000192b83d",
                      "indicator": "c98e192bf71a7f97563824cd448b47613743dcd1c853742b78f42b000192b83d",
                      "type": "hash_sha256",
                      "deleted": false,
                      "published_date": 1700547356,
                      "last_updated": 1700547361,
                      "reports": [
                          "reports"
                      ],
                      "actors": [
                          "SALTYSPIDER"
                      ],
                      "malware_families": [
                          "Mofksys"
                      ],
                      "kill_chains": [
                          "Installation",
                          "C2"
                      ],
                      "ip_address_types": [
                          "81.2.69.192"
                      ],
                      "domain_types": [
                          "abc.com"
                      ],
                      "malicious_confidence": "high",
                      "_marker": "17005473618d17ae6353d123235e4158c5c81f25f0",
                      "labels": [
                          {
                              "name": "MaliciousConfidence/High",
                              "created_on": 1700547356,
                              "last_valid_on": 1700547360
                          },
                          {
                              "name": "Malware/Mofksys",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          },
                          {
                              "name": "ThreatType/Commodity",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          },
                          {
                              "name": "ThreatType/CredentialHarvesting",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          },
                          {
                              "name": "ThreatType/InformationStealer",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          }
                      ],
                      "relations": [
                          {
                              "id": "domain.com.yy",
                              "indicator": "domain.ds",
                              "type": "domain",
                              "created_date": 1700547339,
                              "last_valid_date": 1700547339
                          },
                          {
                              "id": "domain.xx.yy",
                              "indicator": "domain.xx.fd",
                              "type": "domain",
                              "created_date": 1700547339,
                              "last_valid_date": 1700547339
                          }
                      ],
                      "targets": [
                          "abc"
                      ],
                      "threat_types": [
                          "Commodity",
                          "CredentialHarvesting",
                          "InformationStealer"
                      ],
                      "vulnerabilities": [
                          "vuln"
                      ]
                  }
              ]
          }
  - path: /intel/combined/indicators/v1
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    query_params:
      _marker: "123"
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - application/json
        body: |-
          {
              "meta": {
                  "query_time": 0.0127735
              },
              "resources": [
                  {
                      "id": "hash_sha2_d98e1a24cd448b47613743dcd1c853742b78f42b000192b83d",
                      "indicator": "hh192bf71a7f9757613743dcd1c853742b78f42b000192b83d",
                      "type": "hash_sha2",
                      "deleted": true,
                      "published_date": 1700547359,
                      "last_updated": 1700547461,
                      "reports": [
                          "reports"
                      ],
                      "actors": [
                          "SALTYSPIDER"
                      ],
                      "malware_families": [
                          "Trojan"
                      ],
                      "kill_chains": [
                          "Installation",
                          "C2"
                      ],
                      "ip_address_types": [
                          "81.2.69.192"
                      ],
                      "domain_types": [
                          "abc.com"
                      ],
                      "malicious_confidence": "low",
                      "_marker": "17005473618d17ae63123235e4158c5c81f25f0",
                      "labels": [
                          {
                              "name": "MaliciousConfidence/High",
                              "created_on": 1700547356,
                              "last_valid_on": 1700547360
                          },
                          {
                              "name": "Malware/Mofksys",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          },
                          {
                              "name": "ThreatType/Commodity",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          },
                          {
                              "name": "ThreatType/CredentialHarvesting",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          },
                          {
                              "name": "ThreatType/InformationStealer",
                              "created_on": 1700547359,
                              "last_valid_on": 1700547359
                          }
                      ],
                      "relations": [
                          {
                              "id": "domain.ab",
                              "indicator": "domain.com",
                              "type": "domain",
                              "created_date": 1700547349,
                              "last_valid_date": 1700547349
                          },
                          {
                              "id": "domain.xx.bb",
                              "indicator": "nodomain.xx.aa",
                              "type": "domain",
                              "created_date": 1700547338,
                              "last_valid_date": 1700547338
                          }
                      ],
                      "targets": [
                          "xyz"
                      ],
                      "threat_types": [
                          "Commodity",
                          "CredentialHarvesting"
                      ],
                      "vulnerabilities": [
                          "vuln"
                      ]
                  }
              ]
          }
  - path: /iocs/combined/indicator/v1
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    query_params:
      offset: 0
      limit: 1
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - application/json
        body: |-
          {
              "meta": {
                  "query_time": 0.012677735,
                  "pagination": {
                      "limit": 1,
                      "total": 2,
                      "offset": 0
                  },
                  "powered_by": "ioc-manager",
                  "trace_id": "abc-111-4bbc-99a1-5c453e391775"
              },
              "errors": null,
              "resources": [
                  {
                      "id": "34874a88935860cf6yyfc856d6abb6f35a29d8c077195ed6291aa8373696b44",
                      "type": "ipv4",
                      "value": "81.2.69.192",
                      "action": "detect again",
                      "severity": "critical",
                      "description": "IS-38887",
                      "metadata": {
                          "filename": "High_Serverity_Heuristic_Sandbox_Threat.docx"
                      },
                      "platforms": [
                          "windows",
                          "mac",
                          "linux"
                      ],
                      "tags": [
                          "IS-38887"
                      ],
                      "expired": false,
                      "deleted": false,
                      "applied_globally": true,
                      "from_parent": false,
                      "created_on": "2023-11-01T10:22:23.10607613Z",
                      "created_by": "abc.it@example.com",
                      "modified_on": "2023-11-01T10:22:23.10607613Z",
                      "modified_by": "example.it@ex.com"
                  }
              ]
          }
  - path: /iocs/combined/indicator/v1
    methods: ['GET']
    request_headers:
      Authorization:
        - 'Bearer xxxx'
    query_params:
      offset: 1
      limit: 1
    responses:
      - status_code: 200
        headers:
          Content-Type:
            - application/json
        body: |-
          {
              "meta": {
                  "query_time": 0.0126735,
                  "powered_by": "ioc-manager",
                  "trace_id": "xyxy-111-4bbc-99a1-5c453e91775"
              },
              "errors": null,
              "resources": [
                  {
                      "id": "34435443546777cf6yyfc856d6abb6f35a29d8c077195ed6291aa8373696b44",
                      "type": "ipv4",
                      "value": "81.2.69.192",
                      "action": "detect failed",
                      "severity": "low",
                      "description": "IS-38987",
                      "metadata": {
                          "filename": "High_Serverity_Heuristic_Sandbox_Threat.txt"
                      },
                      "platforms": [
                          "windows",
                          "mac",
                          "android"
                      ],
                      "tags": [
                          "IS-38887"
                      ],
                      "expired": true,
                      "deleted": false,
                      "applied_globally": true,
                      "from_parent": false,
                      "created_on": "2023-11-01T10:22:23.10607613Z",
                      "created_by": "abc.it@domain.com",
                      "modified_on": "2023-11-01T10:28:23.10607613Z",
                      "modified_by": "example.it@domain.com"
                  }
              ]
          }
