title: Prometheus collector metrics
type: metrics
elasticsearch:
  index_mode: "time_series"
streams:
  - input: prometheus/metrics
    vars:
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - localhost:9090
      - name: metrics_path
        type: text
        title: Metrics Path
        multi: false
        required: false
        show_user: true
        default: /metrics
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
      - name: use_types
        type: bool
        title: Use Types
        multi: false
        required: true
        show_user: true
        default: true
      - name: rate_counters
        type: bool
        title: Rate Counters
        multi: false
        required: true
        show_user: true
        default: true
      - name: leaderelection
        type: bool
        title: Leader Election
        description: Enable leaderelection between a set of Elastic Agents running on Kubernetes
        multi: false
        required: true
        show_user: true
        default: false
      - name: condition
        title: Condition
        description: Condition to filter when to apply this datastream
        type: text
        multi: false
        required: false
        show_user: true
      - name: bearer_token_file
        type: text
        title: 'HTTP config options: bearer_token_file'
        description: If defined, the contents of the file will be read once at initialization and then the value will be used in an HTTP Authorization header.
        multi: false
        secret: false
        required: false
        show_user: false
      - name: ssl.verification_mode
        type: text
        title: SSL Verification Mode
        multi: false
        required: false
        show_user: true
      - name: ssl.certificate_authorities
        type: text
        title: SSL Certificate Authorities
        multi: true
        required: false
        show_user: false
      - name: metrics_filters.exclude
        type: text
        title: Metrics Filters Exclude
        multi: true
        required: false
        show_user: false
        default: []
      - name: metrics_filters.include
        type: text
        title: Metrics Filters Include
        multi: true
        required: false
        show_user: false
        default: []
      - name: username
        type: text
        title: 'HTTP config options: Username'
        description: The username to use for basic authentication.
        multi: false
        required: false
        show_user: false
      - name: password
        type: password
        secret: true
        title: 'HTTP config options: Password'
        description: The password to use for basic authentication.
        multi: false
        required: false
        show_user: false
      - name: connect_timeout
        type: text
        title: 'HTTP config options: connect_timeout'
        description: Total time limit for an HTTP connection to be completed (Default 2 seconds)
        multi: false
        required: false
        show_user: false
      - name: timeout
        type: text
        title: 'HTTP config options: timeout'
        description: Total time limit for HTTP requests made by the module (Default 10 seconds)
        multi: false
        required: false
        show_user: false
      - name: headers
        type: yaml
        title: "HTTP config options: headers"
        description: A list of headers to use with the HTTP request
        multi: false
        required: false
        show_user: false
        default: |
          # headers:
          #   Cookie: abcdef=123456
          #   My-Custom-Header: my-custom-value
      - name: query
        type: yaml
        title: "HTTP config options: query"
        description: An optional value to pass common query params in YAML
        multi: false
        required: false
        show_user: false
        default: |
          # query:
          #   key: value
      - name: data_stream.dataset
        type: text
        title: 'Datasream Dataset name'
        description: Name of Datastream dataset
        multi: false
        default: prometheus.collector
        required: true
        show_user: true
      - name: processors
        type: yaml
        title: Processors
        multi: false
        required: false
        show_user: false
        description: >
          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the logs are parsed. See [Processors](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) for details.

    title: Prometheus collector metrics
    enabled: true
    description: Collect Prometheus collector metrics
