services:
  redisenterprise:
    image: docker.elastic.co/integrations-ci/beats-redisenterprise:${REDISENTERPRISE_VERSION:-5.4.10-22}-3
    build: .
    cap_add:
      - SYS_RESOURCE
    ports:
      - 8070
