title: Grafana metrics
type: metrics
streams:
  - input: prometheus/metrics
    vars:
      - name: period
        type: text
        title: Period
        required: true
        show_user: true
        default: 60s
        description: How often to scrape metrics from Grafana.
      - name: tags
        type: text
        title: Tags
        multi: true
        required: false
        show_user: false
        default:
          - grafana-metrics
        description: Tags to add to each event.
      - name: processors
        type: yaml
        title: Processors
        required: false
        show_user: false
        description: Custom Elastic Agent processors in YAML format.
    title: Grafana metrics
    description: Collect Grafana Prometheus metrics
elasticsearch:
  index_mode: time_series
