title: Grafana metrics
type: metrics
streams:
  - input: prometheus/metrics
    vars:
      - name: period
        type: text
        title: Period
        required: true
        show_user: true
        default: 60s
      - name: tags
        type: text
        title: Tags
        multi: true
        required: false
        show_user: false
        default:
          - grafana-metrics
      - name: processors
        type: yaml
        title: Processors
        required: false
        show_user: false
    title: Grafana metrics
    description: Collect Grafana Prometheus metrics
elasticsearch:
  index_mode: time_series
