title: Kubernetes scheduler metrics
release: experimental
type: metrics
streams:
- input: kubernetes/metrics
  vars:
  - name: hosts
    type: text
    title: Hosts
    multi: true
    required: true
    show_user: true
    default:
    - http://localhost:10251
  - name: period
    type: text
    title: Period
    multi: false
    required: true
    show_user: true
    default: 10s
  title: Kubernetes scheduler metrics
  description: Collect Kubernetes scheduler metrics
