title: Kubernetes PersistentVolumeClaim metrics
type: metrics
streams:
  - input: kubernetes/metrics
    enabled: false
    vars:
      - name: add_metadata
        type: bool
        title: Add Metadata
        multi: false
        required: true
        show_user: true
        default: true
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - kube-state-metrics:8080
      - name: leaderelection
        type: bool
        title: Leader Election
        multi: false
        required: true
        show_user: true
        default: true
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
      - name: node
        type: text
        title: Node to watch resources from for metadata
        multi: false
        required: false
        show_user: false
      - name: namespace
        type: text
        title: Namespace to watch resources from for metadata
        multi: false
        required: false
        show_user: false
      - name: bearer_token_file
        type: text
        title: Bearer Token File
        multi: false
        required: false
        show_user: false
        default: /var/run/secrets/kubernetes.io/serviceaccount/token
      - name: ssl.certificate_authorities
        type: text
        title: SSL Certificate Authorities
        multi: true
        required: false
        show_user: false
      - name: processors
        type: yaml
        title: Processors
        multi: false
        required: false
        show_user: false
        description: >
          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the events are shipped. See [Processors](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) for details.

    title: Kubernetes PersistentVolumeClaim metrics
    description: Collect Kubernetes PersistentVolumeClaim metrics from kube_state_metrics
