---
name: Bump latest elastic-stack test version
pipelineid: 'bump-latest-elastic-stack-version'

actions:
  default:
    title: '[updatecli] Update latest snapshot to {{ source "latestSnapshot" }}'
    kind: github/pullrequest
    scmid: default
    spec:
      labels:
        - automation
        - dependency

scms:
  default:
    kind: github
    spec:
      owner: '{{ .scm.owner }}'
      repository: '{{ .scm.repository }}'
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      commitusingapi: true
      branch: main

sources:
  latestSnapshot:
    name: Get latest snapshot
    kind: json
    spec:
      file: https://storage.googleapis.com/artifacts-api/snapshots/main.json
      key: .version
  latestSnapshotMajorMinor:
    name: Get latest snapshort major and minor
    kind: json
    spec:
      file: https://storage.googleapis.com/artifacts-api/snapshots/main.json
      key: .version
    transformers:
      - findsubmatch:
          pattern: '(^\d+\.\d+)\.[^\s]+$'
          captureindex: 1

targets:
  update-snapshot:
    name: '[updatecli] Update latest snapshot to {{ source "latestSnapshot" }}'
    kind: file
    sourceid: latestSnapshot
    scmid: default
    spec:
      file: '.buildkite/pipeline.schedule-daily.yml'
      matchpattern: '(STACK_VERSION:) 8\.[^\s]*\.[^\s]*'
      replacepattern: '$1 {{ source "latestSnapshot" }}'

  update-snapshot-label:
    name: '[updatecli] Update latest snapshot label step to {{ source "latestSnapshotMajorMinor" }}'
    kind: file
    sourceid: latestSnapshotMajorMinor
    scmid: default
    spec:
      file: '.buildkite/pipeline.schedule-daily.yml'
      matchpattern: '(Stack Version) v8\.\d+"'
      replacepattern: 'Stack Version v{{ source "latestSnapshotMajorMinor" }}"'

  update-snapshot-weekly-build:
    name: '[updatecli] Update latest snapshot in catalog-info for weekly schedule to {{ source "latestSnapshot" }}'
    kind: file
    sourceid: latestSnapshot
    scmid: default
    spec:
      file: 'catalog-info.yaml'
      # matchpattern: '(STACK_VERSION:) 8\..*$'
      matchpattern: '(ELASTIC_PR_COMMENTS_ENABLED:)'
      replacepattern: '$1 {{ source "latestSnapshot" }}'
