- name: kubernetes.node
  type: group
  fields:
    - name: start_time
      type: date
      description: |
        Start time
    - name: cpu
      type: group
      fields:
        - name: usage
          type: group
          fields:
            - name: core
              type: group
              fields:
                - name: ns
                  type: long
                  metric_type: gauge
                  description: |
                    Node CPU Core usage nanoseconds
            - name: nanocores
              type: long
              metric_type: gauge
              description: |
                CPU used nanocores
    - name: memory
      type: group
      fields:
        - name: available
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Total available memory
        - name: usage
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Total memory usage
        - name: rss
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                RSS memory usage
        - name: workingset
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Working set memory usage
        - name: pagefaults
          type: long
          metric_type: counter
          description: |
            Number of page faults
        - name: majorpagefaults
          type: long
          metric_type: counter
          description: |
            Number of major page faults
    - name: network
      type: group
      fields:
        - name: rx
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: counter
              description: |
                Received bytes
            - name: errors
              type: long
              description: |
                Rx errors
        - name: tx
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: counter
              description: |
                Transmitted bytes
            - name: errors
              type: long
              metric_type: counter
              description: |
                Tx errors
    - name: fs
      type: group
      fields:
        - name: capacity
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Filesystem total capacity in bytes
        - name: available
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Filesystem total available in bytes
        - name: used
          type: group
          fields:
            - name: bytes
              type: long
              format: bytes
              unit: byte
              metric_type: gauge
              description: |
                Filesystem total used in bytes
        - name: inodes
          type: group
          fields:
            - name: used
              type: long
              metric_type: gauge
              description: |
                Number of used inodes
            - name: count
              type: long
              metric_type: gauge
              description: |
                Number of inodes
            - name: free
              type: long
              metric_type: gauge
              description: |
                Number of free inodes
    - name: runtime
      type: group
      fields:
        - name: imagefs
          type: group
          fields:
            - name: capacity
              type: group
              fields:
                - name: bytes
                  type: long
                  format: bytes
                  unit: byte
                  metric_type: gauge
                  description: |
                    Image filesystem total capacity in bytes
            - name: available
              type: group
              fields:
                - name: bytes
                  type: long
                  format: bytes
                  unit: byte
                  metric_type: gauge
                  description: |
                    Image filesystem total available in bytes
            - name: used
              type: group
              fields:
                - name: bytes
                  type: long
                  format: bytes
                  unit: byte
                  metric_type: gauge
                  description: |
                    Image filesystem total used in bytes
