- name: kubernetes.persistentvolumeclaim
  type: group
  fields:
    - name: name
      dimension: true
      type: keyword
      description: PVC name.
    - name: volume_name
      type: keyword
      description: Binded volume name.
    - name: request_storage.bytes
      type: long
      unit: byte
      metric_type: gauge
      description: Requested capacity.
    - name: phase
      type: keyword
      description: PVC phase.
    - name: access_mode
      type: keyword
      description: Access mode.
    - name: storage_class
      type: keyword
      description: Storage class for the PVC.
