type: metrics
title: Traefik health metrics
streams:
  - input: traefik/metrics
    vars:
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
    title: Traefik health metrics
    description: Collect Traefik health metrics
