- name: Tenant
  cardinality: 100000
- name: category
  cardinality: 100000
- name: operationName
  cardinality: 100000
- name: properties.Timestamp
  period: -24h
- name: properties.TargetDeviceName
  cardinality: 100000
- name: properties.DestinationIPAddress
  cardinality: 100000
- name: properties.DestinationPort
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.DeviceName
  cardinality: 100000
- name: properties.IPAddress
  cardinality: 100000
- name: properties.OSPlatform
  cardinality: 100000
- name: properties.DeviceType
  cardinality: 100000
- name: properties.Protocol
  cardinality: 100000
- name: properties.AccountDomain
  cardinality: 100000
- name: properties.AccountSid
  cardinality: 100000
- name: properties.AccountName
  cardinality: 100000
- name: properties.AccountDisplayName
  cardinality: 100000
- name: properties.AccountObjectId
  cardinality: 100000
- name: properties.AccountUpn
  cardinality: 100000
- name: properties.ActionType
  cardinality: 100000
- name: properties.AdditionalFields
  cardinality: 100000
- name: properties.Application
  cardinality: 100000
- name: properties.DestinationDeviceName
  cardinality: 100000
- name: properties.FailureReason
  cardinality: 100000
- name: properties.Isp
  cardinality: 100000
- name: properties.Location
  cardinality: 100000
- name: properties.LogonType
  cardinality: 100000
- name: properties.Port
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.ReportId
  cardinality: 100000
- name: properties.TargetAccountDisplayName
  cardinality: 100000
- name: properties.IsAdminOperation
  cardinality: 100000
- name: properties.Query
  cardinality: 100000
- name: properties.QueryTarget
  cardinality: 100000
- name: properties.QueryType
  cardinality: 100000
- name: properties.TargetAccountUpn
  cardinality: 100000
- name: properties.ISP
  cardinality: 100000
- name: properties.AccountId
  cardinality: 100000
- name: properties.AccountType
  cardinality: 100000
- name: properties.ActivityObjects
  cardinality: 100000
- name: properties.ActivityType
  cardinality: 100000
- name: properties.AppInstanceId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.ApplicationId
  cardinality: 100000
- name: properties.City
  cardinality: 100000
- name: properties.CountryCode
  cardinality: 100000
- name: properties.IPCategory
  cardinality: 100000
- name: properties.IPTags
  cardinality: 100000
- name: properties.IsAnonymousProxy
  cardinality: 100000
- name: properties.IsExternalUser
  cardinality: 100000
- name: properties.IsImpersonated
  cardinality: 100000
- name: properties.ObjectId
  cardinality: 100000
- name: properties.ObjectName
  cardinality: 100000
- name: properties.ObjectType
  cardinality: 100000
- name: properties.RawEventData.ChatThreadId
  cardinality: 100000
- name: properties.RawEventData.CommunicationType
  cardinality: 100000
- name: properties.RawEventData.CreationTime
  period: -24h
- name: properties.RawEventData.ExtraProperties
  cardinality: 100000
- name: properties.RawEventData.Id
  cardinality: 100000
- name: properties.RawEventData.ItemName
  cardinality: 100000
- name: properties.RawEventData.MessageId
  cardinality: 100000
- name: properties.RawEventData.MessageVersion
  cardinality: 100000
- name: properties.RawEventData.MessageVisibilityTime
  period: -24h
- name: properties.RawEventData.Operation
  cardinality: 100000
- name: properties.RawEventData.OrganizationId
  cardinality: 100000
- name: properties.RawEventData.ParticipantInfo.HasForeignTenantUsers
  cardinality: 100000
- name: properties.RawEventData.ParticipantInfo.HasGuestUsers
  cardinality: 100000
- name: properties.RawEventData.ParticipantInfo.HasOtherGuestUsers
  cardinality: 100000
- name: properties.RawEventData.ParticipantInfo.HasUnauthenticatedUsers
  cardinality: 100000
- name: properties.RawEventData.ParticipantInfo.ParticipatingDomains
  cardinality: 100000
- name: properties.RawEventData.ParticipantInfo.ParticipatingSIPDomains
  cardinality: 100000
- name: properties.RawEventData.ParticipantInfo.ParticipatingTenantIds
  cardinality: 100000
- name: properties.RawEventData.RecordType
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.RawEventData.ResourceTenantId
  cardinality: 100000
- name: properties.RawEventData.UserId
  cardinality: 100000
- name: properties.RawEventData.UserKey
  cardinality: 100000
- name: properties.RawEventData.UserType
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.RawEventData.Version
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.RawEventData.Workload
  cardinality: 100000
- name: properties.UserAgent
  cardinality: 100000
- name: properties.UserAgentTags
  cardinality: 100000
- name: properties.Address
  cardinality: 100000
- name: properties.BlastRadius
  cardinality: 100000
- name: properties.ChangeSource
  cardinality: 100000
- name: properties.CloudSid
  cardinality: 100000
- name: properties.CompanyName
  cardinality: 100000
- name: properties.Country
  cardinality: 100000
- name: properties.CreatedDateTime
  period: -24h
- name: properties.CriticalityLevel
  cardinality: 100000
- name: properties.DeletedDateTime
  cardinality: 100000
- name: properties.Department
  cardinality: 100000
- name: properties.DistinguishedName
  cardinality: 100000
- name: properties.EmailAddress
  cardinality: 100000
- name: properties.EmployeeId
  cardinality: 100000
- name: properties.GivenName
  cardinality: 100000
- name: properties.IsAccountEnabled
  cardinality: 100000
- name: properties.JobTitle
  cardinality: 100000
- name: properties.Manager
  cardinality: 100000
- name: properties.OnPremSid
  cardinality: 100000
- name: properties.OtherMailAddresses
  cardinality: 100000
- name: properties.Phone
  cardinality: 100000
- name: properties.RiskLevel
  cardinality: 100000
- name: properties.RiskLevelDetails
  cardinality: 100000
- name: properties.SipProxyAddress
  cardinality: 100000
- name: properties.SourceProvider
  cardinality: 100000
- name: properties.State
  cardinality: 100000
- name: properties.Surname
  cardinality: 100000
- name: properties.Tags
  cardinality: 100000
- name: properties.Type
  cardinality: 100000
- name: properties.AuditSource
  cardinality: 100000
- name: properties.LastSeenForUser
  cardinality: 100000
- name: properties.OAuthAppId
  cardinality: 100000
- name: properties.SessionData
  cardinality: 100000
- name: properties.UncommonForUser
  cardinality: 100000
- name: properties.AlertId
  cardinality: 100000
- name: properties.DeviceId
  cardinality: 100000
- name: properties.EmailSubject
  cardinality: 100000
- name: properties.EntityType
  cardinality: 100000
- name: properties.EvidenceDirection
  cardinality: 100000
- name: properties.EvidenceRole
  cardinality: 100000
- name: properties.FileName
  cardinality: 100000
- name: properties.FileSize
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.FolderPath
  cardinality: 100000
- name: properties.LocalIP
  cardinality: 100000
- name: properties.MachineGroup
  cardinality: 100000
- name: properties.NetworkMessageId
  cardinality: 100000
- name: properties.OAuthApplicationId
  cardinality: 100000
- name: properties.ProcessCommandLine
  cardinality: 100000
- name: properties.RegistryKey
  cardinality: 100000
- name: properties.RegistryValueData
  cardinality: 100000
- name: properties.RegistryValueName
  cardinality: 100000
- name: properties.RemoteIP
  cardinality: 100000
- name: properties.RemoteUrl
  cardinality: 100000
- name: properties.SHA1
  cardinality: 100000
- name: properties.SHA256
  cardinality: 100000
- name: properties.ServiceSource
  cardinality: 100000
- name: properties.ThreatFamily
  cardinality: 100000
- name: properties.AttackTechniques
  cardinality: 100000
- name: properties.Category
  cardinality: 100000
- name: properties.DetectionSource
  cardinality: 100000
- name: properties.Severity
  enum:
    - low
    - high
    - medium
    - critical
    - informational
- name: properties.Title
  cardinality: 100000
- name: properties.AppGuardContainerId
  cardinality: 100000
- name: properties.CreatedProcessSessionId
  cardinality: 100000
- name: properties.InitiatingProcessAccountDomain
  cardinality: 100000
- name: properties.InitiatingProcessAccountName
  cardinality: 100000
- name: properties.InitiatingProcessAccountObjectId
  cardinality: 100000
- name: properties.InitiatingProcessAccountSid
  cardinality: 100000
- name: properties.InitiatingProcessAccountUpn
  cardinality: 100000
- name: properties.InitiatingProcessCommandLine
  cardinality: 100000
- name: properties.InitiatingProcessCreationTime
  cardinality: 100000
- name: properties.InitiatingProcessFileName
  cardinality: 100000
- name: properties.InitiatingProcessFileSize
  cardinality: 100000
- name: properties.InitiatingProcessFolderPath
  cardinality: 100000
- name: properties.InitiatingProcessId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.InitiatingProcessIntegrityLevel
  cardinality: 100000
- name: properties.InitiatingProcessLogonId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.InitiatingProcessMD5
  cardinality: 100000
- name: properties.InitiatingProcessParentCreationTime
  cardinality: 100000
- name: properties.InitiatingProcessParentFileName
  cardinality: 100000
- name: properties.InitiatingProcessParentId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.InitiatingProcessRemoteSessionDeviceName
  cardinality: 100000
- name: properties.InitiatingProcessRemoteSessionIP
  cardinality: 100000
- name: properties.InitiatingProcessSHA1
  cardinality: 100000
- name: properties.InitiatingProcessSHA256
  cardinality: 100000
- name: properties.InitiatingProcessSessionId
  cardinality: 100000
- name: properties.InitiatingProcessSignatureStatus
  cardinality: 100000
- name: properties.InitiatingProcessSignerType
  cardinality: 100000
- name: properties.InitiatingProcessTokenElevation
  cardinality: 100000
- name: properties.InitiatingProcessVersionInfoCompanyName
  cardinality: 100000
- name: properties.InitiatingProcessVersionInfoFileDescription
  cardinality: 100000
- name: properties.InitiatingProcessVersionInfoInternalFileName
  cardinality: 100000
- name: properties.InitiatingProcessVersionInfoOriginalFileName
  cardinality: 100000
- name: properties.InitiatingProcessVersionInfoProductName
  cardinality: 100000
- name: properties.InitiatingProcessVersionInfoProductVersion
  cardinality: 100000
- name: properties.IsInitiatingProcessRemoteSession
  cardinality: 100000
- name: properties.IsProcessRemoteSession
  cardinality: 100000
- name: properties.LogonId
  cardinality: 100000
- name: properties.MD5
  cardinality: 100000
- name: properties.ProcessCreationTime
  cardinality: 100000
- name: properties.ProcessId
  cardinality: 100000
- name: properties.ProcessIntegrityLevel
  cardinality: 100000
- name: properties.ProcessRemoteSessionDeviceName
  cardinality: 100000
- name: properties.ProcessRemoteSessionIP
  cardinality: 100000
- name: properties.ProcessTokenElevation
  cardinality: 100000
- name: properties.ProcessVersionInfoCompanyName
  cardinality: 100000
- name: properties.ProcessVersionInfoFileDescription
  cardinality: 100000
- name: properties.ProcessVersionInfoInternalFileName
  cardinality: 100000
- name: properties.ProcessVersionInfoOriginalFileName
  cardinality: 100000
- name: properties.ProcessVersionInfoProductName
  cardinality: 100000
- name: properties.ProcessVersionInfoProductVersion
  cardinality: 100000
- name: properties.FileOriginIP
  cardinality: 100000
- name: properties.FileOriginUrl
  cardinality: 100000
- name: properties.LocalPort
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.RemoteDeviceName
  cardinality: 100000
- name: properties.RemotePort
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.CertificateCountersignatureTime
  period: -24h
- name: properties.CertificateCreationTime
  period: -24h
- name: properties.CertificateExpirationTime
  period: -24h
- name: properties.CertificateSerialNumber
  cardinality: 100000
- name: properties.CrlDistributionPointUrls
  cardinality: 100000
- name: properties.IsRootSignerMicrosoft
  cardinality: 100000
- name: properties.IsSigned
  cardinality: 100000
- name: properties.IsTrusted
  cardinality: 100000
- name: properties.Issuer
  cardinality: 100000
- name: properties.IssuerHash
  cardinality: 100000
- name: properties.SignatureType
  cardinality: 100000
- name: properties.Signer
  cardinality: 100000
- name: properties.SignerHash
  cardinality: 100000
- name: properties.FileOriginReferrerUrl
  cardinality: 100000
- name: properties.IsAzureInfoProtectionApplied
  cardinality: 100000
- name: properties.PreviousFileName
  cardinality: 100000
- name: properties.PreviousFolderPath
  cardinality: 100000
- name: properties.RequestAccountDomain
  cardinality: 100000
- name: properties.RequestAccountName
  cardinality: 100000
- name: properties.RequestAccountSid
  cardinality: 100000
- name: properties.RequestProtocol
  cardinality: 100000
- name: properties.RequestSourceIP
  cardinality: 100000
- name: properties.RequestSourcePort
  cardinality: 100000
- name: properties.SensitivityLabel
  cardinality: 100000
- name: properties.SensitivitySubLabel
  cardinality: 100000
- name: properties.ShareName
  cardinality: 100000
- name: properties.AadDeviceId
  cardinality: 100000
- name: properties.AssetValue
  cardinality: 100000
- name: properties.IsInternetFacing
  cardinality: 100000
- name: properties.DeviceManualTags
  cardinality: 100000
- name: properties.DeviceDynamicTags
  cardinality: 100000
- name: properties.ExposureLevel
  cardinality: 100000
- name: properties.SensorHealthState
  cardinality: 100000
- name: properties.ExclusionReason
  cardinality: 100000
- name: properties.IsExcluded
  cardinality: 100000
- name: properties.ClientVersion
  cardinality: 100000
- name: properties.DeviceCategory
  cardinality: 100000
- name: properties.DeviceSubtype
  cardinality: 100000
- name: properties.IsAzureADJoined
  cardinality: 100000
- name: properties.JoinType
  cardinality: 100000
- name: properties.LoggedOnUsers
  cardinality: 100000
- name: properties.MergedDeviceIds
  cardinality: 100000
- name: properties.MergedToDeviceId
  cardinality: 100000
- name: properties.Model
  cardinality: 100000
- name: properties.OSArchitecture
  cardinality: 100000
- name: properties.OSBuild
  cardinality: 100000
- name: properties.OSDistribution
  cardinality: 100000
- name: properties.OSVersion
  cardinality: 100000
- name: properties.OSVersionInfo
  cardinality: 100000
- name: properties.OnboardingStatus
  cardinality: 100000
- name: properties.PublicIP
  cardinality: 100000
- name: properties.RegistryDeviceTag
  cardinality: 100000
- name: properties.Vendor
  cardinality: 100000
- name: properties.IsLocalAdmin
  cardinality: 100000
- name: properties.RemoteIPType
  cardinality: 100000
- name: properties.LocalIPType
  cardinality: 100000
- name: properties.ConnectedNetworks
  cardinality: 100000
- name: properties.DefaultGateways
  cardinality: 100000
- name: properties.DnsAddresses
  cardinality: 100000
- name: properties.IPAddresses
  cardinality: 100000
- name: properties.IPv4Dhcp
  cardinality: 100000
- name: properties.IPv6Dhcp
  cardinality: 100000
- name: properties.MacAddress
  cardinality: 100000
- name: properties.NetworkAdapterName
  cardinality: 100000
- name: properties.NetworkAdapterStatus
  cardinality: 100000
- name: properties.NetworkAdapterType
  cardinality: 100000
- name: properties.NetworkAdapterVendor
  cardinality: 100000
- name: properties.TunnelType
  cardinality: 100000
- name: properties.PreviousRegistryKey
  cardinality: 100000
- name: properties.PreviousRegistryValueData
  cardinality: 100000
- name: properties.PreviousRegistryValueName
  cardinality: 100000
- name: properties.RegistryValueType
  cardinality: 100000
- name: properties.DetectionMethods
  cardinality: 100000
- name: properties.FileType
  cardinality: 100000
- name: properties.RecipientEmailAddress
  cardinality: 100000
- name: properties.RecipientObjectId
  cardinality: 100000
- name: properties.SenderDisplayName
  cardinality: 100000
- name: properties.SenderFromAddress
  cardinality: 100000
- name: properties.SenderObjectId
  cardinality: 100000
- name: properties.ThreatNames
  cardinality: 100000
- name: properties.ThreatTypes
  cardinality: 100000
- name: properties.AttachmentCount
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.AuthenticationDetails
  cardinality: 100000
- name: properties.ConfidenceLevel
  cardinality: 100000
- name: properties.Connectors
  cardinality: 100000
- name: properties.DeliveryAction
  cardinality: 100000
- name: properties.DeliveryLocation
  cardinality: 100000
- name: properties.EmailAction
  cardinality: 100000
- name: properties.EmailActionPolicy
  cardinality: 100000
- name: properties.EmailActionPolicyGuid
  cardinality: 100000
- name: properties.EmailClusterId
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.EmailDirection
  cardinality: 100000
- name: properties.EmailLanguage
  cardinality: 100000
- name: properties.InternetMessageId
  cardinality: 100000
- name: properties.OrgLevelAction
  cardinality: 100000
- name: properties.OrgLevelPolicy
  cardinality: 100000
- name: properties.SenderFromDomain
  cardinality: 100000
- name: properties.SenderIPv4
  cardinality: 100000
- name: properties.SenderIPv6
  cardinality: 100000
- name: properties.SenderMailFromAddress
  cardinality: 100000
- name: properties.SenderMailFromDomain
  cardinality: 100000
- name: properties.Subject
  cardinality: 100000
- name: properties.UrlCount
  cardinality: 100000
  range:
    min: 10
    max: 10000
- name: properties.UserLevelAction
  cardinality: 100000
- name: properties.UserLevelPolicy
  cardinality: 100000
- name: properties.Url
  cardinality: 100000
- name: properties.UrlDomain
  cardinality: 100000
- name: properties.UrlLocation
  cardinality: 100000
- name: properties.ActionResult
  cardinality: 100000
- name: properties.ActionTrigger
  cardinality: 100000
- name: properties.Action
  cardinality: 100000
- name: properties.IsClickedThrough
  cardinality: 100000
- name: properties.UrlChain
  cardinality: 100000
- name: properties.Workload
  cardinality: 100000
- name: tenantId
  cardinality: 100000
- name: time
  period: -24h
- name: _TimeReceivedBySvc
  period: -24h
