version: '2.3'
services:
  spycloud:
    image: docker.elastic.co/observability/stream:v0.13.0
    hostname: spycloud
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config.yml
